### ISSUE TITLE
Check For Linter Existence In PATH And Fall Back To GOPATH/bin If Necessary

### ISSUE THREAD

**Issue by joefitzgerald** [alecthomas/gometalinter#102]
> https://github.com/joefitzgerald/go-plus/issues/384#issuecomment-198505818

In some cases, people don't put `$GOPATH/bin` in their PATH, and so a linter is not found or executed, even though it is installed and available in the user's `$GOPATH/bin` directory. It would be nice to:

* Check for the existence of a linter and create a warning if it is not found
* When checking for the existence of a linter, and it is not found in PATH, check GOPATH/bin before creating a warning

**Comment by alecthomas** [comment]
This doesn't seem like a bad idea, but it's not clear to me how any linter would have worked before, as they're all installed into `$GOPATH/bin`.

**Comment by alecthomas** [comment]
BTW, the first point already existed. If gometalinter can't find a linter it will print something like:

```
WARNING: exec: "dupl": executable file not found in $PATH
```
