### ISSUE TITLE
call to gotype ignores packages named "*_test"

### ISSUE THREAD

**Issue by craigfurman** [alecthomas/gometalinter#104]
Gometalinter calls gotype in a way that results in files in the "_test" () package are ignored. This affects the workflow of devs who like to test packages in a "black box" style, with no access to private members.

GIven a package in `$GOPATH/src/something`:
`something.go`:
```go
package something

// no code here, no linting errors by definition
```

`something_test.go`:
```go
package something_test

// There is no function called Foo(), this is a compiler error
var _ = Foo()
```

Running gotype as gometalinter does: `gotype -a .` exits with 0 and prints nothing to stdout / stderr. Gotype is ignoring files in the "something_test" package and therefore does not spot the compiler error.

Running gotype with file rather than directory arguments: `gotype something_test.go` exits with 2 and prints `something_test.go:3:9: undeclared name: Foo` to stderr.

Unfortunately, when run each file as an argument, making use of a shell glob (`gotype *`) it complains about the 2 files having a different package.

I haven't really got any suggestions on how to fix this except calling gotype once per file present under the directory gometalinter is being called from, but I'm not sure if this would be too slow.

@joefitzgerald this may be of interest to you, as the latest version of go-plus relies on gometalinter to spot compiler errors (unless I'm mistaken).

**Comment by joefitzgerald** [comment]
Have you tried the --test flag?

**Comment by craigfurman** [comment]
Those gotype examples above are representative of running gometafilter with
"--tests".

**Comment by alecthomas** [comment]
gotype itself doesn't support this, so there's not much gometalinter can do. I think it's out of scope for gometalinter to work around issues with individual linters.

Also, just FYI, `gotype` is not executed with `*` it is executed with `gotype -e -a .`. You can see this by enabling `--debug` on `gometalinter`.

**Comment by alecthomas** [comment]
BTW, calling with individual files won't work either, as gotype only considers symbols directly in the files being analysed. So if a file uses symbols from another file it will result in an error.

**Comment by craigfurman** [comment]
Yeah, seems fair enough that it's out of scope for gometalinter. Would it
be worth mentioning the lack of gotype for "_test" packages in the readme?

The varargs example was just another example of how gotype can be called,
and the tradeoffs of that approach.
