### ISSUE TITLE
Supply the column end index

### ISSUE THREAD

**Issue by manucorporat** [alecthomas/gometalinter#106]
Right now, `gometalinter` provides the line and column start index which is great. But it would great to get the end index of column in order to implement better highlighting in editors like atom and others.

Please, see:
https://github.com/joefitzgerald/gometalinter-linter/pull/30

**Comment by alecthomas** [comment]
This doesn't seem unreasonable, but [none of the linters support this](https://github.com/alecthomas/gometalinter/blob/master/main.go#L117) so it would never be populated...

**Comment by alecthomas** [comment]
In the case of editor linters, they typically have some heuristics to highlight the closest symbol when a range is unavailable. I'm not sure if the Atom plugin does this or not.
