### ISSUE TITLE
configuration does not work

### ISSUE THREAD

**Issue by alexei-led** [alecthomas/gometalinter#107]
I'm using following flags `--disable=dupl, --dupl-threshold=500, --cyclo-over=15` - no effect (also after restart)
linter complains on "complexity 14" and "dull" code of 50 lines

I'm using Atom 1.6.1 and gometalinter 1.1.0

**Comment by alecthomas** [comment]
Have you tried those arguments on the command line? If that works the problem is with the editor configuration.

**Comment by alexei-led** [comment]
Command line it works. 
Here is my editor config
```
"go-plus": {}
  "gometalinter-linter":
    args: [
      "--disable=dupl --dupl-threshold=500 --cyclo-over=15"
    ]
```

**Comment by alecthomas** [comment]
Ah. Each argument needs to be a separate string in the args list, not one big string.

**Comment by alexei-led** [comment]
Yep, you are right. Comma separated strings and adding `--json` (did not work without).
