### ISSUE TITLE
Allow installation of all of the metalinters' code into vendor folder

### ISSUE THREAD

**Issue by milanaleksic** [alecthomas/gometalinter#112]
*Failure scenario:*
I use metalinter in a CI (semaphoreci.com in this particular case, but not relevant) and I have a "prepare stage" that installs metalinter with all its tools.

If metalinter author adds a new lint tool, although no changes are made in the project that utilizes metalinter for verification, we end up having a failed build if I retry the build.

*Fixing* this then ends up being quite a task: one must then `--install --update --force` locally to get the same new linters for reproduction purposes locally, fix everything and push again. I think this can be optimized.

**Proposal**
Would it be possible for metalinter to run in "detached" mode and build linters based on current state of those linters in a vendor project? Maybe use an additional folder locally to store all build linter binaries to avoid polluting `$GOPATH/bin`?

*Please feel free to reject this proposal if it's technically not possible*

**Comment by alecthomas** [comment]
I think the solution that other people use is to first `--disable-all` then explicitly enable just the linters you need. This seems simpler to me, and should be effective for your situation. I'll add it to the FAQ.

**Comment by milanaleksic** [comment]
Alright, but what if then a linter updates with additional checks? Same problem

**Comment by alecthomas** [comment]
Same problem yes, but I don't think that occurs all that frequently.

I'm not really sure what you mean by "detached" mode. If you're talking about vendoring the linters inside gometalinter, I don't believe it's possible to install vendored commands. eg. if I have `github.com/alecthomas/gometalinter/vendor/github.com/kisielk/errcheck` I can not `go install github.com/kisielk/errcheck` even if vendoring is enabled.

Another option would be to have a separate `GOPATH` entry inside gometalinter, eg. `github.com/alecthomas/gometalinter/linters/src/github.com/kisielk/errcheck`. This would require that gometalinter manage that `GOPATH` itself.

Yet another option would be to use one of the existing vendoring tools, and hope that they support installation of executables. This would, however, require users to install and run that tool.

I appreciate that the current situation is not great, but I don't think these options are the solution. 

If every underlying linter used gopkg.in + semver, we could just pin the versions directly...

**Comment by milanaleksic** [comment]
OK. All options seem to be quite far off for a small-scale project like this so I do acknowledge it might be more than just a simple work: one would have to rethink quite a bit to overcome this dependency problem so I guess we can just forget about this. If I ever get to think about this I might send you a PR with a proposed solution - at this time I also wouldn't know how easy it would be to build local binaries.

On my side I guess most easy solution is not to declare full metalinter success as a mandatory step, just as a `WARN` inside a build to overcome some edge cases / weird situations as explained above.

Thanks for the brainstorming session

**Comment by alecthomas** [comment]
Thanks for bringing it up. I have thought about this before, but I couldn't figure out a reasonable solution.

Another option for your case might be to set GOBIN to something once, then install the linters and not update them. Unfortunately this doesn't mean that your clients will have the same versions though.

**Comment by alecthomas** [comment]
FYI this has subsequently been implemented.
