### ISSUE TITLE
bug with vendor

### ISSUE THREAD

**Issue by on99** [alecthomas/gometalinter#115]
If third party dependency only lies in `./vendor` but not `$GOPATH/src`, `gometalinter` produces errors but it shouldn't.

Please checkout a simple example here: https://github.com/on99/demo

**Comment by alecthomas** [comment]
Did you go through the process outlined in the CONTRIBUTING.md document?

**Comment by GarethLewin** [comment]
99% sure it's because you don't use `go install` or `go build -i`

These are limitations of the linters that gometalinter runs, and is not an issue with gometalinter itself.

**Comment by on99** [comment]
@GarethLewin  there is nothing to do with `go install` or `go build -i`

@alecthomas sorry, I just go through it and found the errors are caused by those linters, not gometalinter itself.
