### ISSUE TITLE
gometalinter reports parser and typecheck errors as linter errors

### ISSUE THREAD

**Issue by dominikh** [alecthomas/gometalinter#116]
When a package fails to parse or typecheck, unconvert will print these as errors. gometalinter, however, unconditionally assumes that any output by unconvert is about unnecessary type conversions:

```
$ echo gibberish > somefile.go
$ gometalinter .
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (staticcheck)
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (golint)
somefile.go:1:1:warning: redundant type conversion (unconvert)
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (gosimple)
```

And for gofmt it causes even weirder results:

```
$ gometalinter --enable=gofmt
somefile.go:1:1: expected 'package', found 'IDENT' gibberish:1::warning: file is not gofmted (gofmt)
```

Where the gofmt output seems to merge into the line/column information.

**Comment by alecthomas** [comment]
The first one doesn't really concern me; it's an artefact of mapping unconvert to a more reasonable format (which actually looks like it was [subsequently fixed](https://github.com/mdempsky/unconvert/commit/e309409e344cde31f3b0706a68f17eb2166b3b4b) upstream).

The second one is probably happening for the same reason, though I haven't confirmed it.

**Comment by dominikh** [comment]
> The first one doesn't really concern me; it's an artefact of mapping unconvert to a more reasonable format

It's not an artifact, it's a bug. You claim that gometalinter is `intended for use with editor/IDE integration`. However, it becomes vastly less useful if the outputted information can't be trusted. If my IDE tells me that a conversion is unnecessary, while in fact an identifier is unknown, that's bad UX. Worse, it might lead IDE's to offer quickfixes such as removing the type conversion (which may or may not be a type conversion).

**Comment by alecthomas** [comment]
Your statement is theoretically correct, but ignores the practicalities of interacting with a large number of tools of varying and questionable quality. 

Unconvert is a great example. Initially, it output 4-5 lines of verbose text for each hint it gave, and only the first line contained a valid location. The message override fixes that. However, as you've seen it also overrides parse errors. To correct this you would need a set of regex:message override mappings, as well as patterns to match any other messages the linter output. This is impractical, particularly as some linters output different messages under unusual circumstances which are very hard/impossible to enumerate.

And, yes, gometalinter is useful for IDE integration, but it is a tool that relies on other tools of varying quality. That must be taken into consideration, and blindly applying fixes based on it would be unwise.

**Comment by alecthomas** [comment]
I should also say that in this particular case, because upstream have fixed their output, the message override can be removed.
