### ISSUE TITLE
Deduplicate output

### ISSUE THREAD

**Issue by dominikh** [alecthomas/gometalinter#117]
When running on invalid code (that doesn't typecheck or has syntax errors), most tools will output the same error, For example:

```
$ gometalinter               
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (golint)
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (gosimple)
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (staticcheck)
```

This will cause editors to display multiple errors for a line of code. It would be great if gometalinter could coalesce these errors into a single one. Either something like this:

```
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (golint, gosimple, staticcheck)
```

or even without the list of linters at the end.

**Comment by alecthomas** [comment]
gometalinter streams messages as soon as it sees them, by design. In order to coalesce it would need to buffer them. The streaming behaviour is desirable and the downside of having a few duplicated mesages is not high enough to lose that feature.

**Comment by alecthomas** [comment]
I should say that I'm not actually opposed to supporting this via a flag, as with `--sort` (which buffers).

**Comment by dominikh** [comment]
Okay. I'll send a PR later.

**Comment by casimir** [comment]
@dominikh Did you send the PR? Can't find it.

**Comment by dominikh** [comment]
@casimir I'm sorry, no I haven't.

**Comment by casimir** [comment]
@dominikh no problem just needed it. If I can I'll send a PR soon then.
