### ISSUE TITLE
gometalinter fails for single file

### ISSUE THREAD

**Issue by sijad** [alecthomas/gometalinter#119]
when I try to run `gometalinter /paht/to/myfile.go` I get something like this:

```text
WARNING: failed to execute linter varcheck .: fork/exec /home/gopath/bin/varcheck: not a directory
WARNING: failed to execute linter gotype -e  .: fork/exec /home/gopath/bin/gotype: not a directory
WARNING: failed to execute linter unconvert .: fork/exec /home/gopath/bin/unconvert: not a directory
WARNING: failed to execute linter structcheck  .: fork/exec /home/gopath/bin/structcheck: not a directory
WARNING: failed to execute linter goconst -min-occurrences 3 .: fork/exec /home/gopath/bin/goconst: not a directory
WARNING: failed to execute linter go tool vet ./*.go: fork/exec /usr/local/bin/go: not a directory
WARNING: failed to execute linter gocyclo -over 10 .: fork/exec /home/gopath/bin/gocyclo: not a directory
WARNING: failed to execute linter dupl -plumbing -threshold 50 ./*.go: fork/exec /home/gopath/bin/dupl: not a directory
WARNING: failed to execute linter ineffassign -n .: fork/exec /home/gopath/bin/ineffassign: not a directory
WARNING: failed to execute linter go tool vet --shadow ./*.go: fork/exec /usr/local/bin/go: not a directory
WARNING: failed to execute linter golint -min_confidence 0.800000 .: fork/exec /home/gopath/bin/golint: not a directory
WARNING: failed to execute linter aligncheck .: fork/exec /home/gopath/bin/aligncheck: not a directory
WARNING: failed to execute linter deadcode .: fork/exec /home/gopath/bin/deadcode: not a directory
WARNING: failed to execute linter interfacer ./: fork/exec /home/gopath/bin/interfacer: not a directory
WARNING: failed to execute linter errcheck -abspath .: fork/exec /home/gopath/bin/errcheck: not a directory
```

**Comment by alecthomas** [comment]
gometalinter doesn't support linting individual files. You can see this in the command line help:

```
Args:
  [<path>]  Directory to lint. Defaults to ".". <path>/... will recurse.
```

**Comment by alecthomas** [comment]
That is an odd error though...

**Comment by sijad** [comment]
Most linters can be run over a single file, sometimes it can help to have this option to check only one file

**Comment by sijad** [comment]
can I PR?

**Comment by lukehoban** [comment]
Agreed that it would be great to support running over just a single file.  For integration with tools that run linters on saving a file, it would be really wasteful to always have to compute lint results for the entire package.  As @sijad mentions, most of the common linters for Go support running on a single file - would be great to be able to do the same with `gometalinter`.

**Comment by alecthomas** [comment]
I don't really mind one way or the other, so if the change is minimal I'm happy for a PR.

**Comment by alecthomas** [comment]
BTW, I think there's some exaggeration or misunderstanding here. vim-go and SublimeLinter-contrib-gometalinter both do lint on save. In the latter case, it also supports live linting and is very reponsive. So practically speaking it's not an issue. Also, I think you'll find that the slower linters perform type resolution, which is necessarily cross-package and quite slow regardless.
