### ISSUE TITLE
exclude flag usage example?

### ISSUE THREAD

**Issue by benjamin-rood** [alecthomas/gometalinter#120]
Hi, I am trying to ignore warning messages when linting generated go code, e.g. from the `github.com/pquerna/ffjson` package which spits out variables with underscores and exports methods (i.e. first letter of a method is uppercase) - but I have 400+ warnings for irrelevant things like this.

![screenshot](http://i.imgur.com/8lpkToe.png)

At the moment I am doing this:

    "gometalinter-linter":
      args: [
        "--exclude=(.)+w +(ffj)(.)+"
    (etc)

Or, alternatively, is there some way of using the --skip flag to bypass linting files that end in "_ffjson.go"?

**Comment by alecthomas** [comment]
The regex is a search not a complete match, so something like `--exclude=ffj_` should work.

**Comment by benjamin-rood** [comment]
That’s exactly what I wanted to know, sorted it out, thanks!
