### ISSUE TITLE
Support for vendorcheck?

### ISSUE THREAD

**Issue by vdemario** [alecthomas/gometalinter#122]
Filippo Valsorda [released a new tool](https://blog.cloudflare.com/building-the-simplest-go-static-analysis-tool/) called [vendorcheck](https://github.com/FiloSottile/vendorcheck) yesterday. It checks for use of packages that are in the $GOPATH but are not in the `vendor` directory.

I think it fits `gometalinter` quite nicely. Although I'm not familiar with the source code, I'd like to try to make a PR introducing support for it. Is there an interest in doing that?

**Comment by alecthomas** [comment]
It doesn't look like it reports filenames or line numbers, which gometalinter requires.

**Comment by alecthomas** [comment]
Nice tool though, very useful.
