### ISSUE TITLE
Complex "and", "or" Codes Bug  

### ISSUE THREAD

**Issue by cemkiy** [alecthomas/gometalinter#123]
![selection_005](https://cloud.githubusercontent.com/assets/3001500/14977848/617cca66-1120-11e6-940c-029c2e0d1200.png)

This code part is give me an error:
"suspect or: orderStatusBeforeUpdate != models.OrderStatusTypeDelivered || orderStatusBeforeUpdate != models.OrderStatusTypeNoShow (vet)at line 179 col 1"

But my project is run as expected. So, It's not an error. Is there a bug in gometalinter?

**Comment by alecthomas** [comment]
Please read the [contributing guidelines](https://github.com/alecthomas/gometalinter/blob/master/CONTRIBUTING.md). This message is issued by `go vet`, so if there is a bug it is there.
