### ISSUE TITLE
--enable=testify does not work with syntastic

### ISSUE THREAD

**Issue by kmulvey** [alecthomas/gometalinter#127]
when i put the below in my .vimrc nothing happens when i open/save a .go file. If i remove "--enable=testify", it works fine in vim. Running the command outside of vim works file. Both gometalinter and syntastic are up to date and im running vim 7.4.1718.  Thanks

from command line (works):
gometalinter --enable=testify

from .vimrc (nothing happens):
let g:syntastic_go_checkers = ['gometalinter --enable=testify']

**Comment by alecthomas** [comment]
What makes you think this is an issue with gometalinter?

**Comment by zeayes** [comment]
`g:syntastic_go_checkers` can only set checkers, set checker args with
`let g:syntastic_go_gometalinter_args = '--testify'`
