### ISSUE TITLE
.gometalintrc file, or the like, for distributable config.

### ISSUE THREAD

**Issue by thedodd** [alecthomas/gometalinter#131]
Linters for other languages (pep8, flake8, pyflakes, eslint, just to name a few) have configuration files which may be committed to version control. The files can be used to cleanly integrate linters with text editors & IDEs — [atom](https://atom.io) with `.eslintrc` or `tox.ini` — and offer a more comprehensive experience.

With the way gometalinter currently takes its configuration, you are essentially left with having to use a `Makefile` or some other script for consistent invocation of the linter, and then having to duplicate that same config in you editors plugin for gometalinter. 

I would be happy to open a PR for this. Just point me in the right direction.

**Comment by alecthomas** [comment]
You can already achieve this by putting your flags in a file and invoking 'gometalinter @somefile'

**Comment by thedodd** [comment]
Nice. So ... maybe this ticket should be about adding that to the docs or the `gometalinter -help` output 😄 .

**Comment by soroushjp** [comment]
+1

It was fun discovering this dark magic at work today.
