### ISSUE TITLE
Wanted: add copyfighter

### ISSUE THREAD

**Issue by JAremko** [alecthomas/gometalinter#135]
it might be useful addition: https://github.com/jmhodges/copyfighter

**Comment by alecthomas** [comment]
Looks useful but the output format is unusable ☹️

**Comment by alecthomas** [comment]
No response within a month, we can reopen it if the filed issue is resolved.

**Comment by alecthomas** [comment]
I've created a PR to add a `-plumbing` flag. You can try it out now with something like this:

```
gometalinter --linter='copyfighter:copyfighter -plumbing {path}:PATH:LINE:COL:MESSAGE' --disable-all --enable=copyfighter .
```

**Comment by alecthomas** [comment]
I would like to add copyfighter, but there are two other issues blocking inclusion: https://github.com/jmhodges/copyfighter/issues/7 and https://github.com/jmhodges/copyfighter/issues/6
