### ISSUE TITLE
misspell and CPU usage

### ISSUE THREAD

**Issue by client9** [alecthomas/gometalinter#136]
Hi guys,

thanks for merging in client9/misspell  (which now by the way can convert US <-> UK variations).

Misspell by default uses the host-max number of CPUs for parallelization.   gometalinter also does parallelization.  So when misspell is run one might starve some other linters.

I can set how gometalinter invokes misspell to set the number of CPUs to 1 (flag `-j 1`).  Or do we not care? (which is fine too!)

regards,

n

**Comment by alecthomas** [comment]
I think `-j 1` would be good to use, agreed.
