### ISSUE TITLE
idea: show warnings only for changed lines

### ISSUE THREAD

**Issue by akavel** [alecthomas/gometalinter#137]
Not sure how this could be implemented, but it would be much fancy if gometalinter could show warnings for a commit/pull-request, but only for lines changed by this commit/pull-request. This would aid in gradual migration of a project towards "lint-cleanness", as well as to stop warnings for repeating on lines which were "force accepted/overruled" into the project in the past.

A somewhat handwavy implementation idea is to filter final gometalinter results based on parsing a .patch-formatted file/stream (e.g. stdin).

Ideally, the filtering would happen before running all the tools (to optimize/make stuff faster), but I'm not sure if that's really possible at all.

Or is there such a feature maybe already available somehow with gometalinter?

/Cheers.

**Comment by alecthomas** [comment]
This is a good idea, but not really in the scope of gometalinter. I'd be surprised if there wasn't already a tool that supported this kind of filtering.

**Comment by adamliesko** [comment]
@akavel take a look at https://github.com/bradleyfalzon/revgrep
