### ISSUE TITLE
The errcheck linter is broken

### ISSUE THREAD

**Issue by alficles** [alecthomas/gometalinter#138]
I'd leave an issue on the errorcheck linter directly, but it doesn't have them enabled. But two of the libraries it depends on no longer exist:

    package golang.org/x/tools/go/types: no buildable Go source files in C:\Development\go\src\golang.org\x\tools\go\types
    package honnef.co/go/importer: code in directory C:\Development\go\src\honnef.co\go\importer expects import "this-package-has-been-removed/consider-using-go-loader-instead"

I'm not sure if types just moved or what, but loader doesn't appear to be a drop in replacement for importer. Of course, I can't tell because I can't see the importer history because the author removed it.

It might be worth vendoring the dependencies in the linters you support.

**Comment by alficles** [comment]
Aha, looks like it might already be fixed in the upstream: https://github.com/kisielk/errcheck/commit/f8d8bb57449c28f30f38d8f0439865765403bc31

**Comment by alecthomas** [comment]
Go native vendoring doesn't support installing binaries from the vendor tree, so any vendoring solution would be non-trivial.
