### ISSUE TITLE
Ignore a file

### ISSUE THREAD

**Issue by Allendar** [alecthomas/gometalinter#139]
I'm having a big constants file that I would like to ignore `golint` to complain about missing comments for literally every _enum_-style variation of my constants.

Is there any way to achieve this either by the CLI-command or by putting some kind of comment in the top of the specific file to let `golint`/`gometalinter` ignore it?

Thanks in advance!

**Comment by alecthomas** [comment]
Unfortunately there's no real way to do that reliably as some linters are just passed a directory.

**Comment by JackTiger** [comment]
Is there any method to ignore a file? @alecthomas

**Comment by alecthomas** [comment]
No, nothing has changed in this regard.

**Comment by alecthomas** [comment]
Sorry, I should say..."sort of". You can put a `// nolint` comment before your `package` directive and gometalinter will suppress all warnings.

**Comment by dnephin** [comment]
You can also use the `--exclude <path>` flag or `"Exclude":  [<path>]` in the config to ignore files or file patterns.

**Comment by luhexcp** [comment]
吗的
