### ISSUE TITLE
Gometalinter doesn't work with vendoring nicely anymore

### ISSUE THREAD

**Issue by bobrik** [alecthomas/gometalinter#141]
It looks like ea0aeb74f1183206c3d6db09adbb83636045405b broke it. My tests were all green yesterday and now they are all red because of vendored deps (looking at you, aws).

The following did the trick for me (in `gometalinter` dir):

```
$ git checkout 56537ccf6eff57ec82d8767f3e3a376956de3c69
$ go install ./...
```

Here's how it looks when it fails: https://travis-ci.org/cloudflare/complainer/jobs/142682599

**Comment by bobrik** [comment]
@alecthomas, not fixed yet: https://travis-ci.org/cloudflare/complainer/jobs/142682600

`errcheck` and others work with `.`, but not with `./...`, it seems.

**Comment by bobrik** [comment]
`golint` also complains a lot on 1.6: https://travis-ci.org/cloudflare/complainer/jobs/142682599

**Comment by alecthomas** [comment]
errcheck works for me, and looking at your CI it seems to be working for you...unless I'm missing something.

The following is using `./...` and errcheck outputs correctly?

```
$ GO15VENDOREXPERIMENT=1 gometalinter --dupl-threshold 150 --cyclo-over 12 --deadline 120s ./...
/home/travis/gopath/src/github.com/cloudflare/complainer/vendor/github.com/aws/aws-sdk-go/aws/awsutil/prettify.go:32:19:warning: error return value not checked (buf.WriteString("<buffer>")) (errcheck)
```

**Comment by bobrik** [comment]
https://travis-ci.org/cloudflare/complainer/jobs/142682600 shows tons of `errcheck` failures in `vendor`.


* `./...` NOT OK

```
bobrik@whatever: ~/projects/complainer/src/github.com/cloudflare/complainer on opt-in-defaults
$ GO_VENDOR=1 GO15VENDOREXPERIMENT=1 errcheck -abspath ./... | wc -l
     123
```

* `.` OK

```
bobrik@whatever: ~/projects/complainer/src/github.com/cloudflare/complainer on opt-in-defaults
$ GO_VENDOR=1 GO15VENDOREXPERIMENT=1 errcheck -abspath . | wc -l
       0
```

**Comment by alecthomas** [comment]
Okay, so to clarify, errcheck does "work" but it is no longer excluding vendor directories. That was not clear at all from your comment. Someone else has reported this as #143, so I'll update that when it's fixed.
