### ISSUE TITLE
golint & gosimple: no such file or directory

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#142]
Very recently (after an update), gometalinter fail to run:
```
gometalinter -E gofmt -D gotype -D vetshadow -D dupl -D goconst -D interfacer --tests --deadline=10m ./...
WARNING: failed to execute linter golint -min_confidence 0.800000 .: chdir ./...: no such file or directory
WARNING: failed to execute linter gosimple .: chdir ./...: no such file or directory
```

I think it is related to https://github.com/alecthomas/gometalinter/commit/dcc27da2ed95dee794fa7d979d8e3b9b842bbb41 or https://github.com/alecthomas/gometalinter/commit/ea0aeb74f1183206c3d6db09adbb83636045405b

Currently, my builds on Travis are failing :(

**Comment by alecthomas** [comment]
Should be working now, give it a go.

**Comment by pierrre** [comment]
Yes, it works!
Thank you :)

(sorry for the duplicate)
