### ISSUE TITLE
Specify list of linters to run

### ISSUE THREAD

**Issue by fgblomqvist** [alecthomas/gometalinter#145]
The suggested approach in the docs for running specific linters is to disable all linters and then enable the ones you want, one by one. Wouldn't be a lot more logical to enable the user to specify a list of the linters it wants to run?

Something like this:
`--linters=gofmt,golint,vet,lll`

Right now I am forced to instead do this:
`--disable-all --enable=gofmt --enable=golint --enable=vet --enable=lll`

Or maybe at least allow us to specify a list to `--enable`?

**Comment by alecthomas** [comment]
No it wouldn't be more logical, given that the default behaviour is to run them all. Providing a comma separated list to `--enable` seems like it could be useful, but passing `-E<linter>` isn't really that onerous.
