### ISSUE TITLE
--skip doesn't work with golint

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#147]
Hello,

I use this command:
`gometalinter -E gofmt -D gotype -D vetshadow -D dupl -D goconst -D interfacer --tests -j 1 --deadline=10m --skip=consumer ./...`
But it display messages for the `consumer` directory, only for golint.

If I remove skip, I have messages for the `consumer` directory (golint, vet, gocyclo, etc.)

**Comment by alecthomas** [comment]
That is because of change ea0aeb74f1183206c3d6db09adbb83636045405b (and some subsequent ones). For linters that natively support path expansion, they are called directly. This speeds up linting significantly, but results in skipped paths being processed. I will need to do a second pass over the output messages, excluding skipped paths.

**Comment by pierrre** [comment]
Or disable "path expansion" if there is a directory to skip? (just an idea)

**Comment by alecthomas** [comment]
That would work, but some of the linters are so slow when run per directory that it's ridiculous. errcheck, varcheck, etc. take minutes on bigger repositories. This speeds them up to acceptable levels.

**Comment by pierrre** [comment]
OK I understand.

Do you plan a fix?
> I will need to do a second pass over the output messages, excluding skipped paths.

Thank you.

**Comment by pierrre** [comment]
Hello again!
This issue is annoying to me, because I want to exclude my `vendor` directory from gometalinter.

**Comment by pierrre** [comment]
Ooops, I just saw `--vendor` :P

**Comment by freman** [comment]
Well, this explains my issue too when running as part of our CI suite

```
root@f3df4b6acaa2:~/querylib/.go/src/ourgitlab/golib/querylib# gometalinter --deadline=180s --disable-all --enable=misspell --skip=.go ./...
.go/src/gopkg.in/DATA-DOG/go-sqlmock.v1/argument_test.go:35:35:warning: "expections" is a misspelling of "exceptions" (misspell)
.go/src/gopkg.in/DATA-DOG/go-sqlmock.v1/argument_test.go:56:35:warning: "expections" is a misspelling of "exceptions" (misspell)
```

**Comment by alecthomas** [comment]
This should be working now.

**Comment by lylex** [comment]
@alecthomas Is this working on gometalinter.v1? If my understanding is correct, that is the recommended one.
