### ISSUE TITLE
'slice bounds out of range' error when running go get

### ISSUE THREAD

**Issue by cfatt10** [alecthomas/gometalinter#148]
I ran "go get -u github.com/alecthomas/gometalinter" and it's getting the aforementioned error. Here's the whole output:

panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x539d00, 0xc820010090)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
main.vendoredImportPath(0xc820402400, 0xc8203fa2a1, 0x1e, 0x0, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:460 +0x67b
main.loadImport(0xc8203fa2a1, 0x1e, 0xc82016afc0, 0x64, 0xc820402400, 0xc82018bb90, 0xc8203a5b60, 0x1, 0x1, 0x1, ...)
	/usr/local/go/src/cmd/go/pkg.go:336 +0xe52
main.(*Package).load(0xc820402400, 0xc82018bb90, 0xc820457880, 0x0, 0x0, 0x4)
	/usr/local/go/src/cmd/go/pkg.go:947 +0x4397
main.loadImport(0xc820168a61, 0x1e, 0xc820019480, 0x77, 0xc820170c00, 0xc82018bb90, 0xc820159590, 0x1, 0x1, 0x1, ...)
	/usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.(*Package).load(0xc820170c00, 0xc82018bb90, 0xc820167180, 0x0, 0x0, 0xc)
	/usr/local/go/src/cmd/go/pkg.go:947 +0x4397
main.loadImport(0x7fff5fbff6b2, 0x22, 0xc82000e0c4, 0xd, 0x0, 0xc82018bb90, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.loadPackage(0x7fff5fbff6b2, 0x22, 0xc82018bb90, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:1633 +0x13d8
main.download.func1(0x7fff5fbff6b2, 0x22, 0x0, 0xc82014dee0)
	/usr/local/go/src/cmd/go/get.go:183 +0x43
main.download(0x7fff5fbff6b2, 0x22, 0x0, 0xc82018bb90, 0x0)
	/usr/local/go/src/cmd/go/get.go:188 +0xdc
main.runGet(0x883fe0, 0xc82000a330, 0x1, 0x1)
	/usr/local/go/src/cmd/go/get.go:107 +0x1de
main.main()
	/usr/local/go/src/cmd/go/main.go:181 +0x783

**Comment by alecthomas** [comment]
That's not really a problem with gometalinter, it's a problem with your Go setup (somehow). I've never encountered that issue, but I'd perhaps do some googling or ask on the mailing list.
