### ISSUE TITLE
The disable flag behaves differently from the documentation

### ISSUE THREAD

**Issue by Dynom** [alecthomas/gometalinter#151]
Hi,

In the documentation is reads:

```
-D, --disable=LINTER      List of linters to disable (testify,test).
```

This suggests to me that the following should work:

```
gometalinter -D gotype,dupl,varcheck,aligncheck,structcheck .
```

However:

```
$ gometalinter -D dupl,gocyclo --vendor -t cupid/; echo $?
cupid/comparer.go:46::warning: cyclomatic complexity 11 of function CompareCUPIDsWithScoreThreshold() is high (> 10) (gocyclo)
cupid/comparer_test.go:59::warning: duplicate of comparer_test.go:144-176 (dupl)
cupid/comparer_test.go:144::warning: duplicate of comparer_test.go:59-91 (dupl)
1
```

vs.

```
$ gometalinter -D dupl -D gocyclo --vendor -t cupid/; echo $?
0
```

The same goes for the `--disable` flag.

**Comment by alecthomas** [comment]
I believe you are using an old version of Kingpin (the flag library). It now says:

```
  -D, --disable=LINTER ...  List of linters to disable (testify,test,gofmt,goimports,lll,misspell).
```

Basically, it's difficult to succinctly describe how this should be used. If you have suggestions I'd be interested in hearing them.

**Comment by Dynom** [comment]
Hi @alecthomas,

I am actually referring to the documentation in the [README.md](https://github.com/alecthomas/gometalinter/blob/master/README.md) (nearly at the bottom).

I'd probably document it like:
```
-D, --disable=LINTER Specify a linter to disable (e.g.: testify, test, etc.), the flag can be repeated
```

I think that the words `list of` and the line between parenthesis (comma separated, without spaces, like you would do it in a linux shell if you wouldn't use quotes) threw me off.

**Comment by alecthomas** [comment]
I'm going to close this, as I think the default flag descriptions are okay.
