### ISSUE TITLE
--help flag runs the linters

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#152]
If I run `gometalinter --help`, it displays the help, then run the linters.
It should not run the linters.

**Comment by alecthomas** [comment]
That is actually a bug in Kingpin (fixed in alecthomas/kingpin@e5900212cbf65b181d3d8e08308ef06a01d117cf). Run `go get -u` on gometalinter again and it should fix it.

**Comment by pierrre** [comment]
It works! Thank you :)
