### ISSUE TITLE
Emit warning JSON for "deadline exceeded"

### ISSUE THREAD

**Issue by jspiro** [alecthomas/gometalinter#155]
It would be good to know in e.g. Atom that linters are not completing otherwise the lack of warnings could be a false-positive on e.g. tests passing.

**Comment by alecthomas** [comment]
How would you expect that to work exactly? ie. what format would the JSON be?

**Comment by jspiro** [comment]
It could emit it like any other error, the message would be that a particular linter took too long. Anything would be sufficient! (Every time I hit save my 4 CPU cores warm up for a few seconds, lots of linting going on, sometimes they time out and I don't know.)

**Comment by alecthomas** [comment]
Right, but what file/col/line does it report against?

**Comment by client9** [comment]
I understand and like the intent, but the issue appears to be in Atom's plugin and not one of gometalinter.

If a timeout happens (or other failure happens), gometalinter returns >= 2 (as per README.md).   Atom can or should handling this case.  (and 0=run ok, no lint problems, 1 = ran ok, lint problems, 2= failed, no lints, 4=failed, with lints ... i.e partial results).

Even gometalinter did emit a JSON error, I don't think Atom would understand it automatically anyways (or is there a special format for it?).  

Or did I miss something?

regards,

n

**Comment by alecthomas** [comment]
Yes, that's a very good point. The atom linter should definitely be checking the exit status!
