### ISSUE TITLE
test linter is outputting non-existant filenames

### ISSUE THREAD

**Issue by jspiro** [alecthomas/gometalinter#156]
`{"linter":"test","severity":"error","path":"assertions.go","line":225,"col":0,"message":"\r                        \r\tError Trace:\tsimulator_test.go:55"}`-- the correct path should be simulator_test.go. Not sure if this is in-scope of gometalinter or not.

**Comment by jspiro** [comment]
Also, I'm not sure what the testify linter is supposed to do, but it doesn't seem to do anything so far as I can tell.

**Comment by alecthomas** [comment]
I'm guessing this is due to a change in test output, though I'm considering just removing these.

**Comment by jspiro** [comment]
I'd hope `test` stays in -- I don't know of another package for Atom to show whether tests fail :-/ (Which is really surprising.)

**Comment by alecthomas** [comment]
👍
