### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by remexre** [alecthomas/gometalinter#157]
The src symlink in the vendor directory fails on Windows. The command `gometalinter --install` fails because of this. Placing the vendored sources inside a folder named src fixes the issue.

**Comment by alecthomas** [comment]
Hmm, this is a bit of a problem and I did wonder how it would on Windows. The underlying issue is that the vendoring tools (eg. glide) always assume a "vendor" directly with the sources directly under it, whereas GOPATH assumes a "src" directory. So I can either have vendoring tools or GOPATH, but not both. I'm not sure what to do about that.

**Comment by abe545** [comment]
I was able to get it working by deleting the src file, and using mklink to create a symlink:
```
mklink /D src .
```
I am a go newbie, so I don't know if there is a way to create this symlink in windows during the install.

**Comment by remexre** [comment]
Not without go generate or something; it would be possible to do "go
generate" plus a build tag, but that's hackish

**Comment by alecthomas** [comment]
I could probably do that manually before a `--install`.

**Comment by remexre** [comment]
Just a heads up, `mklink` does require Admin privileges...

**Comment by abe545** [comment]
@remexre - yes, and it doesn't work in powershell :/

**Comment by remexre** [comment]
Wait, if it's a shell builtin, would that prevent it from working if e.g. [the gometalinter atom plugin](https://github.com/joefitzgerald/gometalinter-linter) was running `gometalinter --install` rather than cmd or powershell?

**Comment by remexre** [comment]
Maybe change `gometalinter --install` to do (in pseudo-shell):

```sh
cd $GOPATH/github.com/alecthomas/gometalinter
if [[ -e gopath ]]; then
    rm -rf gopath
fi
mkdir gopath
cp -r vendor gopath/src
GOPATH="$GOPATH/github.com/alecthomas/gometalinter/gopath" go get <all the things>
```

and just add `gopath/` to `.gitignore`?

**Comment by alecthomas** [comment]
I have a possible solution: I'll move all the sources into a `vendor/src` directory, then symlink those paths back into vendor. This way the vendoring tool should still work though a little bit clunky, but `--install` will definitely work.

**Comment by alecthomas** [comment]
Okay, let me know if that worked.
