### ISSUE TITLE
GC disable problem

### ISSUE THREAD

**Issue by pocke** [alecthomas/gometalinter#164]
In a huge repository, gometalinter freezes by insufficient memory.
Because gometalinter disables GC of child linters for performance.

For example, I analyse  https://github.com/drone/drone , gometalinter uses about 5GB RAM. 
So, I've tried enabling GC. Then it uses about less than 2GB RAM. However it's slower than disabling GC.

Benchmarks
----------

I've try the benchmark on https://github.com/alecthomas/kingpin and https://github.com/drone/drone .
3 times average.

### command

```
$ time gometalinter --deadline 1200s ./... > /dev/null
```

1.  Disable GC with all linters
  - current master
  - 0ded9f448429beb2db922cc70bca48e21c5fe353
2. Disable GC with fast linters only
  - https://gist.github.com/pocke/f20727b369175959b2b4c9d44502564d
3. Not Disable GC

|                                 | kingpin | drone/drone |
|---------------------------------|---------|-------------|
| 1. Disable GC with all linters  | 3.65s   | 26.66s      |
| 2. Disable GC with fast linters | 6.04s   | 36.26s      |
| 3. Not Disable GC               | 5.91s   | 39.72       |

1 is faster than others. And the difference between  2 and 3 is small.
So, I think 2 implementation is not cool :cry: 

Proposal 
------------

So, I propose a `--enable-gc` option.
In a huge repository, we use gometalinter with `--enable-gc` option. So it enables GC, we can avoid PC freeze.
In a small repository, we can use gometalinter with current speed.

(See. https://github.com/pocke/gometalinter/commit/e3888576b2bf5506c16fea3ae2d20e1d7bf22bcf#commitcomment-18639847 )

**Comment by alecthomas** [comment]
That seems very reasonable to me. Done.

**Comment by pocke** [comment]
Thanks !!
