### ISSUE TITLE
Should invoke linters once with multiple paths if the linter supports it

### ISSUE THREAD

**Issue by marienz** [alecthomas/gometalinter#167]
gometalinter passes the `...` wildcard through to linters that support it, but seems to always pass only one path per linter invocation.

When operating on many packages, this makes it a lot slower than it has to be. An interesting case where this crops up is enabling the `GO15VENDOREXPERIMENT` support (which skips `/vendor/` directories but also defeats the previously mentioned optimization of passing through `...` wildcards) and passing one or more wildcard paths. On a repository I'm working on that currently contains 172 total packages (according to `go list ./...`) of which only 15 are not below a `/vendor/` directory, `gometalinter ./...` is actually faster without `GO15VENDOREXPERIMENT` despite having to lint and spit out about 8000 extra lint warnings for the vendored code. When passing 4 wildcard paths that expand to 14 packages (none of them vendored), it's about 3 times faster without `GO15VENDOREXPERIMENT`.

Although it would help if the `GO15VENDOREXPERIMENT` detected wildcard paths without vendored packages and passed through the wildcard for those, I suspect the better fix is to expand all paths up front and run child linters that support multiple paths/packages once. That should speed up more cases than making the ellipsis handling smarter. The main downsides are having to keep track of which linters can be invoked this way, and some additional complexity in gometalinter.

A cursory check shows all linters except golint that support ellipsis also support multiple paths. As golint is fairly fast anyway, it might make sense to replace the ellipsis support with this instead of having both. I doubt any of the child linters are faster than gometalinter at expanding wildcards, so doing that for them probably will not hurt performance if they still get all paths in one shot.

I haven't looked at how difficult this would be to implement, but I'm happy to do that if this sounds like something you'd merge.

**Comment by alecthomas** [comment]
That seems fairly reasonable to me, I'd accept a PR that did this. Making checks against vendored repos fast would be very nice.
