### ISSUE TITLE
dingo-hunter - Static analyser for finding Deadlocks in Go

### ISSUE THREAD

**Issue by matrixik** [alecthomas/gometalinter#169]
https://github.com/nickng/dingo-hunter

> This is a static analyser to model concurrency and find deadlocks in Go code. We use a system known in the literature as Session Types to look for potential communication mismatches to preempt potential deadlocks.

Created by @nickng

**Comment by alecthomas** [comment]
Looks very useful, but the installation is a bit too complex to be included in gometalinter itself.
