### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by ggeorgiev** [alecthomas/gometalinter#176]
errcheck and probably other linters support -tags. It will be nice if gometalinter accepts and propagate specified tags to it to the linters that support them.

**Comment by alecthomas** [comment]
I try to limit "global" features to those that are consistent across all linters, because it's confusing if they don't behave consistently. It doesn't seem like tags flags are a super common feature (though it would be good if it were :\).

**Comment by ggeorgiev** [comment]
this seems counterintuitive and in fact, it is not even true - you have a bunch of flags that are specific to one or another linter.

If this is what you prefer a pass through protocol will be nice then. The way it is now - the only option I have is to maintain my own fork - this does not seem ideal.

**Comment by alecthomas** [comment]
> this seems counterintuitive and in fact, it is not even true - you have a bunch of flags that are specific to one or another linter.

Linter-specific flags are not the same thing; they change the behaviour of a single linter, so the behaviour is very clear. I was referring to "global" features, and the only current exception is the `--test` flag, which is why I said "try".

> If this is what you prefer a pass through protocol will be nice then.

There is an existing way to pass through flags; by overriding the linter (also see #178):

```
gometalinter --linter='errcheck:errcheck -tags foo -disabletests:PATH:LINE:COL:MESSAGE {path}' 
```

**Comment by client9** [comment]
is this for adding build tags? https://golang.org/pkg/go/build/

**Comment by ggeorgiev** [comment]
yes
