### ISSUE TITLE
Pass argument to specific linter ?

### ISSUE THREAD

**Issue by tbruyelle** [alecthomas/gometalinter#178]
Sorry I didn't find anything on that subject in the README or in the issues.

If I want to pass `--disabletests` to the `errcheck` linter, how do I do that with `gometalinter` ?

**Comment by alecthomas** [comment]
No, this is not possible.

**Comment by tbruyelle** [comment]
Is it something you may add or merge from a PR ?

**Comment by alecthomas** [comment]
Sorry, I should say that there is no *convenient* way to do this. You can achieve it with something like this:

```
gometalinter --linter='errcheck:errcheck -abspath -disabletests:PATH:LINE:COL:MESSAGE {path}' .
```

I think this is generally sufficient.

**Comment by tbruyelle** [comment]
This fits my need thanks. 

To be more convenient, it would be nice to be able to remove the `:PATH:LINE:COL:MESSAGE` part of the command, which in my understanding  helps to parse the tool's ouput. It may not be exposed to the user. Am I right ?

**Comment by tbruyelle** [comment]
Would you accept such feature ?

**Comment by alecthomas** [comment]
Sure, though you can't just default to that, as some linters have custom patterns.
