### ISSUE TITLE
update vendored linters

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#183]
I just saw this tweet: https://twitter.com/dominikhonnef/status/794560951311810560
```
Remember to regularly update gosimple / staticcheck, New rules being added all the time. e.g.: correct usage of http headers and b.N #golang
```

As you can see, the upstream repository is updated very regularly:
https://github.com/dominikh/go-staticcheck

And the latest commit in your repository was 3 months ago:
https://github.com/alecthomas/gometalinter/tree/master/vendor/src/honnef.co/go/staticcheck

Do you have any plan to update vendored linters ? Or do it more frequently ?

I know that the `--no-vendored-linters` flag exists, but I prefer to avoid it:
- I build very frequently on Travis, and it's faster to build vendored linters
- If a linter CLI interface changes, it could break the gometalinter integration

**Comment by alecthomas** [comment]
I don't have time to track all the linters, so I rely on users wanting to see updates for features they care about, just like this one. Feel free to send a PR, or I will get to it soon.

**Comment by alecthomas** [comment]
All linters were just updated in #184.

**Comment by pierrre** [comment]
thank you !
