### ISSUE TITLE
Move dupl to disabled by default

### ISSUE THREAD

**Issue by GarethLewin** [alecthomas/gometalinter#185]
This is an opinionated issue, and totally your call. I find `dupl` is useless as it is full of false positives. A good example would be to run dupl on gometalinter's code itself.

My request is to move dupl to disabled by default, as I just always disable it.

**Comment by alecthomas** [comment]
I'd be okay with that.

**Comment by alecthomas** [comment]
Note that the configuration file format has changed slightly in 2254d21.
