### ISSUE TITLE
Unable to load config from file and run on specific directory

### ISSUE THREAD

**Issue by fgblomqvist** [alecthomas/gometalinter#186]
Running `gometalinter @.gometalinter mydir` runs the linters on all directories and files.
If I take all the commands in .gometalinter and create one big command, it works fine though (only runs the linters on the specific directory).

I'm guessing this is a bug?

**Comment by alecthomas** [comment]
Yes, this is a [bug in Kingpin](https://github.com/alecthomas/kingpin/issues/148). I haven't had the chance to fix it yet.
