### ISSUE TITLE
Always include column in output

### ISSUE THREAD

**Issue by fgblomqvist** [alecthomas/gometalinter#187]
Right now, for linters such as goimports and lll, gometalinter does not provide a column.
For example, this is the output:
`mypackage/myfile.go:1::warning: file is not goimported (goimports)`

To prevent IDE formatting from breaking, it would be great if a column of 1 could be passed as a default. I noticed this is already done for line (it's 1 if nothing else is specified).

What do you think?

**Comment by alecthomas** [comment]
This was a deliberate choice to differentate "no column information" from having a column. If a default column of 1 is provided, many editors will highlight the first word on a line, which is confusing. The line default of 1 is a slightly different case, in that those linters were introduced after gometalinter's output was already defined.

What IDE is this breaking? All editors I'm aware of cope with this well.

**Comment by fgblomqvist** [comment]
Hmm I see. To me, some of them having a line of 1 implies that it doesn't concern a specific line. In the same way, I think that a location if 1:1 would imply that it concerns the entire file.

Nonetheless, I am using IntelliJ IDEA with gometalinter as an external tool, then an output filter that turns the file references to links. If the column is empty, it doesn't turn it into a link. While  I could change it so that it always just ignores the column part, I would obviously loose functionality.
