### ISSUE TITLE
Support configuration file

### ISSUE THREAD

**Issue by zmb3** [alecthomas/gometalinter#189]
I like to use a variety of different editors, and I occasionally run `gometalinter` from the command line.  It would be great if the tool behaved the same way (with my preferred settings for which linters to run, etc) no matter where it was invoked.

To get this behavior, I have to configure each editor to pass the same flags.  It would be very convenient if `gometalinter` would check for the presence of a file in my `$HOME` directory and read configuration settings from there.  Command line arguments could still take precedence over the values specified in the file.

**Comment by alecthomas** [comment]
Okay, I've added support for a JSON configuration file. It would be great if you could test this out.

**Comment by zmb3** [comment]
Seems to work just fine.  Thanks!

**Comment by alecthomas** [comment]
Note that the configuration file has changed slightly in 2254d21.
