### ISSUE TITLE
gometalinter not resolving any libraries, including std

### ISSUE THREAD

**Issue by damienstanton** [alecthomas/gometalinter#191]
In brief, `$GOPATH/bin/gometalinter .` in a given project is failing to find the correct import path.
Details were reported at [this vscode-go issue](https://github.com/Microsoft/vscode-go/issues/635).

**Comment by alecthomas** [comment]
This typically means that gometalinter and its tools were installed with an older version of Go that has subsequently been removed in an upgrade. You will need to reinstall gometalinter and the linters.

**Comment by damienstanton** [comment]
You were correct! Re-installing all known linters with `gometalinter --install` did the trick.
