### ISSUE TITLE
Add -h alias for --help

### ISSUE THREAD

**Issue by willfaught** [alecthomas/gometalinter#195]
Can this be added? Most Go programs seem to have at least -h. It's the first thing I always try because it's shorter. Kingpin makes this easy to add. (I realize this is the nit-pickiest thing in the world. Sorry!)

**Comment by alecthomas** [comment]
You can add this yourself with: `kingpin.HelpFlag.Short('h')`

**Comment by willfaught** [comment]
I assume this means you're open to merging this kind of change?

**Comment by alecthomas** [comment]
No, it [exists already](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#pkg-variables) for exactly this purpose actually...someone else had the same request.

**Comment by willfaught** [comment]
Are you suggesting I fork this locally and run my own build with the change? I'm confused what I can do with a line of Go and an installed binary that I go-getted. I was proposing a change that would be reflected on everyone's future installations of gometalinter.

**Comment by alecthomas** [comment]
Ah, no I would not want that to be the default as there's no way to override short flags once they're added.

**Comment by alecthomas** [comment]
Sorry... I completely brain farted. I thought this issue was on the Kingpin repo!

For gometalinter, yeah I'd be fine with adding `-h`. Sorry about the confusion.

**Comment by willfaught** [comment]
Woops, sorry, didn't see that you left it open. Reopened.

**Comment by alecthomas** [comment]
PR?

**Comment by willfaught** [comment]
Sorry, will do shortly.

**Comment by willfaught** [comment]
It appears gometalinter uses gopkg.in/alecthomas/kingpin.v3-unstable, for which `kingpin.HelpFlag.Short('h')` is invalid. I don't see any way to add a short variation for the help flag using that package. It seems like the help flag is baked into that kingpin package somehow? Not sure how to proceed.

**Comment by willfaught** [comment]
Ping
