### ISSUE TITLE
Upgrade vendored errcheck

### ISSUE THREAD

**Issue by powerman** [alecthomas/gometalinter#198]
Please upgrade it, there are some nice changes, including ignoring errors from stdlib functions which is known to never return error (like (*bytes.Buffer).WriteString).

**Comment by GarethLewin** [comment]
Sorry to be rude, but last time I wanted upgraded vendored tools in gometalinter I just submitted a PR

**Comment by powerman** [comment]
That's not rude, no problem with this at all. I just wanna know is there any reasons to not upgrade.

**Comment by alecthomas** [comment]
Brilliant, thanks for the PR, and thanks @GarethLewin :)
