### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by GarethLewin** [alecthomas/gometalinter#199]
Hi Alec.

Since https://github.com/alecthomas/gometalinter/commit/91662f373ab64c8d64942f4926ffbf3456cf1663 we have no new tag, so gopkg.in is on old tools, could we get a new tag please?

**Comment by GarethLewin** [comment]
I mean new release

**Comment by alecthomas** [comment]
I'm still figuring out some issues with the new config file, but once that's settled I will push a new tag.

**Comment by alecthomas** [comment]
gopkg.in/alecthomas/gometalinter.v1
