### ISSUE TITLE
Installation/build flags?

### ISSUE THREAD

**Issue by Ambrevar** [alecthomas/gometalinter#202]
I'd like to install all the linters without their debugging symbols (disk space nitpicking).
With the regular `go` tool I would call

	go get|build|install -ldflags '-s -w' ...

Any way to do that with gometalinters?

**Comment by alecthomas** [comment]
No, there is no way to do that via gometalinter. You could do something like `GOPATH=$GOPATH/src/github.com/alecthomas/gometalinter/vendor go install <linter> ...`
