### ISSUE TITLE
Please add flag to download (but not install) linters

### ISSUE THREAD

**Issue by AlekSi** [alecthomas/gometalinter#203]
Basically, `gometalinter --install --download-only` should add `-d` to `go get`. Something like:
```
$ gometalinter --help
…
  -i, --install             Attempt to install all known linters.
  -u, --update              Pass -u to go tool when installing.
  -f, --force               Pass -f to go tool when installing.
      --download-only       Pass -d to go tool when installing.
…
```

We (https://github.com/go-reform/reform/pull/82) need this to download dependencies to cache directory $GOPATH/src, then install it with different Go versions to own copies of $GOPATH/{bin,pkg}.

We can make a pull request if you are OK with it.

**Comment by alecthomas** [comment]
That seems pretty weird, but sure.
