### ISSUE TITLE
Enabling GC and Setting Deadline in the config causes strange warnings

### ISSUE THREAD

**Issue by yuriy-yarosh** [alecthomas/gometalinter#210]
Config
```json
{
    "DisableAll": true,
    "Enable": [
        "gas",
        "gocyclo",
        "gofmt",
        "ineffassign",
        "lll",
        "staticcheck",
        "deadcode",
        "goconst",
        "golint",
        "gosimple",
        "aligncheck",
        "dupl",
        "goimports",
        "gotype",
        "misspell",
        "unconvert",
        "vet",
        "vetshadow",
        "errcheck",
        "interfacer"
    ],

    "Concurrency": 16,
    "Cyclo": 10,
    "Deadline": 10000000000,
    "LineLength": 120,
    "MinConfidence": 0.8,
    "MinOccurrences": 3,
    "MinConstLength": 3,
    "DuplThreshold": 50,
    "Sort": ["severity"],

    "EnableGC": true,
    "Aggregate": true
}
```

And if `Deadline` is less than `10000000000` I'm getting strange warnings like this
```
WARNING: failed to kill dupl: os: process already finished
WARNING: failed to kill gas: os: process already finished
WARNING: failed to kill dupl: os: process already finished
WARNING: failed to kill goconst: os: process already finished
WARNING: failed to kill gocyclo: os: process already finished
WARNING: deadline exceeded by linter lll on api/util (try increasing --deadline)
WARNING: deadline exceeded by linter gocyclo on api (try increasing --deadline)
WARNING: deadline exceeded by linter dupl on api (try increasing --deadline)
WARNING: deadline exceeded by linter ineffassign on . (try increasing --deadline)
WARNING: deadline exceeded by linter vetshadow on . (try increasing --deadline)
WARNING: deadline exceeded by linter vet on . (try increasing --deadline)
...
```

ofc linters are getting killed prematurely for unknown reason, maybe it's caused by improper `time.Duration` deserialization.

**Comment by GarethLewin** [comment]
10000000000ns is 10seconds, is it possible that your linting is taking more than 10 seconds?

**Comment by yuriy-yarosh** [comment]
@GarethLewin Ohh... it's nanoseconds, great. It's a bit inconvenient.

> is it possible that your linting is taking more than 10 seconds?
Nope, it takes 7s. And even with 10s deadline value and enabled GC it still fires few Warnings, but it's cool when I'm disabling GC ...

Is there any way to specify "7s" as a string, and not in nanoseconds ?

**Comment by GarethLewin** [comment]
`time.Duration` is actually an int64 (see https://github.com/golang/go/blob/master/src/time/time.go#L441) of nanoseconds. And the code in gometalinter doesn't specifically call https://golang.org/pkg/time/#ParseDuration so yes, it's in NanoSeconds.

Not sure about what other warnings you get, I tend to set deadlines of much higher than 10s when I lint medium sized codebases.

**Comment by alecthomas** [comment]
@garethlewin is correct.

**Comment by alecthomas** [comment]
The use of nanoseconds is due to the JSON unmarshaller, so there's not much that can be done about it unfortunately.
