### ISSUE TITLE
what does 'Subprocess launching with variable.,HIGH,HIGH (gas)' mean ?

### ISSUE THREAD

**Issue by bruceauyeung** [alecthomas/gometalinter#211]
i use vscode-go with gometalinter. there are some errors look like 'Subprocess launching with variable.,HIGH,HIGH (gas)' in the problem list. what does it mean ?
i have binged a lot but found nothing. please help me out.

**Comment by GarethLewin** [comment]
This is not a vscode-go nor a gometalinter question, your code is triggering an error from the linter called `gas` that you are using a variable to launch a subprocess (https://github.com/GoASTScanner/gas/blob/master/rules/subproc.go#L33)

**Comment by alecthomas** [comment]
Thanks @garethlewin.
