### ISSUE TITLE
--config should expand "~/" home

### ISSUE THREAD

**Issue by eduncan911** [alecthomas/gometalinter#213]
Again, thank you for this excellent tool!  

I'm trying to use the new `--config` feature, to centralize my configuration across many tools (vim, Atom, VSCode).  I found out that I cannot specify "~/" and have it expand.

    $ gometalinter --config=~/.gometalinter.conf --json .
    gometalinter: error: open ~/.gometalinter.conf: no such file or directory, try --help

Quotes don't help:

    $ gometalinter --config="~/.gometalinter.conf" --json .
    gometalinter: error: open ~/.gometalinter.conf: no such file or directory, try --help

But, using a full path does:

    $ gometalinter --config=/Users/eric/.gometalinter.conf --json .
    [
      {"linter":"golint","severity":"warning","path":"example.go","line":14,"col":2,"message":"var Id should be ID"}
    ]

Would it be possible to expand the ~?

OS: MacOS

**Comment by alecthomas** [comment]
This is typically a function of your shell. For  example, zsh performs this expansion. It may be possible to make bash do this as well.

**Comment by alecthomas** [comment]
Sorry, I should have mentioned that some shells will only expand ~ for whole arguments. Try `--config ~/Users/eric/...` vs. `--config=~/Users/...`
