### ISSUE TITLE
To integrate Go's unit test report

### ISSUE THREAD

**Issue by penhauer-xiao** [alecthomas/gometalinter#215]
I recommended to integrate Go's unit test report (GoConvey: https://github.com/smartystreets/goconvey), the Go's unit test report is very important and useful.

**Comment by alecthomas** [comment]
Go test is already supported, or are you referring to something specific to goconvey?

**Comment by penhauer-xiao** [comment]
The GoConvey has native integration Go test , but it is more powerful, such as support for BDD testing framework, while a wealth of assertions. and more https://github.com/smartystreets/goconvey

**Comment by alecthomas** [comment]
Sorry, I really don't understand what you're asking for. What do you mean by "integrate"? 

Are you referring to something like `gometalinter --enable goconvey`? If so, I don't understand how that would work, as it looks like goconvey isn't a tool at all?

If you're suggesting that gometalinter use goconvey for its own tests, then no, I think that is unnecessary. The standard testing package is fine.

**Comment by penhauer-xiao** [comment]
Oh, How to enable Go test?

**Comment by alecthomas** [comment]
To enable linters refer to [this](https://github.com/alecthomas/gometalinter#supported-linters). To use a custom linter, or override the flags of an existing one, refer to the flag `--linter`.
