### ISSUE TITLE
Unknown identifier in example code

### ISSUE THREAD

**Issue by itsjamie** [alecthomas/gometalinter#218]
According to https://github.com/golang/go/issues/14933, this is due to the usage of `go tool vet`, and passing individual file names.

Local Command:
`gometalinter --disable-all --enable=vet --vendor --vendored-linters ./...`

Output:
`ExampleCreateInvalidation refers to unknown identifier: CreateInvalidation (vet)`

When running locally using `go vet ./package` I do not receive the message, however when using `go tool vet ./package/*.go` I do receive the same message.

**Comment by itsjamie** [comment]
Related: gojp/goreportcard/issues/113

**Comment by alecthomas** [comment]
I'm unable to replicate this with `gometalinter`, `go tool vet` or `go vet`, assuming you're talking about `github.com/gowww/compress`. What version of Go are you using?

```
[alec@cavern:~/.go/src/github.com/gowww/compress]gometalinter --disable-all --enable=vet --debug
DEBUG: PATH=/Users/alec/bin/cocos2d-x-3.2alpha0/tools/cocos2d-console/bin:/Users/alec/.go/bin:/Users/alec/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/alec/.cabal/bin:/Users/alec/.go/bin
DEBUG: GOPATH=/Users/alec/.go
DEBUG: GOBIN=
DEBUG: linting path .
DEBUG: linting with vet: go tool vet {path}/*.go (on .)
DEBUG: executing /usr/local/bin/go ["tool" "vet" "example_test.go" "handler.go" "handler_test.go"]
DEBUG: vet hits 0: ^(?:vet:.*?\.go:\s+(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*))|(?:(?P<path>.*?\.go):(?P<line>\d+):\s*(?P<message>.*))$
DEBUG: vet linter took 65.147807ms
DEBUG: total elapsed time 72.103174ms
[alec@cavern:~/.go/src/github.com/gowww/compress]go tool vet .
[alec@cavern:~/.go/src/github.com/gowww/compress]go tool -n vet .
/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64/vet .
[alec@cavern:~/.go/src/github.com/gowww/compress]go tool vet ./*.go
[alec@cavern:~/.go/src/github.com/gowww/compress]go tool -n vet ./*.go
/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64/vet ./example_test.go ./handler.go ./handler_test.go
[alec@cavern:~/.go/src/github.com/gowww/compress]go vet .
[alec@cavern:~/.go/src/github.com/gowww/compress]go vet -n .
/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64/vet handler.go handler_test.go
/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64/vet example_test.go
[alec@cavern:~/.go/src/github.com/gowww/compress]go vet ./*.go
[alec@cavern:~/.go/src/github.com/gowww/compress]go vet -n ./*.go
/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64/vet handler.go handler_test.go
/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64/vet example_test.go
[alec@cavern:~/.go/src/github.com/gowww/compress]go version
go version go1.7.3 darwin/amd64
```

That said, whatever issues caused me to use `go tool vet *.go` in the first place, seem like they may have been fixed in the Go toolchain.

**Comment by itsjamie** [comment]
I found out what it was actually in this case by producing an example.

https://gist.github.com/itsjamie/53d2f49643e722882845c4f50835e4fd

It would appear what was actually happening here is that go tool vet is surpressing, or not checking that an Example matches some item in the actual code?

**Comment by alecthomas** [comment]
Aaaah, very interesting.

**Comment by GoLangsam** [comment]
[Go Report Card](http://goreportcard.com/) is not only a fine and increasingly popular service, but also a proud user of Your versatile and powerful `metalinter`.

Suffering similar annoyances, [here](https://github.com/gojp/goreportcard/issues/113#issuecomment-332070468) is what I found about underlying reasons.

**Comment by dnephin** [comment]
I opened #351 for this as well

**Comment by GoLangsam** [comment]
gr8

**Comment by hiromaily** [comment]
+1
