### ISSUE TITLE
Tool: https://github.com/gordonklaus/ineffassign

### ISSUE THREAD

**Issue by dgryski** [alecthomas/gometalinter#22]
Detects ineffectual assignments

**Comment by alecthomas** [comment]
Nice idea, but unfortunately it recursively checks every directory. This is very slow for vendored source trees :(

Still, I think I'll add it but perhaps default to disabled.

**Comment by alecthomas** [comment]
I filed a ticket.

**Comment by dgryski** [comment]
Which for the record is https://github.com/gordonklaus/ineffassign/issues/2
