### ISSUE TITLE
Disable gas check G101

### ISSUE THREAD

**Issue by willfaught** [alecthomas/gometalinter#221]
With `-exclude=G101`. It's the hardcoded password check. It incorrectly flags things like `const MaxPasswordLength = 50` and `const NodeTypeToken = "token"`. They don't seem willing to change it. See https://github.com/GoASTScanner/gas/issues/108.

**Comment by alecthomas** [comment]
I think the `// #nosec` that they suggest is probably a better option. By its nature, gas is inaccurate (which is also why it is at warning level only), so I suspect most people run it, then explicitly disable particular lines. At least, that is how I use it.
