### ISSUE TITLE
How to (force) install linter-tools from vendor?

### ISSUE THREAD

**Issue by jason-xxl** [alecthomas/gometalinter#224]
Is there any doc telling how? 

I didn't find from readme and also failed to figure out in my tries. Basically I need a force install command. In my test I deleted errcheck and run `gometalinter --install -u` it just output 

> Installing:
>   structcheck
>   unused
>   dupl
>   gocyclo
>   staticcheck
>   aligncheck
>   gosimple
>   interfacer
>   misspell
>   errcheck
>   gas
>   goimports
>   gotype
>   ineffassign
>   lll
>   unconvert
>   varcheck
>   deadcode
>   goconst
>   golint

but I didn't find errcheck been re-installed.

**Comment by alecthomas** [comment]
`gometalinter --install --force`
