### ISSUE TITLE
Disabling linting for generated files

### ISSUE THREAD

**Issue by NobbZ** [alecthomas/gometalinter#226]
I do have some files in my project which are generated using `golex` and `go tool yacc`, I do get a bunch of lints in them which I can't do anything about because of the nature of generated files.

Is there a way to exclude such files from metalinter?

It doesn't matter for me if they are actually linted by the tools or not, but only that they disappear from the summarized output and exit code.

**Comment by alecthomas** [comment]
Yes, there is a flag for it.

**Comment by NobbZ** [comment]
Thank you for the pointer to where to find more information about it or how
it is called. Took me another hour wading through the README and googling
around, starring at the `--help` output before actually finding `-e
"exclude/regex.go"`.

Alec Thomas <notifications@github.com> schrieb am Mo., 23. Jan. 2017 um
19:05 Uhr:

**Comment by zmb3** [comment]
Now that the community seems to have agreed on a [standard way to identify generated files](https://github.com/golang/go/issues/13560), does it make sense to reopen this issue?

I recognize that gometalinter does minimal (if any) actual parsing, so it may make sense to delegate the responsibility of ignoring generated files to the individual linters.  Though it would be really nice if gometalinter could just suppress messages from generated files.

**Comment by alecthomas** [comment]
@zmb3 that's a good idea. gometalinter is now parsing files in order to support nolint directives, so I could just add support to that.

**Comment by bradleyfalzon** [comment]
If anyone is looking at implementing this @shurcool has a library that can help if you want to use that instead: https://github.com/shurcooL/go/pull/29
