### ISSUE TITLE
Gogland integration

### ISSUE THREAD

**Issue by arnoudhgz** [alecthomas/gometalinter#228]
Would be nice if it would be available as linter in Gogland (https://www.jetbrains.com/go/)

**Comment by alecthomas** [comment]
This is not something that I can control. But AFAIK, IntelliJ products generally do not integrate external tools, they attempt to provide functionality through Java-based AST analysis/transformation.

**Comment by djui** [comment]
@arnoudhgz What is your current workaround?

**Comment by KingCrunch** [comment]
Hi @alecthomas 

> But AFAIK, IntelliJ products generally do not integrate external tools, they attempt to
> provide functionality through Java-based AST analysis/transformation.

PhpStorm for example massively uses external tools like PHPUnit, phpcs, ... . This said right now Gogland already uses `go fmt` and `goimports` as external tools.

**Comment by nickw444** [comment]
Writing this since this issue ranks higher in Google than Jetbrain's post about adding gometalinter via file watchers:

https://blog.jetbrains.com/go/2017/10/18/gogland-eap-16-file-watcher-tons-of-new-inspections-smarter-navigate-to-test-and-more/

It seems this is possible now 👍
