### ISSUE TITLE
Problem installing gometalinter

### ISSUE THREAD

**Issue by hgabe** [alecthomas/gometalinter#232]
> # cd C:\GoWorkspace\src\github.com\alecthomas\gometalinter; git pull --ff-only
> There is no tracking information for the current branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>
> 
> If you wish to set tracking information for this branch you can do so with:
> 
>     git branch --set-upstream-to=origin/<branch> master
> 
> package github.com/alecthomas/gometalinter: exit status 1
>

**Comment by alecthomas** [comment]
This is not an issue with gometalinter... Use `go get -u github.com/alecthomas/gometalinter` to update.
