### ISSUE TITLE
Installation fails using `go get -u https://github.com/alecthomas/gometalinter`

### ISSUE THREAD

**Issue by mehmetg** [alecthomas/gometalinter#233]
`➜  goWorkspace go get -u github.com/alecthomas/gometalinter        
# cd .; git clone https://gopkg.in/alecthomas/kingpin.v2 /Users/mehmetgerceker/workspace/goWorkspace/src/gopkg.in/alecthomas/kingpin.v2
Cloning into '/Users/mehmetgerceker/workspace/goWorkspace/src/gopkg.in/alecthomas/kingpin.v2'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/alecthomas/kingpin.v2: exit status 128
# cd .; git clone https://gopkg.in/alecthomas/kingpin.v3-unstable /Users/mehmetgerceker/workspace/goWorkspace/src/gopkg.in/alecthomas/kingpin.v3-unstable
Cloning into '/Users/mehmetgerceker/workspace/goWorkspace/src/gopkg.in/alecthomas/kingpin.v3-unstable'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/alecthomas/kingpin.v3-unstable: exit status **128`

**Comment by alecthomas** [comment]
This is an issue with gopkg.in. See [this issue](https://github.com/niemeyer/gopkg/issues/50) for details and a workaround.

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.

**Comment by alecthomas** [comment]
Brilliant @niemeyer, thanks!
