### ISSUE TITLE
change hardcoded concurrency value

### ISSUE THREAD

**Issue by tychoish** [alecthomas/gometalinter#234]
I think it'd be reasonable to set the number of concurrent linters to NumCPUs rather than 16. I've started to run into situations where running 16 linters at once locks up the system for a few seconds, and I'm actively observing faster performance with ~4 (which is my NumCPUs). 

Would there be objections to a pul request to change this?

**Comment by alecthomas** [comment]
Go for it. Thanks.

**Comment by alecthomas** [comment]
This was fixed in 68a96c21a13d2122a2ef76b752c8b58952c84df4.
