### ISSUE TITLE
Cannot install, remote hung up unexpectedly

### ISSUE THREAD

**Issue by Arch-Mage** [alecthomas/gometalinter#235]
installing with

    go get -v -u github.com/alecthomas/gometalinter

give me this error:

    # cd .; git clone https://gopkg.in/alecthomas/kingpin.v2 /media/ext/go/src/gopkg.in/alecthomas/kingpin.v2
    Cloning into '/media/ext/go/src/gopkg.in/alecthomas/kingpin.v2'...
    error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
    fatal: The remote end hung up unexpectedly
    package gopkg.in/alecthomas/kingpin.v2: exit status 128
    # cd .; git clone https://gopkg.in/alecthomas/kingpin.v3-unstable /media/ext/go/src/gopkg.in/alecthomas/kingpin.v3-unstable
    Cloning into '/media/ext/go/src/gopkg.in/alecthomas/kingpin.v3-unstable'...
    error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
    fatal: The remote end hung up unexpectedly
    package gopkg.in/alecthomas/kingpin.v3-unstable: exit status 128

Git seems failed to clone the code.

**Comment by alecthomas** [comment]
This is [an issue](https://github.com/niemeyer/gopkg/issues/50) with gopkg.in. There's a workaround on that page.

**Comment by Arch-Mage** [comment]
Oh, I see. Every package that depends on gopkg.in is seems to be broken too.

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.
