### ISSUE TITLE
Skip gocyclo for individual functions

### ISSUE THREAD

**Issue by powerman** [alecthomas/gometalinter#238]
I'm opening this here instead of gocyclo repo because gocyclo isn't designed to be used in CI while gometalinter is, and this issue is critical only within CI.

Sometimes function has a lot of `else if` or `case` branches because business-logic demands this, and splitting it to several functions doesn't improve anything but instead damage code readability and maintainability.

Right now only ways to handle this is to either increase global `--cyclo-over` (which will affect all packages of this project instead of single function in one of packages) or split function (and make code worse as result).

I propose to add some way to control `--cyclo-over` or disable gocyclo on per-function basis. Just like `// #nosec` used by some other linter.

**Comment by alecthomas** [comment]
I admit I have considered some kind of comment directives for gometalinter, but it would require gometalinter itself to start parsing source. I'm not sure I want to go down that route.

That said, this is definitely appropriate for filing against gocyclo.

**Comment by alecthomas** [comment]
I've created a branch that (should) support a `// nolint` directive. The syntax is:

```
// nolint[: <linter>[, <linter>, ...]]
```

eg.

```
// nolint: gocyclo, vet
```

Please check it out, give it a try, and let me know if it works for you.

**Comment by powerman** [comment]
I've played with it, not just with gocyclo but also with some other linters, tested package/function/block/line level - everything works ok! Merge it, please!! 😄

**Comment by alecthomas** [comment]
Excellent, that's great to hear :)

I need to write some tests, etc. first, but I'll try to get it into master later today.
