### ISSUE TITLE
dupl recursing subpackages when not asked.

### ISSUE THREAD

**Issue by aarondl** [alecthomas/gometalinter#24]
Running `gometalinter` without `./...` on a package with Godeps shows errors from the `dupl` linter within the `Godeps/_workspace` directory.

On a separate note, is having a hardcoded rule not to recurse into directories beginning with `_` a possibility? This is the behavior of the Go tool.

https://golang.org/cmd/go/#hdr-Description_of_package_lists (last line in that section).

**Comment by alecthomas** [comment]
> On a separate note, is having a hardcoded rule not to recurse into directories beginning with _ a possibility? This is the behavior of the Go tool.

gometalinter defaults to *not* recursing, and when using `./...` it does skip directories starting with `_` and `.`. The behaviour you saw was a bug (an omission, as I wasn't aware dupl recursed by default :().

**Comment by aarondl** [comment]
Thanks very much. Very welcome change! And I'm glad that directories starting with _ are ignored as per the go tool.
