### ISSUE TITLE
go get with go1.8 causes "unexpected directory layout" error on first try

### ISSUE THREAD

**Issue by shawnps** [alecthomas/gometalinter#242]
Running `go get -u -v github.com/alecthomas/gometalinter` first time causes this error:

```
  ~ go get -u -v github.com/alecthomas/gometalinter
github.com/alecthomas/gometalinter (download)
github.com/google/shlex (download)
Fetching https://gopkg.in/alecthomas/kingpin.v3-unstable?go-get=1
Parsing meta tags from https://gopkg.in/alecthomas/kingpin.v3-unstable?go-get=1 (status code 200)
get "gopkg.in/alecthomas/kingpin.v3-unstable": found meta tag main.metaImport{Prefix:"gopkg.in/alecthomas/kingpin.v3-unstable", VCS:"git", RepoRoot:"https://gopkg.in/alecthomas/kingpin.v3-unstable"} at https://gopkg.in/alecthomas/kingpin.v3-unstable?go-get=1
gopkg.in/alecthomas/kingpin.v3-unstable (download)
github.com/alecthomas/units (download)
github.com/nicksnyder/go-i18n (download)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
unexpected directory layout:
	import path: github.com/google/shlex
	root: /Users/shawn/mygo/src
	dir: /Users/shawn/mygo/src/github.com/alecthomas/gometalinter/vendor/github.com/google/shlex
	expand root: /Users/shawn/mygo/src
	expand dir: /Users/shawn/mygo/src/github.com/alecthomas/gometalinter/vendor/src/github.com/google/shlex
	separator: /

```

Running a second time seems to fix. Go version is Go 1.8.

@alecthomas why is there a `src` dir in the `vendor` folder? Doesn't seem used.

**Comment by alecthomas** [comment]
Hmm, weird.

There is a src directory because Go does not support installing binaries from `vendor`. To work around this, I set the `GOPATH` to the `vendor` directory.

**Comment by shawnps** [comment]
@alecthomas speaking for myself I find it a bit confusing to have anything in the vendor dir that's not being importing in the code outside of `vendor/`. My suggestion would be to stick the vendored linters into a separate dir, maybe `vendored-linters/` and have `vendor/` contain only the code that is imported like `google/shlex` etc.

**Comment by alecthomas** [comment]
As I said, the vendoring tooling does not support that (which is not surprising, as it's an unusual use-case), and previously this was not a problem. However, obviously that's no longer the case so I'll have to come up with an alternate plan.

**Comment by shawnps** [comment]
@alecthomas you can't set the `GOPATH` to `vendored_linters/` rather than `vendor/`?

**Comment by alecthomas** [comment]
Yes, that I can do, but the vendoring tool (gvt) does not support alternate directories. I'll probably end up having two separate gvt trees: `_linters/vendor/...` and `vendor/...`

**Comment by shawnps** [comment]
@alecthomas okay, I don't know the semantics of that tool, but it looks like you're doing the `GOPATH` stuff in `main.go`, so I assumed you could just stick everything in a folder like `vendored_linters`, add those to `GOPATH`, then the Go toolchain itself would take care of the `vendor` dir itself. 

You obviously know the code much better than me so I'll leave it to you. Thanks for looking into it!

**Comment by alecthomas** [comment]
Okay, give that a try. Let me know if it works now.

**Comment by shawnps** [comment]
@alecthomas I can confirm it works for me - did `rm -rf $GOPATH/src/github.com/alecthomas/gometalinter` and then:

```
➜  ~ go get -u -v github.com/alecthomas/gometalinter
github.com/alecthomas/gometalinter (download)
github.com/alecthomas/gometalinter/vendor/github.com/google/shlex
github.com/alecthomas/gometalinter/vendor/github.com/alecthomas/units
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/language
github.com/alecthomas/gometalinter/vendor/gopkg.in/yaml.v2
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/translation
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/bundle
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable
github.com/alecthomas/gometalinter
```

All seems good. Thanks for the very fast turnaround.

**Comment by alecthomas** [comment]
Excellent, thanks for the report.

**Comment by nathany** [comment]
Might be worth mentioning in the README?

(go version go1.8.5 darwin/amd64)

**Comment by chlarsen** [comment]
This did it. Thank you so much for your help and patience!
