### ISSUE TITLE
--update should imply --install

### ISSUE THREAD

**Issue by mattbostock** [alecthomas/gometalinter#246]
I expected the following command to update the linter executables:

```
$ gometalinter --update --force
```

Instead, I had to add `--install`:

```
$ gometalinter --update --force --install
```

Specifying `--update` should imply `--install`.

**Comment by alecthomas** [comment]
Actually, `--update` is a no-op, present only for backwards compatibility. You can test it yourself with `gometalinter --debug --install --update`.
