### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by reedobrien** [alecthomas/gometalinter#249]
I've been installing gometalinter like this for quite some time. On a fresh install today, I get the following.  

I don't see anything that indicates I need to do something different. 

[user:~/go/src] % go version
go version go1.8 linux/amd64

[user:~/go/src] % lsb_release -cs
xenial

[user:~/go/src] % go get -u -v github.com/alecthomas/gometalinter
github.com/alecthomas/gometalinter (download)
github.com/alecthomas/gometalinter/vendor/github.com/google/shlex
github.com/alecthomas/gometalinter/vendor/github.com/alecthomas/units
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/language
github.com/alecthomas/gometalinter/vendor/gopkg.in/yaml.v2
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/translation
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/bundle
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable
github.com/alecthomas/gometalinter

[user:~/go/src] % gometalinter --install
gometalinter: error: could not find vendored linters in 

[user:~/go/src] 1 % gometalinter
WARNING: exec: "gosimple": executable file not found in $PATH
WARNING: exec: "interfacer": executable file not found in $PATH
WARNING: exec: "errcheck": executable file not found in $PATH
WARNING: exec: "gas": executable file not found in $PATH
WARNING: exec: "varcheck": executable file not found in $PATH
WARNING: exec: "ineffassign": executable file not found in $PATH
WARNING: exec: "deadcode": executable file not found in $PATH
WARNING: exec: "golint": executable file not found in $PATH
WARNING: exec: "goconst": executable file not found in $PATH
WARNING: exec: "unconvert": executable file not found in $PATH
WARNING: exec: "staticcheck": executable file not found in $PATH
WARNING: exec: "aligncheck": executable file not found in $PATH
WARNING: exec: "gocyclo": executable file not found in $PATH
WARNING: exec: "structcheck": executable file not found in $PATH
WARNING: exec: "gotype": executable file not found in $PATH

**Comment by alecthomas** [comment]
Is your GOPATH set?

**Comment by reedobrien** [comment]
Ignore me.

**Comment by reedobrien** [comment]
1.8 sets $HOME/go I think. And I set it in /etc/profile.d/home.sh for all users, but it appears that somehow it was unset. So I don't know how it was unset, but yes that appears to have been the issue.

**Comment by alecthomas** [comment]
Okay, that is good to know though. The error should be more useful.
