### ISSUE TITLE
Add safesql

### ISSUE THREAD

**Issue by thomasheller** [alecthomas/gometalinter#250]
I would like to add [stripe/safesql](https://github.com/stripe/safesql) to gometalinter -- it finds potential SQL injection vulnerabilities in `database/sql` calls.

However, safesql operates on packages, not files. It imports packages using `golang.org/x/tools/go/loader` and also takes the `vendor` folder into account.

Is there a simple way for gometalinter to pass the Go import path to a linter instead of the file/directory path?

**Comment by alecthomas** [comment]
Shouldn't be an issue. It looks like safesql accepts directories, so you can just use `{path}`. It is mind bogglingly slow though, so it will need to be disabled by default.
