### ISSUE TITLE
Consider adding support for CopyFighter

### ISSUE THREAD

**Issue by geeknoid** [alecthomas/gometalinter#252]
https://github.com/jmhodges/copyfighter seems like a worthy addition to gometalinter's table of linters...

**Comment by alecthomas** [comment]
Unfortunately, if you take a look at the issues, you'll see there are some pretty fundamental problems. Particularly, not supporting build tags, vendor directories, or black-box tests.

**Comment by alecthomas** [comment]
Don't get me wrong, I'd like to add it as it seems very useful, but it's just not robust enough IMO.

**Comment by geeknoid** [comment]
Thanks, I hadn't noticed all its shortcomings. Maybe it'll grow up and then
can be included at some point.

**Comment by alecthomas** [comment]
👍

**Comment by xor-gate** [comment]
To bad it isn't mature yet, would be a nice addition.
