### ISSUE TITLE
Recipe for vendoring with CI?

### ISSUE THREAD

**Issue by wrouesnel** [alecthomas/gometalinter#254]
Has anyone got a recipe for vendoring gometalinter with a CI system like travis?

I like to format my golang sources so the git checkout operation pulls down everything needed to build - having an explicit "install gometalinter" step feels a little uncontrolled in that regard.

**Comment by alecthomas** [comment]
As far as I'm aware, you can not vendor Go *commands*, only packages. I've had to apply some workarounds to make this seamless in gometalinter itself.

If you do want to vendor it, you basically need to make the vendored location *look* like a `GOPATH`: `<project>/tools/src/github.com/alecthomas/gometalinter`. Then set `GOPATH=<project>/tools` and install as usual.
