### ISSUE TITLE
Idea to integrate a new unparam linter

### ISSUE THREAD

**Issue by xor-gate** [alecthomas/gometalinter#256]
Hi,

I came across this linter which checks for unused function parameters https://github.com/mvdan/unparam which is fairly new but probably nice to add in the future.

Kind regards,
Jerry

**Comment by xor-gate** [comment]
Nice, thanks!

**Comment by xor-gate** [comment]
Probably it should also be added to the README.md

**Comment by alecthomas** [comment]
Ah, alas, it relies on `sort.Sort()` which is only in Go 1.8. I had to revert it.

**Comment by xor-gate** [comment]
Thats a pitty :(

**Comment by szuecs** [comment]
@alecthomas FYI: You meant `sort.Slice()`

**Comment by mvdan** [comment]
Support for 1.7 fixed - was not able to find what Go versions `gometalinter` expects to be able to run with.

**Comment by szuecs** [comment]
@mvdan thanks for your fast response.
@alecthomas can you reopen this issue and when you have time check it again? 
Thanks!

**Comment by szuecs** [comment]
was done by  #260
