### ISSUE TITLE
`go get` Install failing due to kingpin 

### ISSUE THREAD

**Issue by marktheunissen** [alecthomas/gometalinter#261]
Running `$ go get -u gopkg.in/alecthomas/gometalinter.v1`

Results in:

> `gopath/src/gopkg.in/alecthomas/gometalinter.v1/main.go:125: cannot use loadConfig (type func(*"gopkg.in/alecthomas/kingpin.v3-unstable".ParseElement, *"gopkg.in/alecthomas/kingpin.v3-unstable".ParseContext) error) as type "gopkg.in/alecthomas/kingpin.v3-unstable".Action in argument to "gopkg.in/alecthomas/kingpin.v3-unstable".Flag("config", "Load JSON configuration from file.").Action`

> `gopath/src/gopkg.in/alecthomas/gometalinter.v1/main.go:126: cannot use disableAction (type func(*"gopkg.in/alecthomas/kingpin.v3-unstable".ParseElement, *"gopkg.in/alecthomas/kingpin.v3-unstable".ParseContext) error) as type "gopkg.in/alecthomas/kingpin.v3-unstable".Action in argument to "gopkg.in/alecthomas/kingpin.v3-unstable".Flag("disable", "Disable previously enabled linters.").PlaceHolder("LINTER").Short('D').Action`

> `gopath/src/gopkg.in/alecthomas/gometalinter.v1/main.go:127: cannot use enableAction (type func(*"gopkg.in/alecthomas/kingpin.v3-unstable".ParseElement, *"gopkg.in/alecthomas/kingpin.v3-unstable".ParseContext) error) as type "gopkg.in/alecthomas/kingpin.v3-unstable".Action in argument to "gopkg.in/alecthomas/kingpin.v3-unstable".Flag("enable", "Enable previously disabled linters.").PlaceHolder("LINTER").Short('E').Action`

> `gopath/src/gopkg.in/alecthomas/gometalinter.v1/main.go:131: cannot use disableAllAction (type func(*"gopkg.in/alecthomas/kingpin.v3-unstable".ParseElement, *"gopkg.in/alecthomas/kingpin.v3-unstable".ParseContext) error) as type "gopkg.in/alecthomas/kingpin.v3-unstable".Action in argument to "gopkg.in/alecthomas/kingpin.v3-unstable".Flag("disable-all", "Disable all linters.").Action`

> `gopath/src/gopkg.in/alecthomas/gometalinter.v1/main.go:132: cannot use enableAllAction (type func(*"gopkg.in/alecthomas/kingpin.v3-unstable".ParseElement, *"gopkg.in/alecthomas/kingpin.v3-unstable".ParseContext) error) as type "gopkg.in/alecthomas/kingpin.v3-unstable".Action in argument to "gopkg.in/alecthomas/kingpin.v3-unstable".Flag("enable-all", "Enable all linters.").Action`

**Comment by alecthomas** [comment]
Tagged v1.2.0, thanks for the ticket.

**Comment by enrichman** [comment]
Thanks for the quick fix. This was breaking our builds.
