### ISSUE TITLE
WARNING: deadline exceeded by linter

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [alecthomas/gometalinter#264]
Hello! Thanks for your work, it really helps as keep our code healthy!

We encounter [strange behaviour](https://travis-ci.org/lightningnetwork/lnd/jobs/213542611) after releasing of `1.2` tag  , and as far as `gopkg` follows the major version, our travis build have been broken 😄

But the thing is that this error only appears in the `travis`.

**Comment by alecthomas** [comment]
That is probably due to the update of unused, staticcheck and go-simple. They are now about [30x slower](https://github.com/dominikh/go-tools/issues/63) than they [used](https://github.com/dominikh/go-staticcheck/issues/55) to be. You'll need to increase your deadline.
