### ISSUE TITLE
Disable linting for generated files

### ISSUE THREAD

**Issue by alecthomas** [alecthomas/gometalinter#270]
Go now has a rough guideline for [identifying generated files](https://github.com/golang/go/issues/13560) (also see #226). Update the directives parser to handle this case.

**Comment by dolmen** [comment]
So when you write a code generator, how will you be able to lint the generated output to detect bugs?

At least an option should be available to NOT skip those files if needed.

**Comment by alecthomas** [comment]
Yeah, I agree. I will add a flag to force linting.

**Comment by korjavin** [comment]
https://github.com/gogo/protobuf generates a code with many warnings, how can I disable linting those files?

**Comment by pierrre** [comment]
Maybe we should have a flags that allows to skip files, with a regexp on the file name.

**Comment by korjavin** [comment]
Sounds good for me

**Comment by GarethLewin** [comment]
gogo/protobuf should add the header mentioned in https://github.com/golang/go/issues/13560#issuecomment-288457920

**Comment by korjavin** [comment]
the beggining of auto-generated file.
```
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg.proto

/*
    Package main is a generated protocol buffer package.

    It is generated from these files:
        msg.proto

    It has these top-level messages:
        Msg
*/
```

**Comment by alecthomas** [comment]
I will add support for the generated file comment (haven't had time yet).

The `--exclude` flag can already be used to skip files.

**Comment by dvyukov** [comment]
Hi,

I have the same problem with my own generated files. They on purpose break some rules and I would like to ignore them for some linters (or for all linters if it's not feasible to do for some).

`--exclude` flag excludes linters, not files. `skip` ignores whole packages.

I can make them conform to the rules for autogenerated files, but this is not supported by gometalinter, right?

Ideally I would like something like comment directive on a _file_, e.g. before package directive:
```
// nolint: lll,dupl
```

**Comment by dnephin** [comment]
`--exclude` works on linter messages, not linters. So you can exclude generated files with `exclude` by using a regex. I do this for things like `.*\.pb\.go`, `^internal/fakes/`, etc.
