### ISSUE TITLE
docker images?

### ISSUE THREAD

**Issue by mmlb** [alecthomas/gometalinter#271]
I'd be nice if you shipped a docker image, I'd like to use it in my ci pipeline with drone.io. The alternatives are building my own image, but then I'd have to track your master/stable releases to rebuild the image. Or I can download the binary, but that is wasteful.

**Comment by alecthomas** [comment]
I have no real interest in maintaining a docker image, sorry. I just don't have enough time. I'd be happy to assist someone else doing it though.
