### ISSUE TITLE
Add parameter to all linters

### ISSUE THREAD

**Issue by krostar** [alecthomas/gometalinter#275]
Hi,

I have to add a parameter to all linters: `-tags gtk_3_18` because I'm using the [github.com/gotk3/gotk3/gtk](https://github.com/gotk3/gotk3/gtk) lib.
I've read this issue #176 to specify a new parameter by overriding the linter.

The current solution is working, I've redefined every linters as specified in the issue mentioned above:

```
#!/bin/sh

param=$1

gometalinter --config=.gometalinter.json ./... \
	--linter="aligncheck:aligncheck ${param} {path}:^(?:[^:]+: )?(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.+)$" \
	--linter="deadcode:deadcode ${param} {path}:^deadcode: (?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$" \
	--linter="dupl:dupl ${param} -plumbing -threshold {duplthreshold} {path}/*.go:^(?P<path>.*?\.go):(?P<line>\d+)-\d+:\s*(?P<message>.*)$" \
	--linter="errcheck:errcheck ${param} -abspath {path}:PATH:LINE:COL:MESSAGE" \
	--linter="gas:gas ${param} -fmt=csv {path}/*.go:^(?P<path>.*?\.go),(?P<line>\d+),(?P<message>[^,]+,[^,]+,[^,]+)" \
	--linter="goconst:goconst ${param} -min-occurrences {min_occurrences} -min-length {min_const_length} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="gocyclo:gocyclo ${param} -over {mincyclo} {path}:^(?P<cyclo>\d+)\s+\S+\s(?P<function>\S+)\s+(?P<path>.*?\.go):(?P<line>\d+):(\d+)$" \
	--linter="gofmt:gofmt ${param} -l -s {path}/*.go:^(?P<path>.*?\.go)$" \
	--linter="goimports:goimports ${param} -l {path}/*.go:^(?P<path>.*?\.go)$" \
	--linter="golint:golint ${param} -min_confidence {min_confidence} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="gosimple:gosimple ${param} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="gotype:gotype ${param} -e {tests=-a} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="ineffassign:ineffassign ${param} -n {path}:PATH:LINE:COL:MESSAGE" \
	--linter="interfacer:interfacer ${param} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="lll:lll ${param} -g -l {maxlinelength} {path}/*.go:PATH:LINE:MESSAGE" \
	--linter="misspell:misspell ${param} -j 1 {path}/*.go:PATH:LINE:COL:MESSAGE" \
	--linter="safesql:safesql ${param} {path}:^- (?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+)$" \
	--linter="staticcheck:staticcheck ${param} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="structcheck:structcheck ${param} {tests=-t} {path}:^(?:[^:]+: )?(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.+)$" \
	--linter="test:go ${param} test {path}:^--- FAIL: .*$\s+(?P<path>.*?\.go):(?P<line>\d+): (?P<message>.*)$" \
	--linter="testify:go ${param} test {path}:Location:\s+(?P<path>.*?\.go):(?P<line>\d+)$\s+Error:\s+(?P<message>[^\n]+)" \
	--linter="unconvert:unconvert ${param} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="unparam:unparam ${param} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="unused:unused ${param} {path}:PATH:LINE:COL:MESSAGE" \
	--linter="varcheck:varcheck ${param} {path}:^(?:[^:]+: )?(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$" \
	--linter="vet:go ${param} tool vet {path}/*.go:^(?:vet:.*?\.go:\s+(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*))|(?:(?P<path>.*?\.go):(?P<line>\d+):\s*(?P<message>.*))$" \
	--linter="vetshadow:go ${param} tool vet --shadow {path}/*.go:^(?:vet:.*?\.go:\s+(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*))|(?:(?P<path>.*?\.go):(?P<line>\d+):\s*(?P<message>.*))$"
```

Some linters doesn't seems to use the tag so I have do desactivate them in the whole gui package with 
```
// nolint: gosimple, errcheck, staticcheck, unused
package gui
```

Is there is easiest solution ? A more maintainable one ?

Thanks for your help

**Comment by alecthomas** [comment]
How many of the linters support tags?

**Comment by client9** [comment]
Hi @alecthomas @krostar  

I'm the author of the optional linter client9/misspell 

Could you help me understand I bit more since I'm having a hard time following this and #176 .  By "tags" do we mean "build constraints" or "build tags" ala https://golang.org/pkg/go/build/#hdr-Build_Constraints 

If so the linter would ignore items with

```
// +build ignore
```

and if `-tags windows` was specified with the following file 

```
// +build linux
```

would be skipped as well.  etc.

I'll assume so.

@alecthomas not sure how the `nolint` tag is retrieved.  I would be nice if gometalinter provided the build-tag selectors, else it's gets messy. I'm happy to add `-tags` support, but will get tricky to get everyone to implement it.

thanks all!

n

**Comment by alecthomas** [comment]
I think this is one of those things that linters themselves need to support, and IIUC many (most?) of them do not. 

`nolint` is handled by parsing source and walking the AST. Emulating build tag support would be... painful, and I'm pretty sure it would mask underlying issues. eg. the case where a linter fails to parse an entire package due to build tag issues, and thus is not reporting actual issues. IMO it's better to report these directly so at least users know that the linter is failing.

That said, I'm open to ideas...

**Comment by ncw** [comment]
I'd be interested in `--tags` too.  To be specific this should be an option for gometalinter which is passed to the linters where they support tags.  If they don't support tags, then that is OK.

I use tags to enable compilation of optional modules.  If you don't set the tags then the linters which support them won't check the optional modules.

`-tag` is supported by errcheck.

```
$ errcheck -h
...
  -tags value
    	space-separated list of build tags to include
...
```

And also by vet

```
$ go tool vet -h
...
  -tags string
    	space-separated list of build tags to apply when parsing
...
```

**Comment by prateek** [comment]
Another possible way to override the commands is in the config file itself, here's mine for e.g.

```
{
  "Linters": {
    "unused": "unused -tags integration:PATH:LINE:COL:MESSAGE",
    "gosimple": "gosimple -tags integration:PATH:LINE:COL:MESSAGE"
  },
  "Enable": [
    "deadcode",
    "varcheck",
    "structcheck",
    "goconst",
    "ineffassign",
    "unconvert",
    "misspell",
    "gosimple",
    "unused"
]}
```

It's not ideal because it's still coupling the command with the pattern,  but I found it easier to do this as opposed to overriding on the CLI.

**Comment by Justin-W** [comment]
Please consider adding gometalinter supports for -tags (or --tags) to correspond to the `go build -tags 'mytag'` functionality.

Any linter that doesn't support a -tags param will probably generate bad output for any project that uses them for [Build Constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) (as @client9 mentioned above). It'd be much preferable for some linters to support a single pass-through from gometalinter, than the current behavior.

The workarounds mentioned above are pretty horrible/unusable. If I'm going to have to manually configure each linter (1 by 1), there is significantly less incentive to use gometalinter at all.

Thanks.
