### ISSUE TITLE
linter deadine exceeded after 30mn

### ISSUE THREAD

**Issue by krostar** [alecthomas/gometalinter#276]
Hi,

I'm trying to solve a travis build error, without success.
When I run `gometalinter --config=.gometalinter.json -d ./...`, even if I increase the deadline, it took more than 30mn to return.

I don't think my project is that heavy/complicated.

Can you help me to understand why it take that much time to finish ?
Here is the build https://travis-ci.org/krostar/nebulo-server/builds/221933222, here is the source code  https://github.com/krostar/nebulo-server/tree/966ad42f4aef330b904666aa3e31e24710b0f4ea

I've activated the debug of gometalinter, I saw some linters taking more than 20minutes, I don't understand why...

Thanks you!

**Comment by vearutop** [comment]
If you did not happen to throw away metalinter yet, try to disable `gosimple` as it consumes 8 cores of i7 24/7.

**Comment by alecthomas** [comment]
Sorry, this issue slipped by me. There are a couple of things this could be. I would first try running with `gometalinter --enable-gc`. It could be that some long-running linters are consuming a very large amount of RAM, and the machine is going into swap. I would then try disabling the linters in the [slow linters list](https://github.com/alecthomas/gometalinter/blob/master/config.go#L103).

**Comment by krostar** [comment]
I'll try that, didnt see the slow linters list before.

Thanks

**Comment by alecthomas** [comment]
This should be fixed in master.
