### ISSUE TITLE
Recursive by default

### ISSUE THREAD

**Issue by saschagrunert** [alecthomas/gometalinter#279]
Hey there,

I guess gometalinter should be recursive by default if providing no or a single path. The `./...` syntax is hard to discover and leads into failures. Also adding a cli option like `--non-recursive` could be an helpful addition. What do you think?

**Comment by GarethLewin** [comment]
I think gometalinter should follow golang standards, and all the go tools are not recursive by default, and all use the `./...` syntax.

**Comment by saschagrunert** [comment]
That is an argument, but what about a `-r/--recursive` flag?

**Comment by alecthomas** [comment]
As @GarethLewin stated, this is a standard Go feature. Go itself supports this, as do most tools.
