### ISSUE TITLE
go-nyet deprecated?

### ISSUE THREAD

**Issue by ronnylt** [alecthomas/gometalinter#28]
go-nyet seems to be deprecated. Would you mind running gometalinter with this linter disabled by default. If yes, please let me know and I will prepare a pull-request. 

Thanks.

https://github.com/barakmich/go-nyet#deprecated

**Comment by alecthomas** [comment]
Thanks for the heads up.

It seems like the right approach might be to disable go-nyet by default, and add a separate `go vet -shadow` linter, also disabled by default.

PS. Why did you close #27?

**Comment by ronnylt** [comment]
Ok, I will work on a PR. 

PS. I closed the other issue because I used my work account by mistake, instead of my personal one :)

**Comment by jgautheron** [comment]
@ronnylt I needed that update so I just went ahead and implemented it. Feel free to review the code! Thanks.
