### ISSUE TITLE
Add a '--list-linters' option, or equivalent

### ISSUE THREAD

**Issue by flimzy** [alecthomas/gometalinter#280]
I'd like the option to see a list of the installed/available linters, and gometalinter's name for them, at runtime.  A name better than `--list-linters` is probably easy to come up with.

**Comment by alecthomas** [comment]
Seems like a good idea.

**Comment by alecthomas** [comment]
They are listed in the `--help` though, or is that not sufficient?

**Comment by flimzy** [comment]
Indeed it does; I missed it as it scrolls off the screen by default.
