### ISSUE TITLE
Comment directives is not working

### ISSUE THREAD

**Issue by continuum-lokesh-jain** [alecthomas/gometalinter#284]
I tires using Comment directives to disable linter on specific line but it is not working as expected.. 
Could you please guide me how do I make this working.

Thanks,
-Lokesh

**Comment by alecthomas** [comment]
Show me an example.

**Comment by continuum-lokesh-jain** [comment]
cmd = exec.Command(absPath, f.configFilePath, f.logFilePath) // nolint

gas linter is throwing  an error at this location

**Comment by alecthomas** [comment]
That is the correct syntax and it works for me:

```
[aat@cavern:~/foo]cat t.go
package main

import "os/exec"

func main() {
	cmd := exec.Command(absPath, f.configFilePath, f.logFilePath)
}
[aat@cavern:~/foo]gometalinter --disable-all --enable gas
t.go:6::warning: Subprocess launching with variable.,HIGH,HIGH (gas)
[aat@cavern:~/foo]vi t.go
[aat@cavern:~/foo]cat t.go
package main

import "os/exec"

func main() {
	cmd := exec.Command(absPath, f.configFilePath, f.logFilePath) // nolint
}
[aat@cavern:~/foo]gometalinter --disable-all --enable gas
[aat@cavern:~/foo]
```

If you could provide a full test case, that would be useful.

**Comment by continuum-lokesh-jain** [comment]
I am storing cmd in the struct variable and then adding reader/writer and before starting the command
so that we can add a wait

**Comment by continuum-lokesh-jain** [comment]
cmd = exec.Command(absPath, configFilePath, logFilePath) // nolint
reader, err := sc.cmd.StdoutPipe()
if err != nil {
	return nil, reader, err
}
writer, err := cmd.StdinPipe()
if err != nil {
	return writer, reader, err
}
err = cmd.Start()

**Comment by alecthomas** [comment]
Please provide a full, reproducible test case for the issue. Ideally a single file I can download and test against.

**Comment by continuum-lokesh-jain** [comment]
Here is full example

package main

import "os/exec"

func main() {
	cmd = exec.Command(absPath, configFilePath, logFilePath) // nolint
	reader, err := sc.cmd.StdoutPipe()
	if err != nil {
		return nil, reader, err
	}
	writer, err := cmd.StdinPipe()
	if err != nil {
		return writer, reader, err
	}
	err = cmd.Start()
}

**Comment by continuum-lokesh-jain** [comment]
lokesh@Lokesh:~$ gedit test.go
lokesh@Lokesh:~$ 
lokesh@Lokesh:~$ gometalinter --disable-all --enable gas
test.go:6::warning: Subprocess launching with variable.,HIGH,HIGH (gas)
lokesh@Lokesh:~$

**Comment by alecthomas** [comment]
Okay, well, I can't reproduce that locally. Are you sure you have the most recent version of gometalinter?

**Comment by continuum-lokesh-jain** [comment]
I think I am but is there any way to check version

**Comment by continuum-lokesh-jain** [comment]
Thanks @alecthomas for the support, I was using older version of gometalinter upgraded this and it worked as expected
