### ISSUE TITLE
Installing linters fails

### ISSUE THREAD

**Issue by aprice** [alecthomas/gometalinter#296]
Using gometalinter@26d250e00c448606128971eca83cb3c6970ec4d8:

```
$ go version
go version go1.8.3 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/var/go"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build731715240=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

`gometalinter --install` fails because it's trying to look for the linters under vendor/, where they are not. From perusing the repo it looks like it should actually be looking for them in _linters/, but the errors do not list that as one of the locations where it's looking for them.

Installing with `--no-vendored-linters` works, but causes it to check out the git repo manually rather than just using go get (which seems like an odd choice but not necessarily a defect) and does an unnecessary `cd .` before each, which fails if you're running the install with `sudo -u` from a directory the user you're running it as does not have access to (e.g. running `sudo -u someuser gometalinter --install --no-vendored-linters` from your own home dir), as it causes `chdir .: permission denied` errors.

**Comment by alecthomas** [comment]
What errors are you referring to? Why do you think it is looking in vendor?

**Comment by alecthomas** [comment]
No response.
