### ISSUE TITLE
Allow `-shadowstrict` for `go tool vet -shadow`

### ISSUE THREAD

**Issue by breml** [alecthomas/gometalinter#298]
I would like to use the `-shadowstrict` flag for `go tool vet -shadow` in `gometalinter`. What would be the preferred way to add this to `gometalinter`?

**Comment by alecthomas** [comment]
The best way to do this is to overload the existing linter configuration. Check the bottom of the README for details on how to do this.

**Comment by katbyte** [comment]
For anyone else ending up here looking to lint shadow, it can now easily be use by adding linter `vetshadow`
