### ISSUE TITLE
linter crash doesn't make gometalinter fail

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#299]
I've updated my Go environment to Go 1.9 beta1 and now several linters (unused, gosimple, staticcheck, unparam) are crashing (`returned exit status 2`)
I will investigate about these crash separately.
In my opinion, if a linter crashes, gometalinter should:
- mark this linter as failed (with an understandable message)
- show stderr/stdout with flag `--debug`

**Comment by dnephin** [comment]
I just recently ran into a similar problem. I hit a bug in `gosimple` that caused it to panic. But the panic wasn't noticeable from the output and it looked like linting was successful.  (I'll send a PR to update the `gosimple` vendor soon).

I think we should be able to detect panics. An exit code of 2 is a good sign. I'm not sure if any linters exit with 2 in other cases. 

This would be a great addition. I should be able to work on a PR sometime soon if @alecthomas agrees.

**Comment by alecthomas** [comment]
I'm definitely in favour of correctly interpreting the exit state in case of a panic. However I'm pretty surprised an exit status of 2 is the result of a panic. IIUC that should [not be the case](http://tldp.org/LDP/abs/html/exitcodes.html). A SIGSEGV should result in an exit code of 139.

For example, a C program segfaulting results in this:

```
$ ./t
zsh: segmentation fault  ./t
$ echo $?
139
```

However an identical Go program does not:

```
$ ./tgo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x205f]

goroutine 1 [running]:
panic(0x594a0, 0xc42000a230)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
main.main()
	/Users/aat/Development/go/src/square/up/t.go:5 +0x1f
exit status 2
$ echo $?
2
```

This may be related to https://github.com/golang/go/issues/13484, though I'm not sure. There is a way to explicitly check for signal termination (outlined [here](https://github.com/golang/go/issues/7938#issuecomment-66094480)), but if the Go runtime is suppressing the signal I'm not sure what can be done.

Digging deeper, it [looks like](https://golang.org/src/runtime/signal_unix.go#L315) the signal might be falling through. Odd. That may also not be the code resulting in the status 2, though.

Anyway, a solution would be good, but trusting a status of 2 is a panic is not sufficient. gometalinter itself, for example, can exit with a status of 2.

**Comment by bradleyfalzon** [comment]
> I'll send a PR to update the gosimple vendor soon

Note, I was hoping to remove that completely in #285 (if it gets the go ahead).

**Comment by dnephin** [comment]
> but trusting a status of 2 is a panic is not sufficient

That's what I was thinking. I think we would need to parse the stderr of the process to determine if the output looks like a panic.

**Comment by pierrre** [comment]
Since the recent updates, the issue is now partially fixed: the full panic message is displayed.
```
DEBUG: warning: /home/pierre/go/bin/unparam returned exit status 2: panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called

goroutine 1091 [running]:
golang.org/x/tools/go/ssa.(*Package).build(0xc4236406c0)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2300 +0x1553
golang.org/x/tools/go/ssa.(*Package).(golang.org/x/tools/go/ssa.build)-fm()
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2260 +0x2a
sync.(*Once).Do(0xc4236406ec, 0xc4262e5798)
	/home/pierre/.gimme/versions/go1.9beta2.src/src/sync/once.go:44 +0xbe
golang.org/x/tools/go/ssa.(*Package).Build(0xc4236406c0)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2260 +0x4c
golang.org/x/tools/go/ssa.(*Program).Build.func1(0xc42bf78440, 0xc4236406c0)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2244 +0x2b
created by golang.org/x/tools/go/ssa.(*Program).Build
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2243 +0x11a
```
