### ISSUE TITLE
'gometalinter.v1 --install' not working due to not finding vendored linters

### ISSUE THREAD

**Issue by gschouse** [alecthomas/gometalinter#301]
I am trying to do 'gometalinter.v1 --install', and am getting this output:

gometalinter.v1: error: could not find vendored linters in GOPATH="/root/go"

I've been trying to fix this for awhile now and have had no success. What exactly are "vendored" linters, and how can I fix this so that I can install the linters?

**Comment by gschouse** [comment]
Just used 'gometalinter.v1 --install --no-vendored-linters' instead.

**Comment by alecthomas** [comment]
It means that gometalinter can not find the vendored linters in its own source code. If you use `go get` to install gometalinter, it should work correctly, unless there is something odd going on with your environment. Did you perhaps install it as root and run it as a user? Permission problems?

**Comment by gschouse** [comment]
I think there is something odd with the environment, so I'll try to look deeper and see if I can figure out the underlying issue. Thanks for the clarification though.
