### ISSUE TITLE
Can't run linter with --linter flag?

### ISSUE THREAD

**Issue by gschouse** [alecthomas/gometalinter#304]
I am trying to run golint with a flag:

`gometalinter --disable-all --enable=golint --linter='golint:golint -set_exit_status .'`, but when I run this I get `gometalinter: error: invalid linter: "golint"`.

How can I use this --linter flag correctly in this case?

**Comment by alecthomas** [comment]
Please read [this section](https://github.com/alecthomas/gometalinter#details) of the README.
