### ISSUE TITLE
gometalinter hangs when run on a directory with no go files

### ISSUE THREAD

**Issue by ixdy** [alecthomas/gometalinter#317]
Noticed this because our travis build (which runs `gometalinter` across our repo) started hanging yesterday.

I checked out the `gometalinter` repo locally to try to track the breaking commit; it seems like   a04df08be5899be3c7ad69aa379858dcb660c709 in #315 may have caused this bug.

To reproduce, you can just try running `gometalinter vendor/` on the gometalinter repo.

cc @dnephin

**Comment by dnephin** [comment]
Thanks for the report. I found  the problem, the errCh has no size, so it's blocking after the first error.  I'll prepare a fix later tonight or tomorrow.

**Comment by ixdy** [comment]
Thanks for the quick fix on this last week!

**Comment by ixdy** [comment]
However, it seems like the behavior is still a bit different than it used to be.

If I run `gometalinter` on a directory with no go files (e.g. `vendor/`), it now exits nonzero, whereas previously it exited 0.
```console
$ go get -u github.com/alecthomas/gometalinter 
$ gometalinter vendor/ ; echo $?
WARNING: vet: no files to lint
WARNING: vetshadow: no files to lint
2
$ git checkout 24dab941af827dbad02b431b3f1adf8efee71804
HEAD is now at 24dab94... split main package into multiple files
$ GOPATH=~/code go install github.com/alecthomas/gometalinter
$ ~/code/bin/gometalinter vendor/; echo $?
0
```

**Comment by alecthomas** [comment]
I don't think this is unreasonable, and master has no guarantees about stability.

**Comment by ixdy** [comment]
fair enough. a fix on our side is pretty trivial anyhow.

**Comment by alecthomas** [comment]
@ixdy fyi I reverted this error. It doesn't seem to add much value, and is not consistent (eg. if you disable vet, gometalinter will not error).

**Comment by ixdy** [comment]
thanks, though we also fixed our scripts to avoid the issue.
