### ISSUE TITLE
Unable to install linter packages

### ISSUE THREAD

**Issue by introllo** [alecthomas/gometalinter#321]
Ultimately, I'm trying to use the sonarqube/golang plugin (https://github.com/uartois/sonar-golang) and sonar-scanner. The GoMetaLinter step is failing on the install.  Please advise.

$ pwd
/home/user/go/src/github.com/golang/example
$ go get -u gopkg.in/alecthomas/gometalinter.v1
$ gometalinter --install
gometalinter: command not found
$ go get -u github.com/alecthomas/gometalinter
$ gometalinter --install
gometalinter: command not found
$ go list ... | grep gometalinter
github.com/alecthomas/gometalinter
github.com/alecthomas/gometalinter/regressiontests
github.com/alecthomas/gometalinter/vendor/github.com/alecthomas/units
github.com/alecthomas/gometalinter/vendor/github.com/google/shlex
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/bundle
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/language
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/language/codegen
github.com/alecthomas/gometalinter/vendor/github.com/nicksnyder/go-i18n/i18n/translation
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/cmd/embedi18n
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/cmd/genvalues
github.com/alecthomas/gometalinter/vendor/gopkg.in/yaml.v2
gopkg.in/alecthomas/gometalinter.v1
gopkg.in/alecthomas/gometalinter.v1/regressiontests
gopkg.in/alecthomas/gometalinter.v1/vendor/github.com/alecthomas/units
gopkg.in/alecthomas/gometalinter.v1/vendor/github.com/google/shlex
gopkg.in/alecthomas/gometalinter.v1/vendor/github.com/nicksnyder/go-i18n/i18n
gopkg.in/alecthomas/gometalinter.v1/vendor/github.com/nicksnyder/go-i18n/i18n/bundle
gopkg.in/alecthomas/gometalinter.v1/vendor/github.com/nicksnyder/go-i18n/i18n/language
gopkg.in/alecthomas/gometalinter.v1/vendor/github.com/nicksnyder/go-i18n/i18n/language/codegen
gopkg.in/alecthomas/gometalinter.v1/vendor/github.com/nicksnyder/go-i18n/i18n/translation
gopkg.in/alecthomas/gometalinter.v1/vendor/gopkg.in/alecthomas/kingpin.v3-unstable
gopkg.in/alecthomas/gometalinter.v1/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/cmd/embedi18n
gopkg.in/alecthomas/gometalinter.v1/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/cmd/genvalues
gopkg.in/alecthomas/gometalinter.v1/vendor/gopkg.in/yaml.v2
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go/"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

NOTE: same steps worked fine on my build agent...

# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/go"
GOTOOLDIR="/usr/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build191474321=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by alecthomas** [comment]
If the binary can't be found after you `go get` it, then `$GOPATH/bin` is not in your `$PATH`.

**Comment by introllo** [comment]
yes, of course. (sorry for the trouble.)
