### ISSUE TITLE
Type aliases produce errors with deadcode, vet, and vetshadow

### ISSUE THREAD

**Issue by mafredri** [alecthomas/gometalinter#323]
Type aliases (Go 1.9) seem to be broken with some linters.

I'm reporting this here because I believe `vet` and `vetshadow` are failing due to how they are integrated in `gometalinter`, I'm unsure about `deadcode`.

This is what I see when I run gometalinter:

```console
$ gometalinter
alias19.go:12:19:warning: expected type, found '=' (and 1 more errors) (deadcode)
alias19.go:12:19:error: expected type, found '=' (and 1 more errors) (vet)
alias19.go:12:19:warning: expected type, found '=' (and 1 more errors) (vetshadow)
```

Using the example from the README to replace `vet` with `go tool vet` I see no errors:

```console
$ gometalinter --disable-all --enable=vet --linter='vet:go tool vet -printfuncs=Infof,Debugf,Warningf,Errorf {path}:PATH:LINE:MESSAGE'
```

I've tried to use the most recent version and a few different combinations:

```console
$ go get -u -v github.com/alecthomas/gometalinter
$ gometalinter --install --update
$ gometalinter --vendored-linters ./...
$ go1.9beta2 get -u -v github.com/alecthomas/gometalinter
$ ...
```

But none seem to help.

**Comment by alecthomas** [comment]
The vet issues are almost certainly an issue with your local environment, as gometalinter just calls out to go. I would guess it's picking up the wrong `go` binary.

`deadcode` probably needs to be updated, but is basically abandonware, so it may have to be removed.

**Comment by bradleyfalzon** [comment]
`deadcode` is basically replaced with unparam/unused. But the issue appears to be because `deadcode` itself ignores build tags and was built with a version of go pre 1.9.

Personally, I'd look at removing deadcode and recommend unused instead, there's a bit of a performance difference there, but at least unused is correct.

**Comment by alecthomas** [comment]
I think I'll just remove deadcode.
