### ISSUE TITLE
Used within an Jenkins jnlp slave : crashes the connexion

### ISSUE THREAD

**Issue by squalou** [alecthomas/gometalinter#324]
Hi,

I hope anyone out there is using Jenkins and may have an idea.
gometalinker works great from my pc, from inside a docker container, no issue. 

Then, I try on Jenkins CI, using a docker container as dynamic AWS-provided Jnlp slave.

and then : 
21:20:12 + gometalinter.v1 --checkstyle
21:20:42 Cannot contact factory-slaves-cd90ec58f8825: java.lang.InterruptedException

I can't find logs or anything worthy on jenkins side. 
No idea what linter could be causing networking issues ... any help is welcome !

(I could provide steps to reproduce precisely, but for now just looking for someone who may have an overall idea)

**Comment by dnephin** [comment]
You could add the `--debug` flag to `gometalinter` to get more verbose output, that might help identify where it's failing.

**Comment by squalou** [comment]
Thanks ! 
indeed it helped a lot, I really should have thought about a verbose thing myself. Anyway, here's the explanation in case somone drops by :

- the 'cannot contact ....' error can be ignored
- debug messages continued to display after

The probleme was : jenkins interrupting the job *after* metaliter completes.

What happens is that Jenkins stops a script whenever a command returns a non-zero result....

SO :
I simply created several script call instead of 'all in one script with metalinter in the middle'

This way I can safely ignore the return code of the metalinter call, and go on with the job.

**Comment by dnephin** [comment]
Cool, glad you found it. You can also use 
```
gometalinter || true
```

or
```
set +e
gometalinter 
```
if you don't want it to exit on a non-zero code.
