### ISSUE TITLE
Differential scan

### ISSUE THREAD

**Issue by JeremyRand** [alecthomas/gometalinter#326]
It would be useful if gometalinter could perform a scan on 2 Git branches, and report only the warnings/errors that exist on one branch but not the other branch.

**Comment by alecthomas** [comment]
This is useful functionality, but is definitely outside the scope of gometalinter. I imagine there are existing tools that provide this functionality.

**Comment by bradleyfalzon** [comment]
I use and wrote https://github.com/bradleyfalzon/revgrep for this exact purpose, works better with gometalinter as the output is standardised.

**Comment by bradleyfalzon** [comment]
@alecthomas, it can be used as a library, I use it in GopherCI, it could be integrated if there's value. But I just pipe gometalinters output into it, which works fine.

**Comment by alecthomas** [comment]
Nice! That's exactly what I was thinking of.

**Comment by alecthomas** [comment]
It would actually be nice to have this as a FAQ entry for gometalinter.

**Comment by bradleyfalzon** [comment]
Sure, I can PR something for review.
