### ISSUE TITLE
Linter for warning when errors are silently discarded?

### ISSUE THREAD

**Issue by mcandre** [alecthomas/gometalinter#327]
Anyone know of a static analyzer for Go source code when errors are either assigned to blank (`_`) variables, or worse, assigned to `err` but then unused in empty code blocks (`{ }`)?

**Comment by dnephin** [comment]
I believe that is https://github.com/kisielk/errcheck

**Comment by alecthomas** [comment]
Assigning to underscore is typically seen as an explicit "i know this is an error, but i don't care". A case of "user beware", if you will.

As for the second case, that is handled by both ineffassign and megacheck. eg.

```
t.go:9:5:warning: ineffectual assignment to err (ineffassign)
t.go:9:5:warning: this value of err is never used (SA4006) (megacheck)
```
