### ISSUE TITLE
which linters are --fast?

### ISSUE THREAD

**Issue by deltaskelta** [alecthomas/gometalinter#330]
I am trying to find out which linters are run when the `--fast` option is set but I cannot find a list anywhere. I would like to add this information to the docs, but I would like some clarification first.

Thanks

**Comment by bradleyfalzon** [comment]
This was changed recently in 4d5e5411e9b10d7a94b81df14ae825954cfa2383, you can see the list of linters and if they're declared as fast with the `IsFast` bool: https://github.com/alecthomas/gometalinter/blob/master/linters.go#L236

**Comment by deltaskelta** [comment]
Actually maybe I closed the issue too fast...I can now see which ones are fast, but do you think it would be benefitial  add a `--fast-list` option so users can quickly get a list of which ones are considered fast so they don't have to dig this deep?

**Comment by alecthomas** [comment]
I think with the new configuration structure, we should probably output a more structured format for the linters. This would include whether a linter is tagged as fast or not.
