### ISSUE TITLE
Problem with single files

### ISSUE THREAD

**Issue by korrat** [alecthomas/gometalinter#331]
When running gometalinter on a single file, some linters like lll are not run and produce no error messages. 

The problem seems to lie with `partitionToMaxArgSizeWithFileGlobs` in partition.go. `pathsToFileGlobs` returns an empty slice in that case, but since `err` is `nil` the calling code continues after `partitionToMaxArgSizeWithFileGlobs` returns.

**Comment by alecthomas** [comment]
gometalinter doesn't support linting single files (as many of the underlying linters don't support it):

```
Args:
  [<path>]  Directories to lint. Defaults to ".". <path>/... will recurse.
```

**Comment by autarch** [comment]
But it _accepts_ single files and produces (bogus) output for them instead of complaining about this. I think the fact that it doesn't give you a more useful error like "please pass in directories containing packages, not files" is a bug.
