### ISSUE TITLE
Ability to configure cli parameters of sub-linters

### ISSUE THREAD

**Issue by prateek** [alecthomas/gometalinter#334]
My repository uses build-tags for certain sub-packages. To lint these packages, I need to provide `unused` a set of `-tags`. There's currently no hook for users to override the cli args used by the metalinter when executing the sub-linters.

**Comment by prateek** [comment]
Happy to provide a patch if you're good with the following approach: 
(1) add a field of cliOverrides from `linterName -> `Args` (additional `map[string]string` in this struct https://github.com/alecthomas/gometalinter/blob/master/config.go#L16)
(2) pipe that to linter constructors to override the [command](https://github.com/alecthomas/gometalinter/blob/master/linters.go#L178).

**Comment by prateek** [comment]
apologies for the noise, dupe of #275

**Comment by dnephin** [comment]
I believe you could also set tags on a specific linter by using a config which includes something like this:

```json
"linters": {
  "unused": "unused -tags tagone,tagtwo:PATH:LINE:COL:MESSAGE"
}
```

I guess that is similar to what you proposed, but it lets you override the command and the pattern used to parse output as well.

**Comment by prateek** [comment]
@dnephin cheers! that got me thinking about an easier way. Posted #336 to address, please take a look.
