### ISSUE TITLE
Fail fast

### ISSUE THREAD

**Issue by thedrow** [alecthomas/gometalinter#335]
Can we add an option to fail fast when one issue is found?

**Comment by bradleyfalzon** [comment]
I'm curious, what exactly is the reason for this? It's easy for a linter to find an issue is another part of the program unrelated to what you are working on, so you may never see the single issue.

**Comment by thedrow** [comment]
We want to fail the build if any issue occurs on any source file. 
The codebase is pretty large and there's no need to block the build worker for as long as it takes to analyze it.

**Comment by bradleyfalzon** [comment]
Understandable, but wouldn't you want to present all the issues found so they can all be fixed? Or if an issue is found, the developer obviously hasn't checked for issues locally and should run gometalinter themselves to get the entire list of issues?

**Comment by dnephin** [comment]
@thedrow I'm surprised it's still that slow after the recent performance improvements. Would you mind sharing some more about your build? Number of packages, files, lines of code, your metalinter config (file or command line, or at least the list of linters you run), and the average build time?

Thanks!

**Comment by thedrow** [comment]
I contributed https://github.com/pachyderm/pachyderm/pull/2146 in order to run gometalint.
They have a pretty large codebase but not as large as k8s I guess.
Right now it takes about 6m to process the entire codebase.
I'm simply trying to follow what they did here https://github.com/pachyderm/pachyderm/blob/master/Makefile#L470

@bradleyfalzon You're dead on. The CI server should check if anything is wrong. Further analysis can be done on the developer's machine.
Travis workers ain't cheap :) You don't want to hang them for long if you don't have too.

**Comment by alecthomas** [comment]
@thedrow somewhat related, but it appears you are using the pinned v1 of gometalinter. This does not include any of the recent performance improvements.

**Comment by thedrow** [comment]
I'd rather use a stable release so I'll wait for an official release with the performance improvements you mentioned.
