### ISSUE TITLE
linter option does not run linter not on the supported list

### ISSUE THREAD

**Issue by frozendragon498** [alecthomas/gometalinter#337]
I have created my own linter i would like to hook up to go meta linter. The documentation indicate that this is possible with the --linter option. However when i put this with my other go bin nothing happens. I clean it of all except creating a file but nothing. No error or anything. So i suspect this is never run at all.

**The command**
> gometalinter --linter='go-corp-linter:go-corp-linter ./:PATH:LINE:MESSAGE' --vendor ./...

**My code**
```

func main() {
	os.OpenFile("/tmp/test123456.txt", os.O_RDONLY|os.O_CREATE, 0666)
}
```

**Comment by dnephin** [comment]
You have to also enable it.

```
gometalinter --linter='...' --enable=go-corp-linter --vendor ./...
```
