### ISSUE TITLE
Offer builtin errblank to do errcheck -blank

### ISSUE THREAD

**Issue by mcandre** [alecthomas/gometalinter#338]
Similar to vetshadow, offer a builtin alias named "errblank" or similar to perform `errcheck -blank`.

**Comment by dnephin** [comment]
Now that full linter config can be specified from the config file it might be better to just document some of these.  For example you could do this:

```json
{
  "Linters": {
    "errcheck": {"Command": "errcheck -blank"}
  }
}
```
