### ISSUE TITLE
Enhancement: A more convenient way to pass flags to known linters

### ISSUE THREAD

**Issue by mcandre** [alecthomas/gometalinter#339]
If gometalinter already knows about a particular linter like errcheck, both the config file and gometalinter CLI flags should make is super easy (much easier than `--linter ...`) to pass flags down to the linters.

**Comment by dnephin** [comment]
I think #336 is the solution to this issue. It addresses the config.

Do you have a proposal for command line  flags? I don't see a good way of making it easier.

**Comment by alecthomas** [comment]
No response. Closing this, assuming that #336 is sufficient.
