### ISSUE TITLE
{path} template variable not substituted

### ISSUE THREAD

**Issue by djui** [alecthomas/gometalinter#340]
The README states in one example that one can use a customer linter in which `{path} will be substituted with the path given to go-metalinter. However, my customer linter gets the verbatim string `{path}`. 

Is this intended to work? If so, how would one write it?

**Comment by dnephin** [comment]
The README needs to be updated. This was removed in a recent change. 

As you noticed, paths are automatically appended to the command.

**Comment by djui** [comment]
Thanks! Will close.
