### ISSUE TITLE
Vendor matching with ./...

### ISSUE THREAD

**Issue by krhubert** [alecthomas/gometalinter#344]
About [go 1.9 matching with ./...](https://golang.org/doc/go1.9#vendor-dotdotdot)

```
By popular request, ./... no longer matches packages in vendor directories in tools accepting package names, such as go test. To match vendor directories, write ./vendor/....
```

I think, `gometalinter` should follow this standard.

**Comment by bradleyfalzon** [comment]
> I think, gometalinter should follow this standard.

I agree and I'm sure the authors do too.

Note, this is available in many of the tools when they are rebuilt, thanks to the recent work by @shurcooL in https://github.com/kisielk/gotool/pull/17 - so it's probably just gometalinter that needs some extra tweaks as it appears to special case suffix `/...`. `gotool` also only supports this behaviour when built with go 1.9+, see https://github.com/kisielk/gotool/issues/16#issuecomment-302267980 - so gometalinter might want to consider this too (matches vendor in < go1.8, doesn't match in go1.9+).

I did want to add though, that not only should `./...` skip vendor, but `./vendor/...` should descend into `./vendor` (and `./mycode/vendor/...`) as per https://go-review.googlesource.com/c/go/+/38745

I don't know specifically if gometalinter would ever pass `./...` to the tools, but if so https://github.com/alecthomas/gometalinter/blob/master/_linters/src/manifest may need to be updated to help continue this behaviour, and I'm not sure if the tools built from these vendors are ever installed in $GOPATH/bin, if so, then the vendored copy of gotool should certainly be updated.

**Comment by dnephin** [comment]
Currently `gometalinter` handles this itself by expanding `...` and filtering out vendor as long as `--vendor` (or the config field) is set.

**Comment by shurcooL** [comment]
Yep, the latest version of [`github.com/kisielk/gotool`](https://godoc.org/github.com/kisielk/gotool) package supports this, when built with Go 1.9. This project needs to update its vendored copies.
