### ISSUE TITLE
Public variable in a private method passes

### ISSUE THREAD

**Issue by Cosby86** [alecthomas/gometalinter#346]
Hello all, I hope this is the right place for my question:
I have the following scenario:
`
func testMethod(){
   VariableA := "AAA"
   ...
}
`

basically in a private method a public variable has been declared but if I run gometalinter against the code this anomaly is not found. Is there any way to catch it?

Thanks

**Comment by alecthomas** [comment]
There is no concept of public _local_ variables in Go, so that's not really an issue (though it is a bit odd). Go only supports the public/private concept at the package level.

**Comment by Cosby86** [comment]
Thank you for the feedback. Any chance to create my own custom rule i.e. to look for any fmt.Primtln in the code?

**Comment by alecthomas** [comment]
There's no simple way to do this, but you could take a look at the golint source code, it might point you in the right direction.
