### ISSUE TITLE
go type: passing the wrong type of arguments

### ISSUE THREAD

**Issue by charlierudolph** [alecthomas/gometalinter#348]
I'm executing gometalinter via
```
gometalinter ./src
```
And getting the following in the debug output: 
```
executing /Users/charlesrudolph/go/bin/gotype -e ./src/cmd ./src/drivers ./src/exit ./src/git ./src/prompt ./src/script ./src/steps ./src/util
DEBUG: [gotype.9]: warning: /Users/charlesrudolph/go/bin/gotype returned exit status 2: read src/cmd: is a directory
```
It appears when passing multiple arguments to go type it expects each to be a file. To pass directories, I believe we need separate executions.

**Comment by dnephin** [comment]
It sounds like https://github.com/alecthomas/gometalinter/blob/87259b86fdb8158e040dae398e975088873882eb/linters.go#L273 needs to be changed to `partitionToPackageFileGlobs` (like `go tool vet`).
