### ISSUE TITLE
Linters are not shut down when gometalinter is killed

### ISSUE THREAD

**Issue by JelteF** [alecthomas/gometalinter#349]
### Environment

I'm having this issue on Linux, but it might behave the same on OSX. 

### How to reproduce:

1. In one shell open `htop` to check running processes (use other process viewer if preferred)
2. In another run the following command:
```bash
gometalinter . & background=$!; sleep 0.5; kill -SIGINT $background 
```

### What I see

Heavy linters like `structcheck`, `errcheck` and `megacheck` are still running and consuming lots of CPU after the kill has finished. They are actually in a detached state without the `gometalinter` process around it when they are killed.

### What I expect

The heavy linters should stop at the same time as gometalinter. 

### Possible solution

`gometalinter` could catch common signals (INT, QUIT, ABRT) and send it to it's child processes. Possibly nicer/easier is to add all subprocess to a process group and send the signal to the process group.

**Comment by dnephin** [comment]
I guess we should add a signal handler to kill the linters

> Possibly nicer/easier is to add all subprocess to a process group 

Does that work on windows?

**Comment by alecthomas** [comment]
I can't replicate this on OSX.

**Comment by alecthomas** [comment]
(not to say it doesn't happen, and we should definitely come up with a solution)
