### ISSUE TITLE
feature request: check whether "// nolint" is still needed

### ISSUE THREAD

**Issue by ecc1** [alecthomas/gometalinter#354]
Please consider adding an option that runs linters even when "// nolint" has been specified, but only warns when there *aren't* any messages.  This would be useful to detect when the nolint declaration is no longer necessary.

**Comment by dnephin** [comment]
I like the idea of being able to validate any `// nolint` and detect when they aren't necessary anymore.

What do you think of a flag like `--warn-unused-nolint` (or maybe `--strict-nolint`, something along those lines) which would print a warning (and exit non-zero) if any `nolint` were read but didn't actually match any linting errors? It could be used along with the normal lint run so you don't have to run gometalinter twice.

Would that work for your use case?

**Comment by ecc1** [comment]
Yes, that's exactly what I want.  For example, I was using ```// nolint``` on some function calls whose result I was ignoring.  Later, that API changed to not return any results, so it was no longer necessary.  I'd like to detect that so I can remove the ```// nolint``` declaration.

**Comment by alecthomas** [comment]
That does seem useful, agreed.
