### ISSUE TITLE
gotype: failed to validate external test files

### ISSUE THREAD

**Issue by kulti** [alecthomas/gometalinter#355]
Related: #348, #353 

In go you can use `package mypackage_test` to write blackbox tests for `package mypackage`. `gotype` has 2 flags to check it separately (`-t` and `-x`).

You should run `gotype -t path_to_package` to check all files for that package with internal tests and `gotype -x path_to_package` to check external tests.

In #348 it was fixed incorrectly by changing gotype strategy. I think you should to run gotype twice for each package with `-t` and `-x` flags.

As I see that need a huge change affecting architecture. So I cannot do any good proposal now.

Regression test in `gotype_test.go` to illustrate problem:
```golang
func TestGoTypeBlackBoxTest(t *testing.T) {
	t.Parallel()

	dir := fs.NewDir(t, "test-gotype",
		fs.WithFile("file.go", fileContent("root")),
		fs.WithFile("file_test.go", fileContent("root_test")))
	defer dir.Remove()

	expected := Issues{
		{Linter: "gotype", Severity: "error", Path: "file.go", Line: 4, Col: 6, Message: "foo declared but not used"},
		{Linter: "gotype", Severity: "error", Path: "file_tet.go", Line: 4, Col: 6, Message: "foo declared but not used"},
	}
	actual := RunLinter(t, "gotype", dir.Path())
	assert.Equal(t, expected, actual)
}
```

**Comment by uudashr** [comment]
cc @dnephin

**Comment by dnephin** [comment]
I suspected this would be a problem, as mentioned https://github.com/alecthomas/gometalinter/issues/351#issuecomment-330101626

> In #348 it was fixed incorrectly by changing gotype strategy. 

#348 was the correct fix. Previously it was broken for every directory, now it's only broken for a directory with multiple packages. #348 should have restored the behaviour to what we had before we introduced partition strategy.

> I think you should to run gotype twice for each package with -t and -x flags.

I don't know if this case is really common enough to warrant such a change. I think there are some good workarounds (some are documented in #351).  Ultimately this is a problem with the `gotype` linter but we can try to work around that problem.

#352 adds a new `single-directory` partition strategy. I think that should solve the problem. With that strategy you will be able to configure `gometalinter` to add a second `gotype` linter and run against both packages.

> Regression test in gotype_test.go to illustrate problem

Thank you for this test case. I will try it out with #352

**Comment by dnephin** [comment]
Opened #356
