### ISSUE TITLE
gotype gone absolutely haywire

### ISSUE THREAD

**Issue by krancour** [alecthomas/gometalinter#357]
Ever since 3eeb3c6358a5df7222c6a7f759554cc0f9729d7b, code that was flawlessly passing the gotype linter is having hundreds of issues found by that linter. Most prominent among them are imports not found (vendored code _and_ application source code) and undeclared names.

Unfortunately, I'm not at liberty to share the code or the traces.

**Comment by dnephin** [comment]
Duplicate of #355 ? Want to try out #356 ?

Are the errors from directories that use multiple packages?

**Comment by alecthomas** [comment]
Can you try master? We just merged a fix by @dnephin .

**Comment by krancour** [comment]
Much better.
