### ISSUE TITLE
Seems like --skip and --vendor aren't working

### ISSUE THREAD

**Issue by dadgar** [alecthomas/gometalinter#359]
Working on a project which has a vendored file with lint errors. No combination of `--skip`, `--vendor` allows me to ignore these. The only solution is to use `--exclude`:

```
$ gometalinter --vendor --skip=vendor/ --disable-all --enable unconvert ./...
vendor/github.com/rkt/rkt/networking/netinfo/netinfo.go:51:13:warning: Openat not declared by package syscall (unconvert)
$  gometalinter --vendor --skip=vendor --exclude "vendor" --disable-all --enable unconvert ./...
$ # no output
```

**Comment by andrestc** [comment]
Did you fix this, @dadgar? I'm also having this issue.

**Comment by dadgar** [comment]
@andrestc I closed since the reported issue was due to a real compile error but this may still be a real issue. You may want to open up an issue describing what you are seeing.
