### ISSUE TITLE
Add regression tests to .travis.yml

### ISSUE THREAD

**Issue by cep21** [alecthomas/gometalinter#36]
It won't detect upstream changes, but will detect changes at least on every commit.

**Comment by alecthomas** [comment]
I have no idea what this means.

It installs all the linters then tests them. If they change output the tests will fail. If you're suggesting running the tests whenever the upstream changes, then Travis [does not support this feature](https://github.com/travis-ci/travis-ci/issues/249).

**Comment by cep21** [comment]
You're right.  I got confused :/
