### ISSUE TITLE
golint linter broken?

### ISSUE THREAD

**Issue by otto-md** [alecthomas/gometalinter#362]
Hello again,

I'm trying to run the `golint` linter but I dont get any output.

Relevant parts of gometalinter.json:
```json
    "DisableAll": true,
    "Enable": [
        "golint"
    ],
    "Skip": [
        "node_modules",
        "vendor"
    ],
    "Vendor": true,
    "Debug": true,
    "Test": true
```

Debug output:
```
DEBUG: [golint.1]: executing /Users/ottob/go/bin/golint -min_confidence 0.800000 ./ACE ./ACE/alerts
DEBUG: [golint.1]: golint hits 0: ^(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$
DEBUG: [golint.1]: golint linter took 10.082839ms
```
If I try to run this generated command manually:
```
$ golint -min_confidence 0.800000 ./ACE ./ACE/alerts ./ACE/block
read ./ACE: is a directory
read ./ACE/alerts: is a directory
```
Running golint with a single path works:
```
$ golint -min_confidence 0.800000 ./ACE
ACE/context.go:8:7: should not use basic type string as key in context.WithValue
```
So maybe another strategy is needed to pass the input files/packages to golint?

**Comment by dnephin** [comment]
The version of `golint` that is bundled with `gometalinter` does support multiple directories:

```
golint [flags] [directories] # where a '/...' suffix includes all sub-directories
```
```
$ golint . regressiontests/
# found issues in both packages
```

How did you install `golint`?

**Comment by otto-md** [comment]
I installed it from https://github.com/golang/lint

**Comment by dnephin** [comment]
gometalinter has linters vendoered at https://github.com/alecthomas/gometalinter/tree/master/_linters to prevent conflicts like this. I think they were all updated recently. You can install the vendoered version using `gometalinter --install` (but that will install all of them).

You can also do something like this (change `/go/src` to match your GOPATH):

```
BOBIN=/usr/local/bin GOPATH=/go/src/github.com/alecthomas/gometalinter/tree/master/_linter go install golint
```

**Comment by otto-md** [comment]
Thanks, Ill try that.

**Comment by otto-md** [comment]
My version of `golint` was too old. Everything works now after a `go get -u github.com/golang/lint/golint`. Thanks for your help.
