### ISSUE TITLE
document gotypex

### ISSUE THREAD

**Issue by charlierudolph** [alecthomas/gometalinter#364]
This was a new linter that is enabled by default but doesn't appear on the README

**Comment by dnephin** [comment]
cc @kulti

**Comment by alecthomas** [comment]
@charlierudolph is it causing problems, or just reporting issues that it wasn't before?

**Comment by charlierudolph** [comment]
I disabled the linter and was just suggesting documenting it as I didn't know what it was and had to look through the commits to see what it was

**Comment by dnephin** [comment]
@kulti yes adding another line to the README in the list of linters would be great. This is similar to `vet`/`vetshadow` and they are both listed separately. I guess it should say `gotypex - ... in external test packages` or something along those lines.
