### ISSUE TITLE
gometalinter doesn't behave the same on linux and macos

### ISSUE THREAD

**Issue by vincentserpoul** [alecthomas/gometalinter#366]
I use both a mac and linux machine.
When I run gometalinter on my mac or on my linux, I don't get the same results.
Are the linters not available on both platform?
What else could be the source of the difference?

**Comment by alecthomas** [comment]
What have you tried, to debug it?

**Comment by vincentserpoul** [comment]
I first tried debug it, nothing was faulty or showed any error.
I then realized I had both installed gometalinter as a local bin (from release dl) and go bin (from go get -u).
It was using the release gometalinter on my mac...
Stupid issue that I kept for quite some time.
