### ISSUE TITLE
WARNING: invalid command ""

### ISSUE THREAD

**Issue by Bo0mer** [alecthomas/gometalinter#369]
Commit 90d987842c8b2b8591691f6227d855a3a992e202 switches from `aligncheck` to `maligned`, which causes `gometalinter` to fail with the following output:
```
$ gometalinter --config=./gometalinterconfig.json ./...
WARNING: invalid command ""
```
when provided with the following config:
```json
{
  "Enable": [
    "aligncheck",
    "deadcode",
    "errcheck",
    "gas",
    "goconst",
    "gocyclo",
    "gotype",
    "ineffassign",
    "interfacer",
    "megacheck",
    "structcheck",
    "unconvert",
    "varcheck",
    "vetshadow",
    "vet",
    "errcheck",
    "golint"
  ],
  "Deadline": "2m"
}
```

This is caused by the fact that the definition of the `aligncheck` in `linters.go` was substituted by the one for `maligned`. Adding an alias for `aligncheck` which actually runs `maligned` is a possible solution:
```diff
diff --git a/linters.go b/linters.go
index 56d7c05..c457ac1 100644
--- a/linters.go
+++ b/linters.go
@@ -193,6 +193,14 @@ var defaultLinters = map[string]LinterConfig{
                PartitionStrategy: partitionPathsAsPackages,
                defaultEnabled:    true,
        },
+       "aligncheck": { // for compatibility
+               Name:              "maligned",
+               Command:           "maligned",
+               Pattern:           `^(?:[^:]+: )?(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.+)$`,
+               InstallFrom:       "github.com/mdempsky/maligned",
+               PartitionStrategy: partitionPathsAsPackages,
+               defaultEnabled:    true,
+       },
        "deadcode": {
                Name:              "deadcode",
                Command:           "deadcode",
```

I'm not sure whether this should be a supported thing, but it took me some time to figure it out, so I'm sharing in case someone struggles too.

**EDIT:** Actually any typo in the linter name specified via the configuration file will result in the same warning message and to failure. I think that checking that the provided configuration is sane before actually running all the linters could be of help here, e.g.
```
$ gometalinter --config=./config_with_a_typo.json ./...
gometalinter: Unknown linter: "123
$ echo $?
1
```

Thanks for your awesome work!
Cheers,
Ivan

**Comment by dnephin** [comment]
Keeping the definition for `aligncheck` as `defaultEnabled: false` sounds reasonable to me. We should probably also add a warning that it should be replaced by `maligned` so that users know to update.

The error for `invalid command` should probably include the name of the linter to make it easier to debug.  

The error about "unknown linter: 123" seems ok. How do you think it can be improved?

**Comment by rikvdh** [comment]
I'd prefer a deprecation warning when linters go out of service. Having suddenly gometalinter failing with a odd error message is quite 'unstable' behavior.

Perhaps also some compatibility could be added, for example that having a linter enabled named `aligncheck` which is an alias for `maligned` with a deprecation notice.

**Comment by zmb3** [comment]
My bad - didn't think of this case.  Let me know what you think the best option is for deprecating `aligncheck`.  In this case we didn't remove a linter, we just replaced it with a functionally equivalent alternative.  Maybe we can issue a warning when `aligncheck` is listed but still run `maligned`?
 
In the meantime, I'll throw something together to clean up the error message.

**Comment by alecthomas** [comment]
The stable releases of gometalinter on gopkg are intended to be non-breaking. Master has no such guarantees. With all the recent changes, I think we'll bump the stable version to `gometalinter.v2` once the dust settles on the partitioning refactor.

**Comment by alecthomas** [comment]
I think this is fixed.
