### ISSUE TITLE
Support gofmt

### ISSUE THREAD

**Issue by cep21** [alecthomas/gometalinter#37]

**Comment by cep21** [comment]
gofmt prints diffs not lines with issues.  I could special case it and find the first line with an issue and print a generic warning about ```Some kind of gofmt issue on this line.  Recommend running gofmt -s -e <filename.go>```

Thoughts @alecthomas ?

**Comment by alecthomas** [comment]
I don't personally use this, but I assumed that one warning per file would be enough? This seems reasonable to me:

```
gometalinter --linter='gofmt:gofmt -l *.go:^(?P<path>[^\n]+)$' --message-overrides='gofmt:file is not gofmted' --severity=gofmt:warning --disable-all --enable=gofmt
```

It does make the line number 0, but that could be changed to line 1.

**Comment by jgautheron** [comment]
@cep21 I just added support for `goimports` (always has been in my toolchain with `gofmt`).
Can you tell me if you're working on this? if not I'd gladly throw a PR as well.

**Comment by cep21** [comment]
Please submit one!

**Comment by jgautheron** [comment]
Done! does the current implementation fits your needs?

**Comment by cep21** [comment]
Yeap!  Best we can easily do since it outputs diffs.
