### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by wknapik** [alecthomas/gometalinter#371]
Hi. I'm seeing a 3x-7x speedup between gometalinter.v1 and the latest gometalinter from master. That's a very strong reason to use the latest version, but I don't want to depend on something mutable. `go get` doesn't support fetching specific revisions, so a new release would be appreciated. Thanks.

**Comment by dnephin** [comment]
You can run against a pinned pre-relase version using something like this:

```sh

GOMETALINTER_SHA=8eca55135021737bbc65ed68b548b3336853274c
go get -d github.com/alecthomas/gometalinter && \
        cd /go/src/github.com/alecthomas/gometalinter && \
        git checkout -q "$GOMETALINTER_SHA" && \
        go build -v -o /usr/local/bin/gometalinter . && \ 
        gometalinter --install
```

I believe @alecthomas is looking to do a v2 release pretty soon, one all the issues with the new partition strategies are worked out.

**Comment by wknapik** [comment]
Thanks for the hint, but that just feels too hacky to me. It's cleaner to just fork the repo, while waiting for v2 - if you don't push any changes, you have an immutable package with a single-line change in your build system.

On that note - these hardcodes https://github.com/alecthomas/gometalinter/blob/master/main.go#L22 prevent `gometalinter --install` from working with a fork, at least ootb.

**Comment by dnephin** [comment]
Hmm, why do you think it's hacky? It's something that is done by plenty of large go projects ([docker](https://github.com/docker/docker-ce/blob/master/components/engine/hack/dockerfile/install-binaries.sh#L79-L82), [docker/cli](https://github.com/docker/cli/blob/master/dockerfiles/Dockerfile.lint#L5-L11), [kubernetes](https://github.com/kubernetes/kubernetes/blob/be8f1cea8082b03e4322f9f6b474f5ed5ff8679a/hack/lib/util.sh#L488-L490)).

**Comment by wknapik** [comment]
Because you're exchanging a single, common, portable, high-level operation:
```
go get <url>
```
for four special-case, non-portable, low-level operations:
```
GOMETALINTER_SHA=8eca55135021737bbc65ed68b548b3336853274c
go get -d github.com/alecthomas/gometalinter && \
        cd /go/src/github.com/alecthomas/gometalinter && \
        git checkout -q "$GOMETALINTER_SHA" && \
        go build -v -o /usr/local/bin/gometalinter .
```

**Comment by fho** [comment]
Any news on this? When will a new version be released approximately?

**Comment by zramsay** [comment]
One solution would be to use [git flow](http://nvie.com/posts/a-successful-git-branching-model/) so that all development happens on the `develop` branch and any merges to `master` involve a corresponding release and version bump. Then there is at least _some_ stability to running `go get` and breaking changes happen far less frequently. We're also trying to avoid the 4 line hack and relying on v1 runs into problems such as #300

**Comment by dnephin** [comment]
An improvement to the "hack":

```sh
go get -d "$repo"
cd "$(go list -f '{{.Dir}}' $repo)"
git checkout -q "$sha"
go install .
```

This should be just as portable as `go get` as it uses effectively the same binaries (`go`, and `git`) plus `cd` which should be available everywhere.

**Comment by alecthomas** [comment]
Releases will now automatically be created from vx.y.z tagged commits.
