### ISSUE TITLE
Consider adding support for nakedret

### ISSUE THREAD

**Issue by kostix** [alecthomas/gometalinter#372]
The [`nakedret` linter](https://github.com/alexkohler/nakedret) appears to be quite a useful addition to the toolbelt provided by `gometalinter`.

**Comment by dnephin** [comment]
You can use the `nakedret` linter with the following config:

```json
{
 "Linters": {
      "nakedret": {
        "Command": "nakedret",
        "Pattern": "^(?P<path>.*?\\.go):(?P<line>\\d+)\\s*(?P<message>.*)$"
      }
  },
  "Enable": ["nakedret"]
}
```

We could also add it as a default linter if there is lots of interest.

**Comment by alexkohler** [comment]
@dnephin If you guys are on board for adding it as a linter (disabled by default), I could take a stab at the PR.

**Comment by dnephin** [comment]
I added it to one of the projects I work on and I found it to be useful, so SGTM.

@alecthomas what do you think?

**Comment by alecthomas** [comment]
Sounds fine to me.
