### ISSUE TITLE
mvdan.cc linters erroring out

### ISSUE THREAD

**Issue by alaska** [alecthomas/gometalinter#378]
# Problem:

``` 
$ gometalinter -i
Installing:
  dupl
  gas
  golint
  gosimple
  lll
  unparam
  unconvert
  errcheck
  goimports
  ineffassign
  interfacer
  misspell
  staticcheck
  structcheck
  aligncheck
  deadcode
  goconst
  safesql
  gocyclo
  gotype
  unused
  varcheck
can't load package: package github.com/mvdan/unparam: cannot find package "github.com/mvdan/unparam" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/unparam (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/unparam (from $GOPATH)
can't load package: package github.com/mvdan/interfacer/cmd/interfacer: cannot find package "github.com/mvdan/interfacer/cmd/interfacer" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOPATH)
WARNING: failed to install one or more linters: exit status 1 (installing individually)
can't load package: package github.com/mvdan/unparam: cannot find package "github.com/mvdan/unparam" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/unparam (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/unparam (from $GOPATH)
WARNING: failed to install github.com/mvdan/unparam: exit status 1
can't load package: package github.com/mvdan/interfacer/cmd/interfacer: cannot find package "github.com/mvdan/interfacer/cmd/interfacer" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOPATH)
WARNING: failed to install github.com/mvdan/interfacer/cmd/interfacer: exit status 1
gometalinter: error: failed to install the following linters: github.com/mvdan/unparam, github.com/mvdan/interfacer/cmd/interfacer
```

# Solution?
I suspect it's because of this: 
```
$ go get github.com/mvdan/unparam
can't load package: package github.com/mvdan/unparam: code in directory /<my gopath>/src/github.com/mvdan/unparam expects import "mvdan.cc/unparam"
```

So, it seems that @mvdan still hosts / develops(?) his packages on github, but has moved the import paths to his own domain. Judgements on the wisdom of this decision aside, this is probably just a simple path change.

**Comment by dnephin** [comment]
I can't reproduce this error. I tried with both `go get gopkg.in/alecthomas/gometalinter.v1` and `go get github.com/alecthomas/gometalinter` using Go 1.9.

Which version of gometalinter are you using? I believe all recent versions use a vendoered version of the linters from the local git repo, so they shouldn't be trying to download anything from github.

**Comment by alaska** [comment]
```
~/<my gopath>/src/github.com/alecthomas/gometalinter $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
$ go install
$ gometalinter -i
Installing:
  errcheck
  gocyclo
  goimports
  ineffassign
  dupl
  golint
  gotype
  interfacer
  varcheck
  aligncheck
  goconst
  gosimple
  staticcheck
  structcheck
  unconvert
  gas
  lll
  misspell
  safesql
  unparam
  unused
  deadcode
can't load package: package github.com/mvdan/interfacer/cmd/interfacer: cannot find package "github.com/mvdan/interfacer/cmd/interfacer" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOPATH)
can't load package: package github.com/mvdan/unparam: cannot find package "github.com/mvdan/unparam" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/unparam (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/unparam (from $GOPATH)
WARNING: failed to install one or more linters: exit status 1 (installing individually)
can't load package: package github.com/mvdan/interfacer/cmd/interfacer: cannot find package "github.com/mvdan/interfacer/cmd/interfacer" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/interfacer/cmd/interfacer (from $GOPATH)
WARNING: failed to install github.com/mvdan/interfacer/cmd/interfacer: exit status 1
can't load package: package github.com/mvdan/unparam: cannot find package "github.com/mvdan/unparam" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/mvdan/unparam (from $GOROOT)
        /<my gopath>/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/unparam (from $GOPATH)
WARNING: failed to install github.com/mvdan/unparam: exit status 1
gometalinter: error: failed to install the following linters: github.com/mvdan/interfacer/cmd/interfacer, github.com/mvdan/unparam
```

Is the fact that I'm using HEAD a problem? Should I be using a tag instead?

**Comment by alaska** [comment]
The problem linters don't look to be vendored at all:

```
[pigly] ~/<my gopath>/src/github.com/alecthomas/gometalinter/vendor [master|✔]$ find . -type d
.
./github.com
./github.com/alecthomas
./github.com/alecthomas/units
./github.com/google
./github.com/google/shlex
./github.com/nicksnyder
./github.com/nicksnyder/go-i18n
./github.com/nicksnyder/go-i18n/i18n
./github.com/nicksnyder/go-i18n/i18n/bundle
./github.com/nicksnyder/go-i18n/i18n/language
./github.com/nicksnyder/go-i18n/i18n/language/codegen
./github.com/nicksnyder/go-i18n/i18n/translation
./gopkg.in
./gopkg.in/alecthomas
./gopkg.in/alecthomas/kingpin.v3-unstable
./gopkg.in/alecthomas/kingpin.v3-unstable/cmd
./gopkg.in/alecthomas/kingpin.v3-unstable/cmd/embedi18n
./gopkg.in/alecthomas/kingpin.v3-unstable/cmd/genvalues
./gopkg.in/yaml.v2
```

**Comment by dnephin** [comment]
The linters are under `_linters`.

What's the git sha (`git rev-parse HEAD`), 9165748669edf1f7e77f96f1e01b01aa24a26ad3? `go get` pulls master so that is what I tested as well. Maybe it's your environment? I ran my test from inside an empty docker container so there were no conflicts.

**Comment by alaska** [comment]
```
$ git rev-parse HEAD
9165748669edf1f7e77f96f1e01b01aa24a26ad3
```

What about my environment? I have an explicit (singular) gopath set, and the bin directory for this gopath comes before the bin of my default gopath $HOME/go.

**Comment by dnephin** [comment]
> What about my environment?

Possibly that there are other projects checked out in the same GOPATH, but I'm not sure.

I took another look at the contents of master. It seems we are already using the canonical path for these linters. They are under `_linters/src/mvdan.cc/` so it's strange that something is looking for `github.com/mvdan/unparam`. There are no go files in the repo that reference that path.

```
$ git grep github.com/mvdan/unparam
# README.md and _linters/src/manifest are the two files listed

$ git grep github.com/mvdan/interfacer/cmd/interfacer
# no matches
```
It's not clear to me why go is looking for these paths, but it doesn't happen for me in an empty container, or in our CI when using `master`. Maybe try with a fresh `GOPATH` with nothing else installed? either in a container, or just setting `GOPATH` to some empty directory.

**Comment by alaska** [comment]
I'm going to close this for now. There is some major oddness in my OSX environment.  It looks like it was using another gometalinter from an alternate gopath, despite `which gometalinter` returning the correct one. That's upsetting, but clearly not the project's fault.

**Comment by andrewwebber** [comment]
I have this issue on fedora, golang 1.9.1

**Comment by mvdan** [comment]
I'm around to fix any issues on my side if necessary, but it doesn't look to be the case :)

**Comment by Quasilyte** [comment]
This issue is reproducible.

Seems like `gometalinter` tries to install `unparam` from `github.com`, but will fail with:
```
can't load package: package github.com/mvdan/unparam: code in directory ~/go/src/github.com/mvdan/unparam expects import "mvdan.cc/unparam"
```
This can be reproduced with `go get github.com/mvdan/unparam`.

**Comment by alecthomas** [comment]
This is a different issue, apparently caused by unparam having moved.

**Comment by Quasilyte** [comment]
> This is a different issue, apparently caused by unparam having moved.

Why do you think it's a different issue?
I have exactly the same repro steps as in original message,
error messages are the same.

I tried to workaround it and found information that provided in my previous message.

Also note `Solution` section of original message. It points to that very issue.

I do believe that it's more correct to fix a way gometalinter tries to install those packages rather than asking @mvdan to do something with it.

**Comment by alecthomas** [comment]
Ah sorry, I didn't see the final error line in the original message on mobile.

**Comment by Quasilyte** [comment]
Today I found another person facing this issue.
Please, re-open this issue.

Maybe someone will send a PR.

**Comment by Quasilyte** [comment]
Turns out this issue is harder to reproduce than I thought.
I will try to record precise info if it will bite me again.

I'm too unfamiliar with a way gometalinter does it's `--install` to predict what could lead to that or to magical fix that made it impossible to reproduce.

**Comment by vvb** [comment]
I have also bumped into this,

```
