### ISSUE TITLE
API based integration with linters

### ISSUE THREAD

**Issue by vektah** [alecthomas/gometalinter#380]
Most of the time spent running gometalinter is due to each linter parsing the project individually. 

This leads to a lots of wasted effort and cycles:
 - linter aggregators pop up eg [megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck)
 - lots of duplicated parsing code
 - subtle differences in the way paths are read
 - installing metalinter requires installing all the sublinters. versioning is awkward.

path bugs are probably the worst, as they often lead to silent failures where the linter being called does nothing but does not fail.

What I propose instead is two interfaces that external linters can satisfy.

One for linters that work on the raw file, without the ast:
```go
type FileLinter func(filename string) []Error
```

and one for the heavier linters that use the AST
```go
type ASTLinter func(file *ast.File, scope *types.Scope) []Error
```

This has a bunch of benefits:
 - gometalinter can vendor in the linters making it easy to `go get`
 - gometalinter could ship a single precompiled binary release without the need for --install
 - gometalinter can do one parse of the source
 - writing a new linter is easier if you dont need to write a cli interface, gometalinter (or another separate package) could even provide a stand alone linter cli interface so the go linter ecosystem can start to stabilize their cli interfaces.
 - standardizing on a linting error type means richer context than can be returned by parsing cli output
 - panics from a linter much easier to deal with

**Comment by alecthomas** [comment]
I've had similar thoughts myself in the past, but the hurdle isn't really technical it's having time to implement the code, or convincing maintainers to implement it.

**Comment by Vektah** [comment]
Build it and they will come? I recently wrote a linter and if and API like the one above existed it would have been a no brainer to write it directly for gometalinter. Plus a few practices to existing repos probably wouldn't be too hard.

**Comment by dnephin** [comment]
I have also wanted this, but it seemed less urgent after the changes I made to the partitioning, since it greatly reduced the runtime. 

@Vektah are you using v1 or master of gometalinter? master is much faster

> installing metalinter requires installing all the sublinters. versioning is awkward.

This is mostly fixed by vendoring linters in `_linters`, but in-process would still be an improvement.

-----

Converting every linter to the in-process interface all at once would be difficult (especially difficult for `gofmt`, and `go vet` that are part of the stdlib). 

Providing the interface and allowing both out-of-process and in-process linters at the same time would be good. That way it would still be possible to have `gometalinter` run new linters that are not compiled in.

I expect many linters will want to continue to run stand alone as well.

**Comment by Vektah** [comment]
> @Vektah are you using v1 or master of gometalinter? master is much faster

Yeah, you're right it's fast enough on machines with enough cores. Its probably the least interesting point above.

I am most interested in being able to quickly spin up new linters with a standard cli interface and good path handling
`mylinter ./...` vs `mylinter foo.go` vs `mylinter github.com/foo` vs `mylinter .`

Followed by richer error handling / less regexing, better panic handling (I've seen metalinter pass when linters have panicked), single binary releases.

> Converting every linter to the in-process interface all at once would be difficult (especially difficult for gofmt, and go vet that are part of the stdlib).
>
> Providing the interface and allowing both out-of-process and in-process linters at the same time would be good. That way it would still be possible to have gometalinter run new linters that are not compiled in.

Yeah 100% this would need to be a change that linters can incrementally opt into. I'm pretty sure an ExecLinter could be built that satisfies either of the interfaces above. Perhaps a third interface would be needed for the package level partition strategy.

> I expect many linters will want to continue to run stand alone as well.

Of course, this is just an opt-in interface.

**Comment by alecthomas** [comment]
I think it's a great idea.

To add to what's here, I'll note that @dominikh's tools already conform to a [conceptually similar API](https://godoc.org/honnef.co/go/tools/lint#Linter) based on [golang.org/x/tools/go/loader](https://godoc.org/golang.org/x/tools/go/loader). I believe there are quite a few linters that do the same. I suspect some linters probably also work on a `go/token.FileSet`, so we'd probably need to support a few different interfaces.

As for migrating existing tools that do not have an API interface, a low-impact approach might be to refactor them to expose a minimal public interface (that doesn't depend on the metalinter API). We could then write adapters between the two APIs. Taking megacheck as an example, write an adapter that translates `[]Problem` into `[]Issue` (or whatever).

@dominikh high-level, any thoughts?

**Comment by dominikh** [comment]
I'm seeing two separate ideas here. One is having linters expose an interface that takes in arguments (files, import paths) and returns a list of problems. The other is sharing work by having said interface accept `*ast.File` or `*loader.Program`.

The first idea is a decent idea in general. Linters that do not yet have such an API can easily add it, and ones that do have one (primarily my tools) can be wrapped around with adapters, as @alecthomas suggests.

The second idea is a bit more problematic. Passing in an `*ast.File` is definitely insufficient for certain classes of linters. Passing in a `*loader.Program` would work for the majority of linters, but not mine, as my tools will soon depend on a custom loader and different internal representations. The idea of sharing work has come up in the past, see for example https://github.com/dominikh/go-tools/issues/39#issuecomment-281698568 and https://github.com/mvdan/lint

**Comment by Vektah** [comment]
> but not mine, as my tools will soon depend on a custom loader and different internal representations.

Interesting, could you go into any detail around why loader.Program is insufficient? Are you doing more analysis in the loader? Is that something that would be useful to other linters?

**Comment by dominikh** [comment]
@Vektah The long-term goal is writing a loader that can use an on-disk cached representation of packages. Similar to object files in $GOPATH/pkg, but containing a full representation of the AST, type system and SSA form¹. In the process, I will introduce an abstraction that matches my own needs closer than go/loader does, by bridging some gaps and exporting more data.

The caching loader could benefit other tools, but I'm reluctant to suggest anyone build their linters on top of my APIs, as my APIs are not stable and change regularly to suit my own needs.

¹: it is also worth noting that my SSA form isn't the upstream go/ssa form, but a custom fork, which allows me to access some interna, implement e-SSA form and in general customize the SSA form to my own needs.

**Comment by Vektah** [comment]
That sounds awesome. 

It also sounds like that your linters wouldn't benefit much from the shared work anyway, and probably end up being the fastest part of doing a linter pass.  

Perhaps we just need find the right interfaces. It sounds like so far we have:
 - filename (gofmt/goimports)
 - single package (partitioned cli wrappers)
 - loader.Program (most other linters needing AST and types)

What would be the ideal way to programmatically invoke one of your linters and get back the problems? Is invoking per-package to much overhead?

**Comment by dominikh** [comment]
I'd suggest a slice of import paths instead of a single import path, akin to the current support for `...` – tools that do not wish to support running on multiple packages at once can implement a simple loop, and operating on multiple packages at once will benefit most linters that do type-checking, such as errcheck.

**Comment by Vektah** [comment]
Sounds reasonable:
```go
type Issue {
	// this is the gometalinter struct, minus Linter and formatTmpl
	Severity   Severity `json:"severity"`
	Path       string   `json:"path"`
	Line       int      `json:"line"`
	Col        int      `json:"col"`
	Message    string   `json:"message"`
}

type FileLinter func(filenames []string) []Error
type PackageLinter func(packages []string) []Error
type ProgramLinter func(program *loader.Program) []Error
```

Another thing to consider is config. Perhaps letting linters do their own thing and parse cli flags directly is enough?

**Comment by dominikh** [comment]
Regarding config, that contradicts separation of concerns for most tools, where the frontend parses CLI flags and populates configuration structs for the backend.

For example, in my tools, `cmd/<tool>` is responsible for handling the CLI and instantiates `<tool>` (a different package) with the correct configuration set.

**Comment by Vektah** [comment]
Yeah, I agree. But config is a harder problem. gometalinter shouldn't need to know what options are available for each linter, should it? 

Maybe most tools are simple enough that a `map[string]string` is enough? the cli could represent it similar to `go build / go test` with `gometalinter -govet.composites=false`, and the json config falls out pretty naturally.

**Comment by alecthomas** [comment]
A couple of issues requesting [new](https://github.com/alecthomas/gometalinter/issues/383) [linters](https://github.com/alecthomas/gometalinter/issues/381) have been added subsequent to this one. I propose we use these as a test-case for this newly proposed API.

I've had a quick look through the code for one of them, and it seems relatively straightforward to modify them in this fashion.

CCing the authors of the tools for feedback/thoughts: @richardartoul and @alexkohler.

To recap for their benefit:

1. gometalinter: add interfaces to support the most common integration scenarios (SSA, source file, etc.). 
2. Each tool: factor out an entry point separate from the `main` package so that gometalinter can import it. It could be as simple as `Lint(fs *ast.FileSet, file *ast.File)` (or whatever). The existing `main` package of the tool would also import this.
3. gometalinter: write an adapter between this API and gometalinter's interface.

In an ideal world the factored out interface would be identical to gometalinter's interface and no adapter would be necessary.

**Comment by Vektah** [comment]
Config aside I completely agree, as long as linters have a method outside of the main package that can be called into (ideally asking for whatever parse tree use internally) it can be wired up with some glue.

**Comment by alexkohler** [comment]
@alecthomas thanks for the recap! I think this is a great idea - it shouldn’t be too bad to wire up an entry point. I’d be glad to be a test case for this new API.

**Comment by richardartoul** [comment]
Same, happy to be a guinea pig

**Comment by richardartoul** [comment]
To recap as someone who has written a linter that will be testing this feature, I'm waiting for the new interface to be integrated into gometalinter, correct?

**Comment by alecthomas** [comment]
@richardartoul correct.

**Comment by alecthomas** [comment]
I've started working on this in https://github.com/alecthomas/gometalinter/tree/v3-unstable.

**Comment by alecthomas** [comment]
Another linter that would benefit from API integration: https://github.com/766b/godox

**Comment by liut0** [comment]
My first oss repo does implement more or less the use-cases described here: [gomultilinter](https://github.com/liut0/gomultilinter). If you are interested, have a look. I would appreciate any feedback.

**Comment by golangci** [comment]
take a look at https://github.com/golangci/golangci-lint: it does API based integration with dozens of linters.

@liut0 cool project, we've done similar tool; maybe we didn't build it if we'd found gomultilinter before.

**Comment by alecthomas** [comment]
@golangci nice! Your project is very new, but if you continue to maintain it, are able to upstream your changes, and continue to keep the linters up to date, I'd be happy to stop supporting gometalinter. It started as a side project, but it really needs more of a time commitment.

**Comment by golangci** [comment]
@alecthomas thank you!
