### ISSUE TITLE
redundant alias on import

### ISSUE THREAD

**Issue by aultimus** [alecthomas/gometalinter#381]
Is there any type of check that catches redundant alias in imports

ie. simplifies:
```
	assert "github.com/stretchr/testify/assert"
```

to 

```
	 "github.com/stretchr/testify/assert"
```

? 

Thanks

**Comment by alexkohler** [comment]
[I wrote a tool that catches these](https://github.com/alexkohler/unimport), but this is not currently included in gometalinter. If there's interest (given the blessing of @dnephin and @alecthomas), support could be added. In the meantime, you should be able to add it as a [custom linter](https://github.com/alecthomas/gometalinter#configuration-file).
