### ISSUE TITLE
Feature request: exclude patterns stored in a file

### ISSUE THREAD

**Issue by jmuk** [alecthomas/gometalinter#382]
We do have a file in our project -- called `generated_files` -- which lists the name of files which are generated automatically, so we want to exclude them for the linters. gometalinter seems to expect the exact pattern for `--exclude` flag, and there's no way to read the exclude patterns from a file, like `--exclude=@filename` (or `--exclude_file=filename`).

Apparently it's possible to make some shell tricks to read the file and expand the flags appropriately -- yet I think it's great if gometalinter natively support it.

**Comment by alecthomas** [comment]
Have you tried `--config`?

**Comment by jmuk** [comment]
oh, I didn't notice that. This should save my situation. Thanks!
