### ISSUE TITLE
New linter for detecting bad usage of time.Time

### ISSUE THREAD

**Issue by richardartoul** [alecthomas/gometalinter#383]
Hello,

My team ran into this issue recently upgrading to Go 1.9. We were using a lot of maps where the key was either a time.Time, or contained a nested time.Time.

Due to the changes to the internal representation of time.Time in Go 1.9, this becomes very dangerous and error-prone so we wrote a linter to auto-detect it.

The linter (along with a more detailed explanation) is here: https://github.com/m3db/build-tools/tree/master/linters/maptime

Is there any interest in mentioning this linter in the README? I could make a P.R

**Comment by flimzy** [comment]
broken (private?) link.

**Comment by richardartoul** [comment]
Sorry we renamed it (promise we won't do that again) because we expanded its functionality to also detect stuff like time.Time{} == time.Time{}

This link should work: https://github.com/m3db/build-tools/tree/master/linters/badtime

**Comment by richardartoul** [comment]
We ran it on our own codebases and it found a good number of real issues, as well as things that could have easily become bugs in the future

**Comment by ferhatelmas** [comment]
@richardartoul You might want to jump into discussion on [golang/go#22977](https://github.com/golang/go/issues/22977) and [golang/go#22978](https://github.com/golang/go/issues/22978)
