### ISSUE TITLE
Consider adding support for prealloc 

### ISSUE THREAD

**Issue by Starz0r** [alecthomas/gometalinter#385]
[prealloc](https://github.com/alexkohler/prealloc) seems like a pretty solid and stable linter to find places where declarations can be preoptimized .

**Comment by rliebz** [comment]
For those who are interested, you can use prealloc by adding this to your `.gometalinter.json`:
```json
{
  "Linters": {
    "prealloc": {
      "Command": "prealloc",
      "Pattern": "^(?P<path>.*?\\.go):(?P<line>\\d+)\\s*(?P<message>.*)$"
    }
  },
  "Enable": [
    "prealloc"
  ]
}
```

Just make sure you enable all the linters you are interested in rather than just `prealloc`.
