### ISSUE TITLE
If --config and --install are used together only install enabled linters

### ISSUE THREAD

**Issue by dnephin** [alecthomas/gometalinter#387]
Currently every linter with an `InstallFrom` field is installed when run with `--install`. 

This is a feature request to have `--install` read the config (if one is set with `--config`) and only install linters which are enabled in the config. As we add more linters to the default config this will become more important. 

This should be backwards compatible because `--install` without a config would still install every linter.

**Comment by flimzy** [comment]
I don't think this needs to be tied to `--config` in particular.  It should also follow that if one runs `gometalinter --install --disable-all --enable=foo`, it should only install foo.
