### ISSUE TITLE
Adding custom linters to config don't run them unless explicitly "Enabled"

### ISSUE THREAD

**Issue by johanbrandhorst** [alecthomas/gometalinter#388]
From what I can tell, adding a new linter to the `"Linters"` part of the `gometalinter` config does not add it to the linters that should be run. Instead, you have to also add it to `"Enabled"`, which unfortunately means that you have to explicitly enable _all_ linters you want. The problem with this is then that there's no way to automatically enable linters that are enabled in gometalinter updates.

Ideally adding a linter to `"Linters"` should add it to the default linters, so I don't have to explicitly enable it. I'd like to have both custom linters _and_ the ability to get new linters as they are added to gometalinter.

**Comment by sni** [comment]
+1
