### ISSUE TITLE
Staticcheck 2017.2

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#389]
https://github.com/dominikh/go-tools/releases/tag/2017.2

This is a new release. (today)
Maybe we could update the vendored linter.

**Comment by alecthomas** [comment]
Sure, send a PR and we'll merge it.

**Comment by pierrre** [comment]
OK, I'll try to do it tomorrow.

Actually there are less changes than I thought previously.
The vendored linters are already up to date (1-2 weeks old).
Changes https://github.com/dominikh/go-tools/compare/15d446f3efa09ffb7dc2745ae3086c3304250e78...0fc6318a0ec10493acdf6d3961880d23c5cbe6bb
So when I run `gvt`, it doesn't change much.

I thought that the tagged release was a more important change.
But gometalinter already follows the master branch.

**Comment by dominikh** [comment]
Personally, I'd love it if gometalinter tracked the releases instead of master. It gives users a more stable experience (no new checks that appear at random, no bugs that are on master), and they get a nice changelog whenever they update to a new version.

Releases will probably happen every 1-3 months, depending on the rate and importance of changes.

**Comment by pierrre** [comment]
I just submitted a PR.

I don't know well the `gvt` tool, but it doesn't seem to have a "manifest" file like `golang/dep`.
So, if someone run `gvt update -all`, it will not use the latest stable tag anymore.

**Comment by dnephin** [comment]
Changing to `dep` would be good, but it expects semver, and `2017.2` does not look like semver, so I'm not sure that it will actually work to pin to a specific major version.

**Comment by dlsniper** [comment]
> ` 2017.2 ` does not look like semver

That's major: 2017, minor: 2, patch: optional, excluded, 0. How is that not semver?

**Comment by alecthomas** [comment]
In semver, each version component has semantic meaning. That is where the "sem" in semantic comes from after all. Changes in the MAJOR component represent API breaking changes. In the case of honnef.co/go/tools there is no such guarantee, so a 2017.3 release could break API guarantees.

That's fine, but it's not semver.
