### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by alecthomas** [alecthomas/gometalinter#395]
@dnephin Further to our discussion about splitting up gometalinter into packages: obviously in principle I think this is a very good idea. To facilitate this, I suggest we move away from a `go get` model of distribution to a binary release model. We can continue to support binaries built from master, but also tagged, versioned releases. Thoughts?

**Comment by alecthomas** [comment]
It would need some way to build+distribute all of the linter binaries, and some form of packaging/installation, but I think the benefits in terms of architectural cleanliness will be worth it.

**Comment by alecthomas** [comment]
The code is actually brutally ugly, which shows its evolution from a quick command-line hack to what it is now :\, but I think it would be fantastic to clean it up.

**Comment by alecthomas** [comment]
See https://github.com/alecthomas/gometalinter/tree/packagify for a start.

**Comment by dnephin** [comment]
Sounds great!

**Comment by alecthomas** [comment]
I also propose we take the opportunity to break backwards compatibility and clean up the configuration format. There are some warts.
