### ISSUE TITLE
[Exit status]Can I set the Exit status just 0?

### ISSUE THREAD

**Issue by cyw3** [alecthomas/gometalinter#399]
What is the meaning below:
![image](https://user-images.githubusercontent.com/11549103/33377146-5ce89728-d54b-11e7-85e2-ab1391be5583.png)

Can I set the Exit status just 0? not 1, 2, 3 or the other.

**Comment by dnephin** [comment]
If there are no errors, the exit status will be 0.

If you want to ignore the exit status use `gometalinter || true`

**Comment by cyw3** [comment]
Actuallly, i occured the question below:
![image](https://user-images.githubusercontent.com/11549103/33379725-d573c476-d553-11e7-8092-816755441f50.png)

**Comment by dnephin** [comment]
Sorry, I don't understand what you're asking

**Comment by cyw3** [comment]
Actuallly, when i use gometalinter with the command below:

**gometalinter || true --enable-all --json --debug --concurrency=8 --cyclo-over=10 --line-length=80 --min-confidence=.80 --min-occurrences=3 --min-const-length=3 --dupl-threshold=50 --sort=path --enable-gc ./...**

I found low of result were:

**could not import google.golang.org/grpc (cannot find package \"google.golang.org/grpc\" in any of:**

and the exit status was 1.

Why would have this result. i think they were not the good result as gometalinter did not work.

**Comment by cyw3** [comment]
go version go1.9.2 darwin/amd64

**Comment by cyw3** [comment]
Besides, I wonder if some linter would return exist code '1' when the linter find the error it definded.

**Comment by alecthomas** [comment]
I'm sorry, I can't understand what problem you're having. If you can clarify, please reopen.
