### ISSUE TITLE
gotype linter doesn't work if a package is not installed in $GOPATH/pkg

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#40]
If a package is installed in `$GOPATH/src` but not in `$GOPATH/pkg`, the `gotype` linter fails:
```
image/encoder.go:48:52:error: undeclared name: imageserver (gotype)
```

**Comment by alecthomas** [comment]
There's very little I can do about that, it's the way gotype works... you should file a ticket with the gotype authors if you think this is an issue.

**Comment by pierrre** [comment]
Could you run `go install xxx` before `gotype`?
I don't know if it's a good idea...

**Comment by alecthomas** [comment]
I don't think that would be wise really.

**Comment by pierrre** [comment]
OK, I understand.
Thank you. :)

**Comment by gonzaloserrano** [comment]
Ouch! We just had this same problem.
