### ISSUE TITLE
Linting fails because link in comment is interpretted as symlink

### ISSUE THREAD

**Issue by alexparker215** [alecthomas/gometalinter#400]
I have the following comment in a go source file:
```
// Interface:
//    github.com/IBM-Bluemix/bluemix-cli-sdk/blob/master/plugin/plugin.go
```
However, linting fails with the following error:
```
WARNING: failed to resolve symlinks in //    github.com/IBM-Bluemix/bluemix-cli-sdk/blob/master/plugin/plugin.go: lstat /    github.com: no such file or directory
../../../../../../../    github.com/IBM-Bluemix/bluemix-cli-sdk/blob/master/plugin/plugin.go:1::warning: file is not gofmted with -s (gofmt)
```
I have tried innumerable variations, removing spaces, adding quotes around the link, etc., but I cannot find a way to make this pass linting. I don't understand how/why this is interpreted as a  symlink, but if there is a way to fix this or ignore this line, that would be great.

**Comment by dnephin** [comment]
I think what might be happening is that one of the regex in https://github.com/alecthomas/gometalinter/blob/master/linters.go#L205 is accidentally including the message as part of the path, then attempting to use that url as the path.

What version of gometalinter are you using?
You can use `gometalinter --debug` to see the full output. That should tell you which linter is creating the error message, so we'll know which regex is problematic.

**Comment by alecthomas** [comment]
Ping.

**Comment by alexparker215** [comment]
Sorry, I've been busy and neglected this. I will test it out in the next couple of days and report back. Thank you.
