### ISSUE TITLE
No version flag

### ISSUE THREAD

**Issue by Zamiell** [alecthomas/gometalinter#401]
```
C:\Users\Zamiell\go\src\github.com\Zamiell\hanabi-live>gometalinter --version
gometalinter: error: unknown long flag '--version', try --help
```

Virtually every command-line program has the `-v` / `--version` flag, so I think gometalinter should as well.

As an aside, it would also be nice if the output from this command would also show the version of all of the linters that gometalinter uses. Although that might be a little long/messy. *shrug*

**Comment by dnephin** [comment]
I think a version flag (including git sha) would be great.

Many of the linters do not have their own versions, so I'm not sure that part will work.

**Comment by alecthomas** [comment]
Yep, agreed. I am almost finished with the packaging script for release binaries. I will bake versioning into the script.

**Comment by alecthomas** [comment]
This is implemented. Release binaries will now include the version.
