### ISSUE TITLE
Feature request: Support for .gometalinterrc

### ISSUE THREAD

**Issue by Zamiell** [alecthomas/gometalinter#402]
Most linters have support for rc files.

E.g.
* Javascript - [jshint - .jshintrc](http://jshint.com/docs/)
* Javascript - [eslint - .eslintrc](https://eslint.org/docs/user-guide/configuring)
* Lua - [luacheck - .luacheckrc](http://luacheck.readthedocs.io/en/stable/config.html)
* Python - [pylint - .pylintrc](https://docs.pylint.org/en/1.6.0/run.html)
* Puppet - [puppet-lint - .puppet-lintrc](https://github.com/rodjek/puppet-lint)
* and so on

So I'm extremely surprised to see this feature missing in gometalinter. Why is this important? Because people want/need to have different linting rules per code repository.

It is common practice to specify all the linting rules for a project to a .gometalintrc file, and keep it in revision control (git) at the root of the repository.

And then peoples code editors automatically use the rc file at
```
/home/Zamiell/go-project/.gometalinterrc
```
when editing the file
```
/home/Zamiell/go-project/src/models/poop.go
```
And this is handled seamlessly because because the linter handles loading the config from the correct place.

(I'm aware that you can manually specify a file to read arguments from by using the clunky "@file" syntax, but the point of having an rc file is that the linter will **automatically use it without having to specify**.)

<br />

### Implementation Details

What is the logic for finding a `.gometalinterrc` file? Well, typically, linters will start by looking for it in the same directory as the go source code file, and then look a directory above that, and then a directory above that, and so forth. And then, as a last resort, it will look in `~/.gometalinterrc` (the home directory).

Source: the eslint/jshint docs that I linked above.

**Comment by dnephin** [comment]
`gometalinter` already supports a JSON config file.  The main differences seem to be there is no default path, you have to specify the path with a flag. Does that sound right?

I wouldn't mind having a default path for the config file.

**Comment by Zamiell** [comment]
Yes, a JSON config file is file. To be clear, the format of the file is not important. The important part is that it is loaded automatically, per project.

**Comment by rliebz** [comment]
I'm not sure that there's a sane way to load a config file automatically per project—it may have to be done on a path-by-path basis.

Consider the following directory structure:

```
main.go
foo/
  .gometalinterrc
  foo.go
```

Running the following would produce different results:

```bash
# Uses .gometalinterrc for foo.go
cd foo && gometalinter

# Does not use .gometalinterrc for foo.go
gometalinter ./...

# Maybe uses .gometalinterrc for foo.go (depending on implementation)
gometalinter ./foo
gometalinter foo/foo.go
```

I imagine this may cause problems when opening the file in an editor, where you could get different results based on which directory you open, or whether it's a file or package being linted. 

There may also be multiple valid `.gometalinterrc` files for a given execution if multiple paths are passed to `gometalinter`.

[The way `eslint` seems to handle this](https://eslint.org/docs/user-guide/configuring#using-configuration-files) looks pretty sane—each file to be linted gets its own configuration. This means that for a simple project with one `.gometalinterrc` at the root, everything would share a config, but there would be less ambiguity and better support for granular controls if you need them.

**Comment by dnephin** [comment]
> Consider the following directory structure:

That directory structure doesn't make any sense. The config file needs to be at the root of the project. If you want to put the config somewhere else you can always use `--config`.

> each file to be linted gets its own configuration ... less ambiguity and better support for granular controls if you need them.

It's also a lot more complexity to maintain, for what I would consider a very rare use case. If you  want different linter rules for different paths you can always script that yourself. The common case is to use a single config for the entire project. 

I think the most common way of finding the "defualt config" is to use the same rules as `.git`. Look for a file in the cwd, then look in the parent dir, and continue until you find something.

**Comment by rliebz** [comment]
If you're okay with coupling the default config file to the working directory instead of the directory of the files being tested, I've actually basically got an implementation for that written up, minus tests, that I'd be happy to make a PR out of. 

I would hope no one would structure their code like that—I mostly posted the above because when I looked into implementing this, those were the ambiguities I consisted from an implementation perspective. Making the working directory significant, even when passing absolute paths, solves it as well.

**Comment by dnephin** [comment]
A PR with that behaviour would be great, thanks!

**Comment by Zamiell** [comment]
Why break linter convention by appending a .json to the file name? This is unlike any other linter that I've seen.

**Comment by alecthomas** [comment]
The rationale is explained in the PR comments.

**Comment by Zamiell** [comment]
Are you referring to this?

> I hate to bikeshed the name, but... what do others thing about .gometalinter.json instead?
> I have a preference for using the format file extension. It would make it easier to support yaml, toml or some other format if we wanted to in the future.

It is a bit weird since it breaks linter convention. It could be potentially confusing for new gometalinter users who will name their rc file without an extension by default.

If gometalinter wants to support YAML in the future, could it just dynamically find out what the file type is via the following algorithm?

1) Try to parse JSON
2) If fail, try to parse YAML
3) If fail, try to parse TOML
etc.

**Comment by rliebz** [comment]
Actually [eslint has deprecated rc files without an extension](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) in favor of being explicit. [Other linters like rubocop](https://rubocop.readthedocs.io/en/latest/configuration/) also have config files with extensions, so I don't think it's fair to say there is a linter convention. What this syntax does provide is a more explicit way to support different config formats and automatic syntax highlighting for editors that pick up on that stuff.

Even if a large number of linters stick to the `rc` suffix, I would argue that the gometalinter config file has as much in common as go tool config files like [dep (Gopkg.toml)](https://github.com/golang/dep) and [goreleaser (.goreleaser.yml)](https://github.com/goreleaser/goreleaser) as it has in common other linters, and I haven't seen many go configurations with the `rc` extension.

There's certainly valid arguments to use `rc`, but I really think it ends up boiling down to preference here.

**Comment by Zamiell** [comment]
Ok, that's interesting; I didn't know that the format was deprecated in eslint, which is seems to be one of the most popular linters, if not the most popular.
