### ISSUE TITLE
gometalinter v2: installing linters does not work when gopkg.in is used

### ISSUE THREAD

**Issue by fho** [alecthomas/gometalinter#404]
Hello,

I'm using gopkg.in to install gometalinter via:
-  `go get -v -u gopkg.in/alecthomas/gometalinter.v2`

That works but when I try to install the linters  via` gometalinter.v2 --install` it fails with: 
`gometalinter.v2: error: could not find vendored linters in GOPATH="/home/fho/go"`

When I install gometalinter via `go get -u github.com/alecthomas/gometalinter`,
`gometalinter --install` works like expected

**Comment by dnephin** [comment]
Thanks for the bug report!

#405 will fix it, once it's tagged.

A workaround is to move it to `/go/src/github.com/alecthomas/gometalinter` or a symlink might work as well.

**Comment by alecthomas** [comment]
@fho please note that this method of installation will be cease to work soon; the blessed approach is to use release binaries from [here](https://github.com/alecthomas/gometalinter/releases)

**Comment by fho** [comment]
@alecthomas the provided binaries don't work for our usecase.
We run gometalinter on a system that uses musl libc, the binaries are linked against glibc.

**Comment by alecthomas** [comment]
We'll have to provide a script or makefile for installing the linters, for cases such as yours.

**Comment by fho** [comment]
Maybe it would also be possible to compile the binaries with `CGO_ENABLED=0` environment variable set, then they wouldn't require a specific libc version
