### ISSUE TITLE
megacheck is automagic

### ISSUE THREAD

**Issue by hasufell** [alecthomas/gometalinter#412]
This is *not* expected behavior when I set e.g.

```json
{
    "Enable": ["vet", "golint", "staticcheck", "unused", "gosimple"]
}
```

If I want megacheck, then I will add megacheck to that list instead of staticcheck, gosimple and unused. Megacheck also has the disadvantage that I don't really see what linter found what issue.

**Comment by alecthomas** [comment]
The other linters are deprecated and will be removed completely at some point. This is the intermediate stage.
