### ISSUE TITLE
check for shadowing of predeclared identifiers

### ISSUE THREAD

**Issue by nishanths** [alecthomas/gometalinter#417]
Go defines 39 [predeclared identifiers](https://golang.org/ref/spec#Predeclared_identifiers). These identifiers can be shadowed in user-written Go code.

```
Types:
	bool byte complex64 complex128 error float32 float64
	int int8 int16 int32 int64 rune string
	uint uint8 uint16 uint32 uint64 uintptr

Constants:
	true false iota

Zero value:
	nil

Functions:
	append cap close complex copy delete imag len
	make new panic print println real recover
```

## Example

Consider a file:

```
package main

type T struct {
	x, y int
	s string
}

func main() {
	a := []T{{x: 0}, {x: 1}, {x: 2}}
        print(a[1])
	b := make([]T, 3)
	copy(b, a)
}
```

And another file in the same package with these definitions:

```
package main

// order of src and dst is switched from the builtin copy!
func copy(src, dst []T) {
	for i := range dst {
		if i == len(src) {
			break
		}
		string := src[i].s
		dst[i].s = string
	}
}

// not the builtin print as expected!
func print(t T) { log.Printf("{ x=%d, y=%d }", t.x, t.y) }
```

Most Go programmers would expect that the `copy` and `print` used in the first file are the builtin `copy` and `print` functions. Shadowing them adds confusion and cognitive overhead. So check for declarations that shadow the predeclared identifiers. 

See #416.

**Comment by alecthomas** [comment]
We will add predeclared as one of the first candidates for integration via #380.
