### ISSUE TITLE
Update README w/ install instructions for v2.0

### ISSUE THREAD

**Issue by zmb3** [alecthomas/gometalinter#418]
I see the release notes for v2.0 mention that the new direction is to release binaries (including bundled linters).

What’s not clear to me is how this change impacts the recommended way to install gometalinter.  Is `go get` going to be deprecated?  Should we just download the binaries and place them on our `$PATH`?  Does the linters directory also need to be in the path or is gometalinter smart enough to look there for tools to exec?

It would be nice if we could update the install and quick start sections of the README to reflect the latest recommendations.

**Comment by alecthomas** [comment]
Yes, good call.

**Comment by amimas** [comment]
Please post the new instructions? Also, would you be able to include how to install this using Gradle? I'm using Gradle for build process using following gogradle plugin.

https://github.com/gogradle/gogradle

I'd like to include gometalinter into the overall build process. But, not sure how to set it up. In our CI/CD process, I won't have access to "install" this on the build machines. Even golang is being setup by the build process using gogradle in a temporary location.

**Comment by alecthomas** [comment]
@amimas I can't provide instructions on how to install gometalinter with every CI, that is impractical.

**Comment by amimas** [comment]
Definitely agree that it's impractical to provide instructions for every CI. I mentioned about Gradle because that's a very robust build tool than Ant or Maven. It's not necessarily CI.

Maybe I'll be able to figure out how to use it with Gradle once the updated instructions for v2 is available. Thanks

**Comment by rliebz** [comment]
Having a small shell script [like goreleaser is using](https://github.com/goreleaser/get) would go a long way without having to cater to any specific CI.

**Comment by mrmark** [comment]
Hopefully this is helpful, https://github.com/goreleaser/godownloader

Also, IIRC, goreleaser makes it easy to make and automatically update a homebrew tap repository, if interested.  That way folks can use homebrew to automatically install and keep things up-to-date easily.

**Comment by alecthomas** [comment]
I did look at `goreleaser` but had some issues with environment variables. I have subsequently made it work, so I'll switch to that soon.

`godownloader` looks interesting, but doesn't support multiple binaries :(

**Comment by alecthomas** [comment]
https://github.com/goreleaser/goreleaser/issues/540#issuecomment-362870152

**Comment by gudvinr** [comment]
That's very sick. So now it's recommended to use precompiled binaries BUT there's no generic instructions for installation and usage.
And how we are supposed to use it? Go tooling was always easy to use as "copy-paste & go" and now metalinter became opposite of that.

**Comment by alecthomas** [comment]
@gudvinr The old way still works fine, but thanks for your constructive input.

**Comment by gudvinr** [comment]
@alecthomas Thanks for the reply.
Yes, it definetely works fine _for now_ but since this is deprecated way to install I guess it will be eliminated in future. So people think that newer way should be used whenever possible.

I'm sorry that my response sounds rude a bit. But to be honest it's really annoying that one should digging into setup process of tools that supposed to make development process easier.

**Comment by alecthomas** [comment]
There will be instructions added once there's an automated solution. Until then you can continue to use the instructions in the README.

**Comment by flyinprogrammer** [comment]
for those who might want a godownloader script - i used the generator and then hacked it. which i realize is bad practice, but yeah.

https://github.com/flyinprogrammer/godownloaders/blob/master/download_gometalinter.sh#L52-L58

**Comment by wknapik** [comment]
The simplest hack, if you need one:
```
curl -sLo- https://github.com/alecthomas/gometalinter/releases/download/v2.0.5/gometalinter-2.0.5-linux-amd64.tar.gz|tar -xzC "$GOPATH/bin" --exclude COPYING --exclude README.md --strip-components 1 -f-
```

**Comment by autarch** [comment]
@alecthomas 
> godownloader looks interesting, but doesn't support multiple binaries :(

It does now. See the discussion in https://github.com/goreleaser/godownloader/issues/52

**Comment by alecthomas** [comment]
@autarch That's awesome, though it looks like there are still a couple of kinks. Once those are fixed I'll make a downloader available. Thanks for creating that issue BTW.

**Comment by konradreiche** [comment]
Is there a way to always download the latest release of the binary package? Due to the version encoding in the file name I wouldn't know how.

**Comment by alecthomas** [comment]
goreleaser/godownloader now both support multiple binaries. I've added the script. Please test with:

```bash
$ export BINDIR=<directory-in-your-$PATH>
$ curl https://raw.githubusercontent.com/alecthomas/gometalinter/master/scripts/install.sh | bash
```
