### ISSUE TITLE
100% CPU & Memory Usage

### ISSUE THREAD

**Issue by azer** [alecthomas/gometalinter#427]
Hey there,

I tried running gometalinter in bunch of repositories, and mostly got my computer freezed. I run Linux on Macbook Air (1.70GHz / 8GB Ram).

Looking at the issue history, there aren't any other complaints. Am I doing something wrong ?

**Comment by dnephin** [comment]
This has happened to me on occasionally as well. I usually run in a Docker container, but I'm not sure if that matters.

I usually fix it by setting a concurrency to a much smaller value with `-j 2`. The default value is the number of CPUs, which I think can be a problem sometimes.

**Comment by alecthomas** [comment]
Part of the problem, I believe, is that some linters will also parallelise themselves. I know at least megacheck does this. This can result in NxN (N=number of cores) concurrent linters executing.

**Comment by dnephin** [comment]
That makes sense. Probably something we should document for the new #380 interface, that linter implementations are expected to only run a single goroutine.

**Comment by alecthomas** [comment]
I've forced `GOMAXPROCS=1` for sub-linters. That should "solve" this problem for now. I've also removed the disabling of GC.
