### ISSUE TITLE
How to use gometalinter in Goland

### ISSUE THREAD

**Issue by doubliekill** [alecthomas/gometalinter#428]

**Comment by doubliekill** [comment]
Seems not support in Goland

**Comment by dnephin** [comment]
It seems to be available as Settings -> File Watchers. What isn't working?

**Comment by alecthomas** [comment]
https://blog.jetbrains.com/go/2017/10/18/gogland-eap-16-file-watcher-tons-of-new-inspections-smarter-navigate-to-test-and-more/
