### ISSUE TITLE
Gas errors appear to be not be picked up

### ISSUE THREAD

**Issue by alexkohler** [alecthomas/gometalinter#429]
Perhaps I'm missing something, but I'm running into a bit of an issue where I can't get `gas` errors to show up. (This was found while working on an issue for status-go)

Suppose I have main.go:
```Go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Fprintf(os.Stderr, "go")
}
```

When I run gas:

```Bash
$ $ gas .                                                                                                                                                                                 
[gas] 2018/01/31 12:53:35 including rules: default
[gas] 2018/01/31 12:53:35 excluding rules: default
[gas] 2018/01/31 12:53:35 Searching directory: /home/alex/workspace/gasTest
[gas] 2018/01/31 12:53:35 Checking package: main
[gas] 2018/01/31 12:53:35 Checking file: /home/alex/workspace/gasTest/main.go
Results:

[/home/alex/workspace/gasTest/main.go:9] - Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > fmt.Fprintf(os.Stderr, "go")


Summary:
   Files: 1
   Lines: 10
   Nosec: 0
  Issues: 1

```

When I run gometalinter:

```Bash
$ gometalinter.v2 --no-config --disable-all --enable=gas --debug . 
DEBUG: GOPATH=/home/alex/workspace/gasTest
DEBUG: GOBIN=/home/alex/go/bin
DEBUG: linting path .
DEBUG: [gas.1]: executing /home/alex/go/bin/gas -fmt=csv main.go
DEBUG: [gas.1]: warning: /home/alex/go/bin/gas returned exit status 1: [gas] 2018/01/31 12:53:47 including rules: default
[gas] 2018/01/31 12:53:47 excluding rules: default
[gas] 2018/01/31 12:53:47 Searching directory: /home/alex/workspace/gasTest/main.go
[gas] 2018/01/31 12:53:47 readdirent: not a directory

DEBUG: [gas.1]: gas hits 0: ^(?P<path>.*?\.go),(?P<line>\d+),(?P<message>[^,]+,[^,]+,[^,]+)
DEBUG: [gas.1]: gas linter took 120.854751ms
DEBUG: total elapsed time 131.216646ms
```

It appears that we're giving gas ` /home/alex/workspace/gasTest/main.go` as a directory, which it does not like. This can be reproduced by feeding gas the same file: 
```Bash
$ gas gasTest/main.go 
[gas] 2018/01/31 13:01:27 including rules: default
[gas] 2018/01/31 13:01:27 excluding rules: default
[gas] 2018/01/31 13:01:27 Searching directory: /home/alex/workspace/gasTest/main.go
[gas] 2018/01/31 13:01:27 readdirent: not a director
```

**Comment by dnephin** [comment]
This was changed to use files in #392, which includes a test case.  Looking at the source for the version we have in `_linters` (https://github.com/GoASTScanner/gas/blob/f22c701483ba201fbdb79c3667a28ef6a4e4a25c/main.go#L254-L260) files should be fine.  I tried locally and I can't reproduce your issue.

What version of `gas` are you using?

There are a lot of changes upstream that haven't been vendored here yet. It seems the args have changed to accept packages or directories. Updating the vendored copy in `_linters` and changing the `partitionStratetgy` would allow it to work with the latest changed.

**Comment by alecthomas** [comment]
No rseponse. We can reopen if this is an issue.

**Comment by alexkohler** [comment]
@dnephin @alecthomas Sorry guys, thought I’d replied to this! It ended up being an old version of gas, updating did the trick.

**Comment by joshuarubin** [comment]
Would love to see this get updated to the latest version of gas
