### ISSUE TITLE
Would like to pass -local option to goimport

### ISSUE THREAD

**Issue by geeknoid** [alecthomas/gometalinter#431]
We format our source code with goimports -local XXX, so it'd be great to be able to pass the same option to gometalinter so it can validate our intended format.

Thanks.

**Comment by dnephin** [comment]
Good news, you can!

Using a config file:

```json
{
  "Linters": {
    "goimports": {"Command": "goimports -l --local xxx"}
  }
}
```

**Comment by geeknoid** [comment]
Excellent, it worked great.

Thanks!
