### ISSUE TITLE
Question around custom gas config

### ISSUE THREAD

**Issue by alexkohler** [alecthomas/gometalinter#432]
Hey guys, I've been trying to write a custom gas configuration and am running into a bit of trouble with the pattern. I've started by specifying the exact same pattern that's in linter.go in my configuration file:

Here is the gas entry for linters.go
```go
"gas": {
	Command:           `gas -fmt=csv`,
	Pattern:           "^(?P<path>.*?\.go),(?P<line>\d+),(?P<message>[^,]+,[^,]+,[^,]+)",
	InstallFrom:       "github.com/GoASTScanner/gas",
	PartitionStrategy: partitionPathsAsDirectories,
	defaultEnabled:    true,
	IsFast:            true,
},
```

Here is my configuration: 
```json
"Linters": {
    "gasv2": {
     "Command": "gas",
     "Pattern": "^(?P<path>.*?\\.go),(?P<line>\\d+),(?P<message>[^,]+,[^,]+,[^,]+)"
     }
},
```
(note that I had to double escape the backslashes - near .go and d+).

When I run this, I can't seem to get any matches:
```Bash
gometalinter --enable=gas geth/log/
DEBUG: [gasv2.1]: gasv2 hits 0: ^(?P<path>.*?\.go),(?P<line>\d+),(?P<message>[^,]+,[^,]+,[^,]+)`
```

When I run the regular gas command I'm able to get output, **and it looks like it's running the same regex**:
```
gometalinter --no-config --debug --disable-all --enable=gas geth/log/
DEBUG: [gas.1]: gas hits 1: ^(?P<path>.*?\.go),(?P<line>\d+),(?P<message>[^,]+,[^,]+,[^,]+)
```

Any ideas where I might be going wrong here? Thanks guys :+1:

**Comment by dnephin** [comment]
You'll need `-fmt=csv` otherwise the output format will be the default, which is text.

**Comment by dnephin** [comment]
Going to close this issue, but feel free to comment if that doesn't work.

**Comment by alexkohler** [comment]
@dnephin oops that did it - thank you!
