### ISSUE TITLE
Can not work based golang 1.9

### ISSUE THREAD

**Issue by LgxAtGitHub** [alecthomas/gometalinter#433]
On golang 1.9.2, my project work well, but when I do check by gometalinter, I got much error like: 
```
... error: could not import time (reading export data: /usr/local/tmp/go/pkg/linux_amd64/time.a: invalid encoding format in export data: got 'v'; want 'c' or 'd') (gotype)
... error: undeclared name: time (gotype)
```
and on golang 1.7.5, everything work well

What's wrong?

**Comment by alecthomas** [comment]
Have you reinstalled gometalinter with Go 1.9.2?

**Comment by alecthomas** [comment]
(and the linters)

**Comment by LgxAtGitHub** [comment]
How to reinstall gometalinter?
I executed ```go get -u gopkg.in/alecthomas/gometalinter.v2```, that's right?

**Comment by LgxAtGitHub** [comment]
ah...

I found the reason, old linters in my path, there have old linter.
My make mistake, I will cllose this issue.
Thanks
