### ISSUE TITLE
How do I output a short path?

### ISSUE THREAD

**Issue by dxvgef** [alecthomas/gometalinter#437]
I get a output like this:
`{GOPATH}/{ProjectPath}/***/***.go:3:1:warning: comment on exported type Share should be of the form "*** ..." (with optional leading article) (golint)`

But i want get a short path, like this:
`***/***.go:3:1:warning: comment on exported type Share should be of the form "*** ..." (with optional leading article) (golint)`

How should I do it?

**Comment by alecthomas** [comment]
gometalinter attempts to do this automatically. Are you using symlinks somewhere, odd GOPATH usage? Can you provide a reproducible example?

**Comment by eaglemoor** [comment]
@dxvgef you need run gometalinter from project path. For example if you use GoLand:

<img width="701" alt="screen shot 2018-03-10 at 04 47 33" src="https://user-images.githubusercontent.com/1461295/37236945-3cccffc0-241e-11e8-8ecb-dad24149d17a.png">
