### ISSUE TITLE
Support for abcgo

### ISSUE THREAD

**Issue by Slach** [alecthomas/gometalinter#440]
Could gometalinter support
https://github.com/droptheplot/abcgo ?

**Comment by alecthomas** [comment]
IIUC ABC is an alternative to LOC. Is that correct? If so, that doesn't seem useful for a linter to report as it's not something you can "fix" per se. What did you have in mind?

In the meantime, you can add a [custom linter](https://github.com/alecthomas/gometalinter#adding-custom-linters) yourself.

**Comment by alecthomas** [comment]
Perhaps, but it would need to add something akin to `gocyclo`'s `-over` flag.
