### ISSUE TITLE
Bundle newer version of deadcode

### ISSUE THREAD

**Issue by ferhatelmas** [alecthomas/gometalinter#441]
Actual code of deadcode lives in [remyoudompheng/go-misc](https://github.com/remyoudompheng/go-misc) and has fixes.

Could we bundle a newer version ?

**Comment by SimonRichardson** [comment]
@alecthomas I've got a PR open to update the https://github.com/tsenart/deadcode/pull/10, but nothing is happening and the original upstream has features that make deadcode a lot more useful. Including checking if tests are using the code in question... 

I think we should either setup and use a fork (I'm not a fan, as we may up with a stale linter again) or we use the original upstream source, what do you think?
