### ISSUE TITLE
gas has moved to github.com/GoASTScanner/gas; update vendored version

### ISSUE THREAD

**Issue by wrouesnel** [alecthomas/gometalinter#445]
This repository seems to have been updated, and the correct install path is now `github.com/GoASTScanner/gas/cmd/gas` in order to build the binary.

**Comment by alecthomas** [comment]
Note that this should not impact installation of gas if you're using the bundled version. We do this specifically to avoid issues like this.

That said, we should update our vendored version at some point to point to the new location.
