### ISSUE TITLE
building from source gives ambiguous version

### ISSUE THREAD

**Issue by zramsay** [alecthomas/gometalinter#446]
given:
```
git checkout master
git pull origin master
go install
gometalinter --version
```
I get:
```
gometalinter version master built from ? on
```
commit: 39a4757a714702004d3fdca45ff83af4dc484af9

I see that the previous commit was meant to fix `--version` but that assumes one is downloading the pre-built binary. Building from source should give the correct version (with commit)

**Comment by alecthomas** [comment]
That is not possible unless you set build options yourself.

**Comment by alecthomas** [comment]
Sorry, closed it before I finished commenting.

The version is designed for binary releases only. Additionally, what you suggest is not possible as the version is set [by the compiler](https://www.atatus.com/blog/golang-auto-build-versioning/).

**Comment by antnsi** [comment]
Sorry, I'm getting same with latest 2.0.5 release, not built myself. 
I probably didn't get answer, but shouldn't it be set manually (or `by goreleaser.`) for release builds?
```
go get -u gopkg.in/alecthomas/gometalinter.v2
gometalinter.v2 --version
gometalinter version master built from ? on
```

**Comment by alecthomas** [comment]
That is not a binary release, that is built from source. If you download the 2.0.5 release from the GitHub [releases](https://github.com/alecthomas/gometalinter/releases) and run it you will see the following:

```
$ ~/Downloads/gometalinter-2.0.5-darwin-amd64/gometalinter --version
gometalinter version 2.0.5 built from 46cc1ea3778b247666c2949669a3333c532fa9c6 on 2018-02-16T02:07:49Z
```
