### ISSUE TITLE
govet is no longer installable

### ISSUE THREAD

**Issue by autarch** [alecthomas/gometalinter#447]
```
$> go get -u github.com/dnephin/govet
package github.com/dnephin/govet: no Go files in /home/autarch/go/src/github.com/dnephin/govet
```

This means that it's impossible to use the `govet` command if you want to manage the installation of linters on your own.

**Comment by dnephin** [comment]
Sorry about that. The code is on the `fork` branch, and I forgot to set that as the default branch in github.

It should be fixed now. Please try again.

**Comment by autarch** [comment]
Yep, I was aware of #436, but the only way to do that right now is to fork gometalinter, which I'd rather avoid.

**Comment by dnephin** [comment]
You don't need to fork. You can do it with a config file which sets the vet command:

```json
{
  "Linters": {
    "vet": {"Command": "go vet"}
  }
}
```

**Comment by dnephin** [comment]
Going to close this since the fork should be installable now with `go get`.
