### ISSUE TITLE
Gas linter b0rken in latest release

### ISSUE THREAD

**Issue by wknapik** [alecthomas/gometalinter#448]
It seems `gas` no longer works, at least with the latest gometalinter release for Linux.

* If I run `gas ./...` using the binary installed with `gometalinter --install` ~a while ago, it works fine~ it fails the same way, as the binary shipped with the latest release (see: below)
* If I run `gas ./...` using the binary installed with `go get -u github.com/GoASTScanner/gas/cmd/gas`, it works fine
* If I run `gas ./...` using the binary from the latest gometalinter release, I get a screenful of errors of the form
```
Processing "<file>"...
Error during type checking: "<file>:<line>:<col> could not import <import> (can't find import: "<import>")"
```
* If I run `gometalinter --disable-all -E gas ./...` using the latest gometalinter release (regardless of whether `gas` comes from the gometalinter release package, or is installed using `go get`), there is no output at all and the exit code is 0

For information - I install the release using:
```
curl -sLo- https://github.com/alecthomas/gometalinter/releases/download/v2.0.5/gometalinter-2.0.5-linux-amd64.tar.gz|tar -xzC "$GOPATH/bin" --exclude COPYING --exclude README.md --strip-components 1 -f-
```

This is a pretty major issue IMO.

I was hoping to switch to official releases finally (after using a frozen clone of the official repo as a workaround for a few months), but when the number of warnings suddenly dropped with the new release, I looked deeper and there it is.

(one issue that might be related is #445, but I think this goes beyond that, because gas just doesn't work with gometalinter anymore, no matter how you install it)

**Comment by wknapik** [comment]
This was tested on Linux, with go 1.8.3 and 1.10.

**Comment by alecthomas** [comment]
Can you try setting GOROOT and trying again?

**Comment by wknapik** [comment]
GOROOT was already explicitly set.

**Comment by wknapik** [comment]
I just tested this with go 1.8.7, 1.9.4 and 1.10.0 (both on my host system and using the official golang docker containers) - the only `gas` binary that works is the one installed via `go get -u github.com/GoASTScanner/gas/cmd/gas`. Binaries installed via `gometalinter --install`, or shipped with the latest gometalinter release all have the same issues - not finding imports.

**Comment by alecthomas** [comment]
To be clear, gas *does* work with `gometalinter --install`, but it appears it does *not* work for you for some reason. There are regression tests that verify that each linter works. These are run in CI. ie. This is not a general problem.

Are you sure that the `gas` being installed with `--install` is the one being used by gometalinter? ie. $GOPATH/bin is first in your $PATH?

eg.

```
[aat@cavern:~/Projects/kingpin]gometalinter --disable-all -E gas .
guesswidth_unix.go:31::warning: Use of unsafe calls should be audited,LOW,HIGH (gas)
```

The regression tests can be run with `go test -v ./regressiontests` from the root of the source.

Also try running with `--debug` (as the [CONTRIBUTING](https://github.com/alecthomas/gometalinter/blob/master/CONTRIBUTING.md) file suggests).

**Comment by wknapik** [comment]
> To be clear, gas does work with `gometalinter --install`, but it appears it does not work for you for some reason. There are regression tests that verify that each linter works. These are run in CI. ie. This is not a general problem.

Well, I for one, am glad we cleared that up.

> Are you sure that the `gas` being installed with `--install` is the one being used by gometalinter?

$GOPATH/bin is the first path in my $PATH and there is no executable called gas in any of the other paths.

> Also try running with `--debug` (as the [CONTRIBUTING](https://github.com/alecthomas/gometalinter/blob/master/CONTRIBUTING.md) file suggests).

Will do.

This may very well be an issue on my end, but if so, it's nothing obvious. If I get to the bottom of it, I'll post an update. Feel free to resolve this, if you like.

**Comment by alecthomas** [comment]
I'd be very interested in finding out what the problem is if you get to the bottom of it, thanks.

**Comment by taybin** [comment]
I just saw this happen today.
