### ISSUE TITLE
No way to exclude vendor dir in latest release

### ISSUE THREAD

**Issue by wknapik** [alecthomas/gometalinter#449]
```
$ curl -sLo- https://github.com/alecthomas/gometalinter/releases/download/v2.0.5/gometalinter-2.0.5-linux-amd64.tar.gz|tar -xzC "$GOPATH/bin" --exclude COPYING --exclude README.md --strip-components 1 -f-
$ cd /path/to/checkout
$ cd subcomponent
$ gometalinter -j1 --vendor -s some_dir -s ../../checkout_root/vendor -s vendor -s ../vendor -s /absolute/path/to/vendor --deadline 900s --disable-all -E dupl -E errcheck -E gosimple -E ineffassign -E misspell -E safesql -E staticcheck -E vet -E vetshadow ./...
../vendor/golang.org/x/net/http2/go19.go:14:2:warning: error return value not checked (invalid operation: s (variable of type *net/http.Server) has no field or method RegisterOnShutdown) (errcheck)
../../checkout_root/vendor/golang.org/x/net/http2/go19.go:14:2:warning: error return value not checked (invalid operation: s (variable of type *net/http.Server) has no field or method RegisterOnShutdown) (errcheck)
../../checkout_root/vendor/golang.org/x/net/http2/go19.go:14:2:warning: invalid operation: s (variable of type *net/http.Server) has no field or method RegisterOnShutdown (gosimple)
../vendor/golang.org/x/net/http2/go19.go:14:2:warning: invalid operation: s (variable of type *net/http.Server) has no field or method RegisterOnShutdown (staticcheck)
$
```
As you can see, I've tried every conceivable way to exclude the vendor dir, but it still gets included.

I'm using go 1.8.3 on Linux / x86_64. The release I used above is 2.0.5.

**Comment by dnephin** [comment]
`--vendor` and `--skip path` tells `gometalinter` to never execute a linter with any path in the vendor directory, but `gometalinter` has no way of ensuring that a linter doesn't load those packages (when they are called with some other path).

I'm not sure why these linters are including `../vendor`, but it may have something to do with the your GOPATH. You can try `CGO_ENABLED=0`, if I remember correctly that can something cause issues.

You can tell `gometalinter` to ignore these errors with `--exclude ../vendor`.

**Comment by wknapik** [comment]
Hi @dnephin. Thanks for the quick response.

My `GOPATH="$HOME"` and there's nothing weird going on in that string (spaces, utf characters, length, etc.). `CGO_ENABLED=0` didn't change anything, but `--exclude ../vendor` did, indeed, remove the warnings for files in `vendor`, which is nice, but I was more concerned with the performance impact of linting `vendor`, than the results being included.

Unless you have any other suggestions for preventing the linters from entering the vendor directory, I suppose this issue can be closed, though I think all gometalinter users would appreciate it, if you guys investigated why this is happening and possibly fixed it - there's potentially a lot of time/resources that could be saved here.

**Comment by dnephin** [comment]
Yes, this could use more investigation. I've encountered this myself once or twice, but it was a while ago, and I was under the impression the issue had been resolved (#315 fixed part of it). Do you have the same problem with go1.9 and go1.10 ?

I don't think this is affecting most users. There's something about specific environments that confuse some linters and causes this problem.  You can run with `--debug` to get more information. If you want to post a log here I can look over it and see if I notice anything.

**Comment by wknapik** [comment]
Interesting - after installing go 1.10, there are no reports for files in the vendor directory, but the analysis seems to take quite a bit longer.

**Comment by alecthomas** [comment]
Can you try explicitly setting `GOROOT` to the location of your 1.9 installation?

**Comment by wknapik** [comment]
Ok, here's how I compared the results for go 1.8, 1.9 and 1.10.

My $GOPATH happens to be equal to $HOME and my $PWD when calling docker is the top of my checkout, within the $HOME tree.

Go 1.8.7 (10s)
```
$ time docker run --rm -it -v "$HOME:$HOME" -w "$PWD/subcomponent" -e "HOME=$HOME" -e "GOROOT=/usr/local/go" -e "GOPATH=$HOME" -e "PATH=$HOME/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -u "$(id -u):$(id -g)" golang:1.8.7-stretch gometalinter -j1 --vendor -s integration-test --deadline 900s --disable-all -E dupl -E errcheck -E gas -E gosimple -E ineffassign -E misspell -E safesql -E staticcheck -E vet -E vetshadow ./...
# results include ONLY the vendor directory
0,06s user 0,02s system 0% cpu 10,875 total
$
```
Go 1.9.4 (47s)
```
$ time docker run --rm -it -v "$HOME:$HOME" -w "$PWD/subcomponent" -e "HOME=$HOME" -e "GOROOT=/usr/local/go" -e "GOPATH=$HOME" -e "PATH=$HOME/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -u "$(id -u):$(id -g)" golang:1.9.4-stretch gometalinter -j1 --vendor -s integration-test --deadline 900s --disable-all -E dupl -E errcheck -E gas -E gosimple -E ineffassign -E misspell -E safesql -E staticcheck -E vet -E vetshadow ./...
# results do NOT include the vendor directory and are identical to those for go 1.10.0
0,06s user 0,02s system 0% cpu 47,667 total
$
```
Go 1.10.0 (46s)
```
$ time docker run --rm -it -v "$HOME:$HOME" -w "$PWD/subcomponent" -e "HOME=$HOME" -e "GOROOT=/usr/local/go" -e "GOPATH=$HOME" -e "PATH=$HOME/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -u "$(id -u):$(id -g)" golang:1.10.0-stretch gometalinter -j1 --vendor -s integration-test --deadline 900s --disable-all -E dupl -E errcheck -E gas -E gosimple -E ineffassign -E misspell -E safesql -E staticcheck -E vet -E vetshadow ./...
# results do NOT include the vendor directory and are identical to those for go 1.9.4
0,06s user 0,02s system 0% cpu 45,987 total
$
```

This should work for you as a way to reproduce the problem (with minor adjustments if your $HOME and $GOPATH are not the same).

There is definitely a problem here, but I leave the analysis to you guys. If you want o support go 1.8, there's the issue of vendor findings, otherwise there's the issue of increased run times in go >=1.9.

PS. $GOROOT was explicitly set in each case.

**Comment by dnephin** [comment]
I suspect the reason it's slower on 1.9/1.10 is directly related to the output. I don't think it's actually linting the correct files with 1.8, which is why it's faster. It runs correctly with 1.9/1.10, which is why it takes longer.

I think it's likely that the compiled binaries are using newer libs which don't work correctly with 1.8. Does gometalinter work correctly with 1.8 if you install it with `go get` instead of the pre-compiled binaries?

**Comment by wknapik** [comment]
> I suspect the reason it's slower on 1.9/1.10 is directly related to the output. I don't think it's actually linting the correct files with 1.8, which is why it's faster. It runs correctly with 1.9/1.10, which is why it takes longer.

Yeah, that's the most likely explanation.

> I think it's likely that the compiled binaries are using newer libs which don't work correctly with 1.8. Does gometalinter work correctly with 1.8 if you install it with go get instead of the pre-compiled binaries?

I believe it did, but I've run out of time to spare for verifying this. When I get back to the gometalinter stuff, I'll probably post some new findings (though we are moving to go 1.10, so it will most likely be info about how the number of warnings changed, with no further investigation into running on go 1.8).

For now at least you know that 1.8 can be problematic. I'd suggest explicitly stating which go versions are supported by gometalinter in the README.

**Comment by wknapik** [comment]
Hey. With go 1.10, the number of findings increased quite a bit (though that may have to do with upgrading gometalinter and the linters), but the running time remained similar. We're no longer using go 1.8, so that's the end of that story for me. Feel free to resolve this, if you can't reproduce the issues with go 1.8. Thanks.

**Comment by mjtrangoni** [comment]
@alecthomas I want to ask how can I skip checking a vendored project here, See (CircleCI)[https://circleci.com/gh/mjtrangoni/grafana/109].

1. This is **not** happening local, at my desktop.
2. There is no vendor at the listed *linting paths*
3. This is running with go1.10.1, but `github.com/mattn/go-sqlite3/sqlite3_go18.go` enforce using `go1.8`.

I am a bit lost on how can I get *gometalinter* running again. Thanks!!

**Comment by dnephin** [comment]
I think the problem is that the code doesn't build.  Those errors are coming from the loader. The package has to load correctly, otherwise it can't lint, so it's reporting that there are errors loading the package.

You could try running `go build` in that environment and I expect you would get the same errors. If you can fix the build errors the lint errors should be gone.

**Comment by mjtrangoni** [comment]
@dnephin I found that `CGO_ENABLED=1` did the trick, as go-sqlite3 use CGO. Thanks!

**Comment by mikeatlas-r7** [comment]
I ran into this as well. `--exclude=^vendor\/` solved it for me.

**Comment by uudashr** [comment]
Same with me 
```
$ gometalinter \
    --exclude='error return value not checked.*Log.*\(errcheck\)$$' \
    --exclude='Errors unhandled.,LOW,HIGH \(gas\)$$' \
    --disable=maligned \
    --cyclo-over=25 \
    --deadline=2m \
    --vendor \
    ./...
vendor/cloud.google.com/go/bigquery/query.go:166:22:error: cannot use true (type bool) as type *bool in assignment (vet)
vendor/cloud.google.com/go/bigquery/query.go:168:22:error: cannot use false (type bool) as type *bool in assignment (vet)
vendor/cloud.google.com/go/bigquery/query.go:199:15:error: cannot use qq.UseLegacySql (type *bool) as type bool in field value (vet)
vendor/cloud.google.com/go/bigquery/query.go:200:22:error: invalid operation: ! *bool (vet)
vendor/cloud.google.com/go/bigquery/query.go:166:22:warning: cannot use true (type bool) as type *bool in assignment (vetshadow)
vendor/cloud.google.com/go/bigquery/query.go:168:22:warning: cannot use false (type bool) as type *bool in assignment (vetshadow)
vendor/cloud.google.com/go/bigquery/query.go:199:15:warning: cannot use qq.UseLegacySql (type *bool) as type bool in field value (vetshadow)
vendor/cloud.google.com/go/bigquery/query.go:200:22:warning: invalid operation: ! *bool (vetshadow)
vendor/cloud.google.com/go/bigquery/query.go:166:24:warning: error return value not checked (cannot convert true (untyped bool constant) to *bool) (errcheck)
```

I'm using Go 1.10.2

**Comment by uudashr** [comment]
Confirm.. it seems issue on the dependency. At least for my case.

**Comment by alecthomas** [comment]
The latest gometalinter master includes a minor attempt to fix some of these issues. Give it a whirl if you're seeing similar issues.

**Comment by uudashr** [comment]
Is it possible to do fix on the linter? Because the problem still happen because of the dependency failed to compile, at least for my case.

**Comment by halorium** [comment]
Any update on this?

**Comment by sergefdrv** [comment]
> `--vendor` and `--skip path` tells `gometalinter` to never execute a linter with any path in the vendor directory, but `gometalinter` has no way of ensuring that a linter doesn't load those packages (when they are called with some other path).

@dnephin Couldn't `gometalinter` automatically ignore any linting error/warning containing `vendor` directory in the reported path, if invoked with `--vendor` option?

**Comment by dnephin** [comment]
It could, but that is definitely not what you want. If a linter is printing errors in vendor it means it is failing to load the source. If you ignore those errors all you have accomplished is to disable the linters that were failing to load.

What you probably want is to fix the build problems, not hide the lint failures.

**Comment by sergefdrv** [comment]
@dnephin In my case, I believe there was no build error. We use CircleCI with docker executor. The first stage is building&testing which works fine. The next stage is linting that failed due linting issues in one of the vendor directory. Interestingly, there was no such error before we split vendored dependencies into two vendor directories: one in root directory, and another in a subdirectory. The one in the subdirectory started causing linting issues: https://circleci.com/gh/sergefdrv/minbft/11. Moreover, same as https://github.com/alecthomas/gometalinter/issues/449#issuecomment-383186230, I cannot reproduce that on my local machine, even though I ensured exactly the same versions of gometalinter and go installed from the same binaries. But I could reproduce the same issue by rebuilding the CI image locally and running linting inside. I wonder why...

**Comment by sergefdrv** [comment]
We used Go 1.10.4 in our builds. I tried to play with Go version and it changes the result when running in a CircleCI container. With Go 1.11.4 there is no linting issue anymore. I wonder why...

**Comment by sergefdrv** [comment]
@alecthomas @mjtrangoni I think I know what was different between the CI container and the local machine. I belive, I installed `gometalinter` at some point on my machine with `go get` and `gometalinter --install`. So I had a bunch of linting tools in my `$GOPATH/bin`, which was included in `$PATH`. I guess the newly installed `gometalinter` used those tools. Once I removed those old binaries, I could reproduce the same on my local machine.

What I don't understand is why `gometalinter` still reports issues found in vendor subdirectories, although I specify `--vendor` option? I can build and test my project with either go1.10.4 or go1.11.4. So this doesn't seem a building issue. The reported issues are like:
```
sample/vendor/golang.org/x/net/http2/go111.go:26:16:warning: error return value not checked (invalid operation: trace (variable of type *net/http/httptrace.ClientTrace) has no field or method Got1xxResponse) (errcheck)
```

What I can notice is that the offending file includes `// +build go1.11` directive.

**Comment by sergefdrv** [comment]
Apparently, `gometalinter`'s tools try to analyse the code as if they would build it using their version of Go, as opposed to using the version of Go installed on the host.

**Comment by alecthomas** [comment]
Maybe gometalinter should check the version of the go compiler on the system against its own version and issue a warning.

**Comment by dnephin** [comment]
That sounds good to me. I expect that will help a bit by catching problems related to go version. However I believe we see similar problems related to `CGO_ENABLED` being enabled or disabled, and there may be other causes that I'm not familiar with.

**Comment by sergefdrv** [comment]
Issuing a warning about go version mismatch would be helpful. I had to spend quite some time trying to understand the real cause of the issue. What could also make sense is to tag the binaries on the release page with the exact go version used to compile. In other words, it would be nice to make this requirement visible.
