### ISSUE TITLE
vet error on C.CBytes call

### ISSUE THREAD

**Issue by sergefdrv** [alecthomas/gometalinter#450]
Please update `go vet` to pick up the fix https://go-review.googlesource.com/c/go/+/31810.

**Comment by alecthomas** [comment]
@dnephin ping

**Comment by dnephin** [comment]
According to the linked github issue (https://github.com/golang/go/issues/17563) that fix was in go1.8.  Apparently I forked from go1.7.6, and I think that was because of version compatibility guarantees with gometalinter.  I'll see if I can pull in any changes from go1.8.

**Comment by alecthomas** [comment]
I forget the original reason for using the fork, but is that still an issue? Can we stop using it now?

**Comment by dnephin** [comment]
Ya, the original issue was fixed. I opened #436 a little while ago. If it was fixed in 1.9 so we would only need the fork for earlier versions.

**Comment by dnephin** [comment]
#459 was opened to remove the `govet` fork. This will work for go1.9 and go1.10.  

If you're on go1.9 or go1.10, as a workaround, you can use this config:

```json
Linters: {
      "vet": {
          "Command": "go vet",
          "PartitionStrategy": "packages"
      }
  },
```

**Comment by dnephin** [comment]
#459 is merged, so closing this.
