### ISSUE TITLE
Add an option to exit non-zero on linter output

### ISSUE THREAD

**Issue by autarch** [alecthomas/gometalinter#456]
The current default behavior, where gometalinter exits 0 even when there are linting errors (for example with `gofmt`), makes this harder to use in a commit hook than it should be.

It'd be nice to have an option that caused it to always exit non-zero if any linter finds an issue.

**Comment by dnephin** [comment]
> gometalinter exits 0 even when there are linting errors

That is not the behaviour:
https://github.com/alecthomas/gometalinter/blob/b25b44d18fb62e4454847292388fbf3f9c503d68/main.go#L233-L246

**Comment by autarch** [comment]
Doh, sorry. I was misinterpreting the issue with my git hook.
