### ISSUE TITLE
lstat could not parse input, nakedret

### ISSUE THREAD

**Issue by manankalra** [alecthomas/gometalinter#458]
These are my file contents:
```go
import fmt

func main() {
   fmt.Println("GoMetaLinter")
}
```
Enabling all of the linters leads to undesirable behavior. 
Disabling `nakedret` solves it.
I'm not sure what's happening.

![selection_035](https://user-images.githubusercontent.com/12759088/38456894-4ab4754c-3aa7-11e8-8615-20c59b23f964.png)

**Comment by alecthomas** [comment]
That error is correct. Every go file needs a package statement eg. `package main`
