### ISSUE TITLE
.gometalinter.json enable all doesn't enable all linters

### ISSUE THREAD

**Issue by jonathanfoster** [alecthomas/gometalinter#463]
It appears .gometalinter.json enable all doesn't actually enable all linters. My .gometalinter.json has `"EnableAll": true`, but optional linters like dupl and lll are not run.

Here's my .gometalinter.json and debug output from running with the JSON file with `"EnableAll": true`, enable-all-json-debug.log, and with the `--enable-all` flag, enable-all-flag-debug.log. In each case I used `gometalinter ./...` to test.

- [.gometalinter.json](https://github.com/alecthomas/gometalinter/files/1935935/default.gometalinter.json.txt)
- [enable-all-json-debug.log](https://github.com/alecthomas/gometalinter/files/1935941/enable-all-json-debug.log)
- [enable-all-flag-debug.log](https://github.com/alecthomas/gometalinter/files/1935966/enable-all-flag-debug.log)

You can see in enable-all-flag-debug.log the dupl linter was enabled because it found duplicate code. No duplicate code was found in enable-all-json-debug.log. I pulled latest to make sure I've got the latest commits. My local repo is on https://github.com/alecthomas/gometalinter/commit/276fcc3b5021666bb60e55519d53c0eb4b36b85d.

I see `--enable-all` triggers the action `enableAllAction`, which enables all default linters (https://github.com/alecthomas/gometalinter/blob/master/main.go#L136). I don't see anything based on `Config.EnableAll` that would trigger a call to `enableAllAction`. The only reference I see is in a call to `replaceWithMegacheck` (https://github.com/alecthomas/gometalinter/blob/master/main.go#L384).

If this issue is not caused by operator error, then I have an idea how to implement the behavior and could submit a quick PR for feedback.

**Comment by Hawken94** [comment]
I met the same problem.
