### ISSUE TITLE
Following code shows type alias 

### ISSUE THREAD

**Issue by etsangsplk** [alecthomas/gometalinter#465]
It looks like the tool does not support type alias, like below
UDF is now an alias to int
E.g.

```go
package main

import (
	"fmt"
)

type UDF = int

func main() {
 	var x int
	var t UDF
	x = 10
	t = UDF(x)
	fmt.Printf("x: %v t: %v", x, t)
}
```

**Comment by alecthomas** [comment]
What's the error?

**Comment by etsangsplk** [comment]
Here it is  
expected type, found '=' (golint)

**Comment by dnephin** [comment]
I think `golint` needs to be updated, so this is probably a dupliate of #443
