### ISSUE TITLE
goimports - reports improperly formatted file as "file is not goimported"

### ISSUE THREAD

**Issue by briantkennedy** [alecthomas/gometalinter#469]
When running gometalinter.v2 with --enable=goimports on a directory containing a file that hasn't been through gofmt, I get an error which seems to suggest that the file has something wrong with the imports rather than the format. When consulting with README.md for the gometalinter, it describes goimports as "Checks missing or unreferenced package imports" which would lead one to further believe there is something wrong with the imports despite go building and testing properly. Since the format is at fault, I would expect a message like "file not formatted" or "file needs gofmt" instead of "file is not goimported".

main.go:1::warning: file is not goimported (goimports)

Simple example of issue here: https://github.com/briantkennedy/gometalinter-issue

**Comment by dnephin** [comment]
https://godoc.org/golang.org/x/tools/cmd/goimports

> In addition to fixing imports, goimports also formats your code in the same style as gofmt so it can be used as a replacement for your editor's gofmt-on-save hook.

This is how `goimports` is implemented. It's `gofmt` + "import formatting". I don't see any way to adjust that behaviour.

I'm going to close this issue, since I don't think there is any way to make this work the way you want, but please do comment if I've missed something.

**Comment by briantkennedy** [comment]
My main comment is that it refers to using goimports as "goimported" which does not seem like an effective term to explain what's going on here. Google searching for "goimported" yeilds 227 results that are all bug descriptions, so it would be helpful for the error message to say "you need to run goimports on this file" instead of using the term "goimported" which isn't realy well defined anywhere.

**Comment by nchelluri** [comment]
I am new to Go, and `gometalinter`, but I just spent 20 minutes trying to track down the meaning of `file is not goimported (goimports)`. Fortunately, I found this thread eventually, and realized I was missing a newline in between a built in package import and a github package import.

**Comment by briantkennedy** [comment]
@dnephin It looks like another user has encountered the same issue, you may want to reconsider the error message emitted when the file is not properly formatted.

**Comment by nchelluri** [comment]
`golangci-lint` reports it slightly differently, and better IMO:

```
$ golangci-lint run -E goimports
main.go:12: File is not goimports-ed (goimports)
```

**Comment by davidwkeith** [comment]
I see this error and I know it is a format issue now. No big deal. Except, best I can tell there is no way for either `gofmt` or `goimports` to tell me why and where the error is.

Ultimately this seems like an issue with `gofmt`, but adding to this conversation incase someone knows what I am missing.
