### ISSUE TITLE
Helping to improve the feature of unit test coverage

### ISSUE THREAD

**Issue by fearblackcat** [alecthomas/gometalinter#475]
There's no unit test coverage feature. So I will pull request if you concur to add this feature.
@alecthomas

**Comment by alecthomas** [comment]
Do you mean as an additional linter? If so, what would the lint messages be do you think?

**Comment by fearblackcat** [comment]
@alecthomas  I plan to list test case pass status in packages that has unit test files. Then do statistics of the average code coverage and packages test  coverage and also display the folder Lists that Lacking Unit Test.

**Comment by alecthomas** [comment]
I think this is outside the scope of gometalinter. It already includes `test` and `testify` linters which show test failure locations, but I think anything beyond that is probably overkill.

**Comment by fearblackcat** [comment]
Yes, the test case pass status is already in the gometalinter. But I think the lcaking unit test modules and test code coverage may be added to it.  :-) .

**Comment by fearblackcat** [comment]
@alecthomas I have added coverage feature for gometalinter. Here is the following output:

```
$ gometalinter --disable-all --enable=testcover ./sample-httpserver
List the summaries of test coverage================
——— git.cloudware.com/xxx/sample-httpserver/middleware
{"is_pass":true,"coverage":"53.3%","time":8.563} []
├── git.cloudware.com/xxx/sample-httpserver/middleware/recovery.go (100.0%)
├── git.cloudware.com/xxx/sample-httpserver/middleware/header.go (100.0%)
├── git.cloudware.com/xxx/sample-httpserver/middleware/language.go (100.0%)
├── git.cloudware.com/xxx/sample-httpserver/middleware/compress.go (91.7%)
└── git.cloudware.com/xxx/sample-httpserver/middleware/cors.go (0.0%)
——— git.cloudware.com/xxx/sample-httpserver {"is_pass":true,"coverage":"23.0%","time":0.019} []
├── git.cloudware.com/xxx/sample-httpserver/base_controller.go (88.9%)
└── git.cloudware.com/xxx/sample-httpserver/init.go (75.0%)
```
I just show the coverage and test pass status.

**Comment by alecthomas** [comment]
Okay, I see. Thanks for taking the time to do this, but I still don't think this is in the scope of a linter.
