### ISSUE TITLE
Use gometalinter to find a specific function in a file/directory

### ISSUE THREAD

**Issue by JimmyCYJ** [alecthomas/gometalinter#476]
Can I use gometalinter to find a specific function in a file/directory?
For example, if I don't want to use function time.Sleep() in a file/directory, can I pass time.Sleep() as parameter to gometalinter, and gometalinter will return warning messages that show all the locations of time.Sleep() in a file/directory.

**Comment by dnephin** [comment]
No, that is not a feature of `gometalinter`.  You would have to write a tool that walks the AST and looks for uses.
