### ISSUE TITLE
Add `--uninstall` command to uninstall linters installed by `--install`

### ISSUE THREAD

**Issue by mattjmcnaughton** [alecthomas/gometalinter#481]
Thoughts on whether it would make sense to have a `--uninstall` command which uninstalls all of the default linters installed by the `--install` command?

For example, `helm` uses `gometalinter.v1 --install` in some of its test scripts. When running those locally, it would be great to have a simple command to return the go/bin folder to its previous state.

Happy to submit a pr if this idea sounds like it could be useful :) Just let me know!

**Comment by yzgyyang** [comment]
It sounds really useful. +1 for this!
