### ISSUE TITLE
Default configuration causes multiple errors for single unused variable.

### ISSUE THREAD

**Issue by unsacrificed** [alecthomas/gometalinter#483]
Assume I have unused variable `x` in `f.go`. Then I receive 3 messages about it with default configuration:

    f.go:135:5:warning: var x is unused (U1000) (megacheck)
    f.go:135:5:warning: unused variable or constant x (varcheck)
    f.go:135:1:warning: x is unused (deadcode)

Looks like it is better to choose single linter for this situation in default configuration (not sure which one).

**Comment by alecthomas** [comment]
Often you can use --aggregate for this purpose, but not in this one because the messages differ. Other than that there is no reasonable solution.
