### ISSUE TITLE
gofmt error/warning logging isn't specific

### ISSUE THREAD

**Issue by dmigwi** [alecthomas/gometalinter#487]
I ran `gometalinter --vendor --disable-all --enable=gofmt --debug ./...` to investigate why a certain file in my code isn't well linted.

```
...
DEBUG: [Jun 14 19:19:28.930] [gofmt.1]: gofmt hits 1: ^(?P<path>.*?\.go)$
DEBUG: [Jun 14 19:19:28.931] [gofmt.1]: gofmt linter took 200.747754ms
DEBUG: [Jun 14 19:19:28.931] nolint: parsing db/dcrpg/upgrades.go for directives
DEBUG: [Jun 14 19:19:28.934] nolint: parsing db/dcrpg/upgrades.go took 3.041239ms
db/dcrpg/upgrades.go:1::warning: file is not gofmted with -s (gofmt)
DEBUG: [Jun 14 19:19:28.934] total elapsed time 221.231548ms
```
On the above log, its reporting like the warning in `db/dcrpg/upgrades.go` is in line 1 but in my code line 1 is a comment describing the package contents and licenses applicable which can't be simplified further. 
Why can't the command above log the exact line where the error/warning occurred? Its quite frustrating looking for an error you don't know where to find it.

**Comment by alecthomas** [comment]
Because gofmt doesn't provide that information.
