### ISSUE TITLE
Question: how to specify an explicit list of linters?

### ISSUE THREAD

**Issue by fatih** [alecthomas/gometalinter#49]
I couldn't find it on the help page, please feel free to close if this is a duplicate. Basically I'm searching for an option to explicitly define linters. So `gometalinters` should only invoke certain linters. These should be passed via a flag option. Is it possible? An example usage I would like to have (if possible):

```
gometalinter --enabled-linters="govet,golint" ./...
```

There is an option called `--linter` but it only allows to specify a single linter. The option `--enable` just enables previously disabled linters. I would want probably something which doesn't rely on any kind of config, and if there is any need of config I should pass them via a flag. 

Btw, I need this so I can integrate this into vim-go. Currently gometalinter calls all possible linters and because vim-go is blocking by default it's just to slow. I want to have a predefined set of linters which I'm going to add it and a way to pass linters as a configuration to vim.

**Comment by alecthomas** [comment]
Hi there. You want:

```
gometalinter --disable-all -E<linter> -E<linter> ...
```

Feel free to reopen if this doesn't answer your question completely.

**Comment by fatih** [comment]
Thanks @alecthomas. I've started and successfully integrated it into vim-go. I'm still working on it. I'll let you know when I'm finished and we can update the Readme. https://github.com/fatih/vim-go/pull/553

**Comment by alecthomas** [comment]
Looking good, thanks very much!
