### ISSUE TITLE
lll line reporting off-by-one

### ISSUE THREAD

**Issue by JeanMertz** [alecthomas/gometalinter#494]
See: https://github.com/walle/lll/issues/5 & https://github.com/walle/lll/pull/6.

I'm not sure that PR will get merged anytime soon, since the project hasn't been updated in two years, and a different gometalinter-initiated PR (https://github.com/walle/lll/pull/4) is still open.

I wanted to bring this to your attention, in case you want to port it over to gometalinter.

**Comment by alecthomas** [comment]
Mmm, yeah the abandoned projects are a bit unfortunate, but thank you.
