### ISSUE TITLE
--config should fail on invalid keys

### ISSUE THREAD

**Issue by lkysow** [alecthomas/gometalinter#502]
Spent some time debugging why `Enabled` and `Linter` didn't work. (The reason is that they keys are `Enable` and `Linters`).

Would be nice to fail the config parsing on invalid keys.

**Comment by alecthomas** [comment]
Unfortunately Go's JSON parser doesn't have that capability. I agree it would be very useful though :(

**Comment by lkysow** [comment]
I think this might work: https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields
