### ISSUE TITLE
`install.sh` script fails after gas rename

### ISSUE THREAD

**Issue by rliebz** [alecthomas/gometalinter#508]
Based on [the installation instructions with `install.sh`](https://github.com/alecthomas/gometalinter/issues/418#issuecomment-387373781), I attempted to install a pinned version of `gometalinter`:
```
 curl -L https://git.io/vp6lP | BINDIR=/usr/local/bin bash
```

And received the following error:
```
install: cannot stat '/tmp/tmp.4Ff1Jfe7oJ/gometalinter-2.0.5-linux-amd64/gosec': No such file or directory
```

This is due to the current install script trying to install `gosec` on a released version of `gometalinter` that did not vendor it. Unsurprisingly, `gas` will not be installed as well, which breaks previous builds that explicitly whitelisted `gas`.

The workaround I'm using now is to `curl` an older version of the install script:

```
curl -sL https://raw.githubusercontent.com/alecthomas/gometalinter/v2.0.6/scripts/install.sh | BINDIR=/usr/local/bin bash
```

I'm not sure what the best long-term strategy is for an install script to support a changing set of binaries, but a couple things that might make things easier for consumers:
- Release a new version with `goreleaser` so that people can pin to the latest version without issues, even if older pinned versions break
- Rather than removing `gas`, add `gosec` as a new linter and replace `gas` as the default linter. This would mean that anyone with a `.gometalinter.json` file that previously whitelisted `gas` should continue to work

**Comment by alecthomas** [comment]
Hmmm, that is not ideal.

**Comment by alecthomas** [comment]
Fixed.
