### ISSUE TITLE
Add support for go modules (vgo)

### ISSUE THREAD

**Issue by medzin** [alecthomas/gometalinter#509]
Please add support for linting projects that use go modules - currently it ends with import errors. Support for modules (vgo) is now in Go 1.11 beta 2.

**Comment by mjgarton** [comment]
Is this considered done at this point?

**Comment by alecthomas** [comment]
I don't use go 1.11 yet, but IIUC this won't be complete until all the tools are updated to support modules. That could take quite some time though, and there's not much more for us to do so I think it's fine to close.
