### ISSUE TITLE
Update to the latest gosec (added a new 'vendor' flag)

### ISSUE THREAD

**Issue by leongor** [alecthomas/gometalinter#511]
[gosec](https://github.com/securego/gosec) was updated to support `vendor` flag.
Please, update dependency to the latest [gosec](https://github.com/securego/gosec) version.

**Comment by alecthomas** [comment]
Latest since it was just merged do you mean?

**Comment by leongor** [comment]
Yes, it's from 2 days ago.

**Comment by hiroki-money** [comment]
+1
