### ISSUE TITLE
Unknown Linter error

### ISSUE THREAD

**Issue by axelbarfod1** [alecthomas/gometalinter#515]
I installed, gometalinter and added the following json:

```
{
    "Enable": ["golint", "dupl", "deadcode", "go tool vet --shadow", "structcheck", "errcheck", "unconvert", "goconst"]
}
```

When I run gometalinter I'm getting the following error:

`gometalinter: error: unknown linters: go tool vet --shadow`

This was working fine last week, did something change ?

**Comment by alecthomas** [comment]
I don't believe that ever would have worked. `Enable` is a list of linter IDs, so to enable vet shadow you would need to use `vetshadow`.
