### ISSUE TITLE
Fix installing linters in module-aware environment

### ISSUE THREAD

**Issue by misha-tectonic** [alecthomas/gometalinter#518]
`gometalinter --install` looks up source code of vendored modules `$GOPATH/src`.

This assumption no longer holds if `gometalinter` is installed from `go.mod` environment.

Also, unless I'm missing something, vendored modules can be replaced with a `go.mod` file pinning versions/repositories of all linters.

**Comment by alecthomas** [comment]
See #499

**Comment by alecthomas** [comment]
Closing this because that is no longer a supported installation mechanism. Use `curl https://git.io/vp6lP | sh` or download releases directly.
