### ISSUE TITLE
Tags aren't being marked as releases

### ISSUE THREAD

**Issue by JeremyLoy** [alecthomas/gometalinter#523]
Hi,

Not sure if this is deliberate or not, but the two most recent tags were not marked as "releases" in Github, therefore `goreleaser` isn't being run. This prevents the newest binary versions from being installed via `home-brew` or some install bash script.

**Comment by thsnr** [comment]
It seems to me that this is because https://github.com/alecthomas/gometalinter/blob/master/.travis.yml#L26 indicates to only create a release if `TRAVIS_GO_VERSION` is 1.11.x, but it is actually simply 1.11.

Replacing it with `^1\.11(\.[0-9]+)?$` should work.

**Comment by alecthomas** [comment]
@thsnr Thanks for picking tha tup, should be fixed now.

**Comment by JeremyLoy** [comment]
LGTM!, thanks for the quick fix!
