### ISSUE TITLE
Add support for custom linter partition strategy in command line

### ISSUE THREAD

**Issue by beornf** [alecthomas/gometalinter#528]
The partition strategy for a custom linter can only be changed in the `.gometalinter.json` config file.

Could we add support to change this through command line flags either by extending the flag `--linter=NAME:COMMAND:PATTERN` or adding a new flag `--linter-strategy=NAME:PARTITION_STRATEGY`?

**Comment by dnephin** [comment]
Specifying complex (and structured) config is not easy on the command line. What's wrong with using the config file?

**Comment by beornf** [comment]
I have been setting custom linter options in my vim config as command line flags. Is using the config file preferred now for enabling/disabling linters and settings that mostly won't change?
