### ISSUE TITLE
gometalinter --install fail

### ISSUE THREAD

**Issue by QHasaki** [alecthomas/gometalinter#534]
after "sudo go get github.com/alecthomas/gometalinter", I'm failed in installing gometalinter, at first i run "gometalinter --install", it failed as:
Installing:
  deadcode
  dupl
  errcheck
  gochecknoglobals
  gochecknoinits
  goconst
  gocyclo
  goimports
  golint
  gosec
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  megacheck
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
go install 4d63.com/gochecknoglobals: open /Users/qinhan/go/bin/gochecknoglobals: permission denied
go install github.com/gordonklaus/ineffassign: open /Users/qinhan/go/bin/ineffassign: permission denied
go install github.com/alecthomas/gocyclo: open /Users/qinhan/go/bin/gocyclo: permission denied
go install github.com/jgautheron/goconst/cmd/goconst: open /Users/qinhan/go/bin/goconst: permission denied
go install github.com/alexkohler/nakedret: open /Users/qinhan/go/bin/nakedret: permission denied
go install github.com/opennota/check/cmd/structcheck: open /Users/qinhan/go/bin/structcheck: permission denied
go install 4d63.com/gochecknoinits: open /Users/qinhan/go/bin/gochecknoinits: permission denied
go install honnef.co/go/tools/cmd/unused: open /Users/qinhan/go/bin/unused: permission denied
go install mvdan.cc/interfacer: open /Users/qinhan/go/bin/interfacer: permission denied
go install github.com/golang/lint/golint: open /Users/qinhan/go/bin/golint: permission denied
go install github.com/walle/lll/cmd/lll: open /Users/qinhan/go/bin/lll: permission denied
go install github.com/stripe/safesql: open /Users/qinhan/go/bin/safesql: permission denied
go install golang.org/x/tools/cmd/gotype: open /Users/qinhan/go/bin/gotype: permission denied
go install github.com/mibk/dupl: open /Users/qinhan/go/bin/dupl: permission denied
go install honnef.co/go/tools/cmd/staticcheck: open /Users/qinhan/go/bin/staticcheck: permission denied
go install github.com/mdempsky/maligned: open /Users/qinhan/go/bin/maligned: permission denied
go install mvdan.cc/unparam: open /Users/qinhan/go/bin/unparam: permission denied
go install github.com/mdempsky/unconvert: open /Users/qinhan/go/bin/unconvert: permission denied
go install github.com/tsenart/deadcode: open /Users/qinhan/go/bin/deadcode: permission denied
go install github.com/opennota/check/cmd/varcheck: open /Users/qinhan/go/bin/varcheck: permission denied
go install golang.org/x/tools/cmd/goimports: open /Users/qinhan/go/bin/goimports: permission denied
go install honnef.co/go/tools/cmd/gosimple: open /Users/qinhan/go/bin/gosimple: permission denied
go install github.com/kisielk/errcheck: open /Users/qinhan/go/bin/errcheck: permission denied
go install github.com/client9/misspell/cmd/misspell: open /Users/qinhan/go/bin/misspell: permission denied
go install github.com/securego/gosec/cmd/gosec: open /Users/qinhan/go/bin/gosec: permission denied
go install honnef.co/go/tools/cmd/megacheck: open /Users/qinhan/go/bin/megacheck: permission denied
WARNING: failed to install one or more linters: exit status 1 (installing individually)
go install honnef.co/go/tools/cmd/staticcheck: open /Users/qinhan/go/bin/staticcheck: permission denied
WARNING: failed to install honnef.co/go/tools/cmd/staticcheck: exit status 1
go install honnef.co/go/tools/cmd/unused: open /Users/qinhan/go/bin/unused: permission denied
WARNING: failed to install honnef.co/go/tools/cmd/unused: exit status 1
go install github.com/opennota/check/cmd/structcheck: open /Users/qinhan/go/bin/structcheck: permission denied
WARNING: failed to install github.com/opennota/check/cmd/structcheck: exit status 1
go install 4d63.com/gochecknoglobals: open /Users/qinhan/go/bin/gochecknoglobals: permission denied
WARNING: failed to install 4d63.com/gochecknoglobals: exit status 1
go install github.com/gordonklaus/ineffassign: open /Users/qinhan/go/bin/ineffassign: permission denied
WARNING: failed to install github.com/gordonklaus/ineffassign: exit status 1
go install github.com/alexkohler/nakedret: open /Users/qinhan/go/bin/nakedret: permission denied
WARNING: failed to install github.com/alexkohler/nakedret: exit status 1
go install mvdan.cc/interfacer: open /Users/qinhan/go/bin/interfacer: permission denied
WARNING: failed to install mvdan.cc/interfacer: exit status 1
go install github.com/walle/lll/cmd/lll: open /Users/qinhan/go/bin/lll: permission denied
WARNING: failed to install github.com/walle/lll/cmd/lll: exit status 1
go install github.com/jgautheron/goconst/cmd/goconst: open /Users/qinhan/go/bin/goconst: permission denied
WARNING: failed to install github.com/jgautheron/goconst/cmd/goconst: exit status 1
go install github.com/alecthomas/gocyclo: open /Users/qinhan/go/bin/gocyclo: permission denied
WARNING: failed to install github.com/alecthomas/gocyclo: exit status 1
go install github.com/golang/lint/golint: open /Users/qinhan/go/bin/golint: permission denied
WARNING: failed to install github.com/golang/lint/golint: exit status 1
go install github.com/stripe/safesql: open /Users/qinhan/go/bin/safesql: permission denied
WARNING: failed to install github.com/stripe/safesql: exit status 1
go install 4d63.com/gochecknoinits: open /Users/qinhan/go/bin/gochecknoinits: permission denied
WARNING: failed to install 4d63.com/gochecknoinits: exit status 1
go install golang.org/x/tools/cmd/gotype: open /Users/qinhan/go/bin/gotype: permission denied
WARNING: failed to install golang.org/x/tools/cmd/gotype: exit status 1
go install golang.org/x/tools/cmd/gotype: open /Users/qinhan/go/bin/gotype: permission denied
WARNING: failed to install golang.org/x/tools/cmd/gotype: exit status 1
go install mvdan.cc/unparam: open /Users/qinhan/go/bin/unparam: permission denied
WARNING: failed to install mvdan.cc/unparam: exit status 1
go install github.com/mdempsky/maligned: open /Users/qinhan/go/bin/maligned: permission denied
WARNING: failed to install github.com/mdempsky/maligned: exit status 1
go install github.com/mibk/dupl: open /Users/qinhan/go/bin/dupl: permission denied
WARNING: failed to install github.com/mibk/dupl: exit status 1
go install github.com/mdempsky/unconvert: open /Users/qinhan/go/bin/unconvert: permission denied
WARNING: failed to install github.com/mdempsky/unconvert: exit status 1
go install github.com/opennota/check/cmd/varcheck: open /Users/qinhan/go/bin/varcheck: permission denied
WARNING: failed to install github.com/opennota/check/cmd/varcheck: exit status 1
go install honnef.co/go/tools/cmd/gosimple: open /Users/qinhan/go/bin/gosimple: permission denied
WARNING: failed to install honnef.co/go/tools/cmd/gosimple: exit status 1
go install github.com/client9/misspell/cmd/misspell: open /Users/qinhan/go/bin/misspell: permission denied
WARNING: failed to install github.com/client9/misspell/cmd/misspell: exit status 1
go install honnef.co/go/tools/cmd/megacheck: open /Users/qinhan/go/bin/megacheck: permission denied
WARNING: failed to install honnef.co/go/tools/cmd/megacheck: exit status 1
go install golang.org/x/tools/cmd/goimports: open /Users/qinhan/go/bin/goimports: permission denied
WARNING: failed to install golang.org/x/tools/cmd/goimports: exit status 1
go install github.com/tsenart/deadcode: open /Users/qinhan/go/bin/deadcode: permission denied
WARNING: failed to install github.com/tsenart/deadcode: exit status 1
go install github.com/kisielk/errcheck: open /Users/qinhan/go/bin/errcheck: permission denied
WARNING: failed to install github.com/kisielk/errcheck: exit status 1
go install github.com/securego/gosec/cmd/gosec: open /Users/qinhan/go/bin/gosec: permission denied
WARNING: failed to install github.com/securego/gosec/cmd/gosec: exit status 1
gometalinter: error: failed to install the following linters: honnef.co/go/tools/cmd/staticcheck, honnef.co/go/tools/cmd/unused, github.com/opennota/check/cmd/structcheck, 4d63.com/gochecknoglobals, github.com/gordonklaus/ineffassign, github.com/alexkohler/nakedret, mvdan.cc/interfacer, github.com/walle/lll/cmd/lll, github.com/jgautheron/goconst/cmd/goconst, github.com/alecthomas/gocyclo, github.com/golang/lint/golint, github.com/stripe/safesql, 4d63.com/gochecknoinits, golang.org/x/tools/cmd/gotype, golang.org/x/tools/cmd/gotype, mvdan.cc/unparam, github.com/mdempsky/maligned, github.com/mibk/dupl, github.com/mdempsky/unconvert, github.com/opennota/check/cmd/varcheck, honnef.co/go/tools/cmd/gosimple, github.com/client9/misspell/cmd/misspell, honnef.co/go/tools/cmd/megacheck, golang.org/x/tools/cmd/goimports, github.com/tsenart/deadcode, github.com/kisielk/errcheck, github.com/securego/gosec/cmd/gosec
------------------------------------------------------------------------------------------------------
then i run " sudo gometalinter --install", if failed again:
gometalinter: error: could not find vendored linters in GOPATH="/var/root/go"

but, i have set my gopath already:
$ env |grep GO
GOBIN=/Users/qinhan/go/bin
GOROOT=/usr/local/Cellar/go/1.11/libexec
GOPATH=/Users/qinhan/go

**Comment by alecthomas** [comment]
Environment variables aren't propagated through sudo, so GOPATH is different for root (as the error describes).

Also, `go get` is no longer a supported installation method. Use the pre-built release packages under the releases tab (see README for details).
