### ISSUE TITLE
Support --disable-all in the configuration file

### ISSUE THREAD

**Issue by autarch** [alecthomas/gometalinter#538]
AFAICT there is no way to set this option via the config file, but pretty much every other CLI option _is_ supported. It'd be nice to support this in config as well.

**Comment by djui** [comment]
Just wanted to ask the same thing. Also: It seems there is a mismatch between `--tests` and https://github.com/alecthomas/gometalinter/blob/master/config.go#L49

**Comment by dnephin** [comment]
The reason it doesn't exist in the config file is because enabling any linter in the config automatically implies `DisableAll`. `Enable` in a config overrides the default list of linters.

With the `--enable` flag the behaviour is to add the linter to the default list.

**Comment by djui** [comment]
I suspected that skimming the code.

Maybe this deserve documenting somewhere as any asymmetry between flags and config file is not asssumed.

Could we check in a `.gometalinter.json.sample` file which then explain any assymeetry of a specific key?
