### ISSUE TITLE
gometalinter: error: EOF, try --help

### ISSUE THREAD

**Issue by nghialt** [alecthomas/gometalinter#542]
I'm facing an error while installing. When I type

> gometalinter --install

the console output: 

> gometalinter: error: EOF, try --help.

Does anyone has any idea what the problem is?

**Comment by alecthomas** [comment]
No but you should use the releases. Manual install is no longer supported and that flag will be removed eventually.

**Comment by alecthomas** [comment]
You can ignore the Quickstart section (I will remove it now, sorry about that). If you used curl, you already have all of the linters installed.

**Comment by nghialt** [comment]
the problem is I didn't specify any lint so it was looking for the json file, which was empty
