### ISSUE TITLE
gometalinter: error: user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by allencloud** [alecthomas/gometalinter#554]
I have used the `--debug` flag to get more debug information, while it is still outputing the error message:

```
root@0dfa93f4ca83:/# gometalinter --debug --disable-all --skip vendor -E gofmt ./...
gometalinter: error: user: Current not implemented on linux/amd64
```

### The way I install

``` sh
curl -L https://git.io/vp6lP | sh
```

**Comment by dirathea** [comment]
any updates on this one? I've got this issue too..

**Comment by pehowell** [comment]
Error appears to be related to not being able to determine what the `$GOPATH` should be. If I set either  `$USER` or `$GOPATH`, the error goes away.
