### ISSUE TITLE
Output for custom linter contains "gibberish"

### ISSUE THREAD

**Issue by soupdiver** [alecthomas/gometalinter#556]
I have added a custom linter with the flag `--linter='imp:goimports -l -local github.com/cloudradar-monitoring/cagent:^(?P<pathh>.*?\.go)$'`. After some back and forth I got it running but the output looks a bit weird:

Gives me:
```
config.go:1::warning:  (imp)
cpu.go:1::warning:  (imp)
mem.go:1::warning:  (imp)
mem_windows.go:1::warning:  (imp)
processes_notwindows.go:1::warning:  (imp)
raid_test.go:1::warning:  (imp)
types.go:1::warning:  (imp)
```

Not really sure why always `:1::warning:  ` is added. Guess it should help identify the problem but the original output is only paths without an explanation.

Can I get rid of this `:1::warning:  ` somehow or do I have to adjust the pattern for that?
Also, is there somewhere an explanation about how to use the pattern? Which things to extract for example?

**Comment by dnephin** [comment]
I believe those lines are the default values for the fields in https://github.com/alecthomas/gometalinter/blob/b242b54b75005af59cb3a06620085146709b598a/issue.go#L72-L80

The message format is https://github.com/alecthomas/gometalinter/blob/b242b54b75005af59cb3a06620085146709b598a/issue.go#L15

So the 1 is the line number and the warning is severity.

You can set a different format in the config, but it would apply to all linters.

**Comment by soupdiver** [comment]
@dnephin yeah seems the locations you pointed out explain the situation.
Seems there is no easy immediate fix then 🤓
