### ISSUE TITLE
install via `curl` fails on `arm64` platform.

### ISSUE THREAD

**Issue by vielmetti** [alecthomas/gometalinter#566]
I get the following error when I try to install `gometalinter` on an arm64 system.

```
% curl -L https://git.io/vp6lP | sh
alecthomas/gometalinter crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/alecthomas/gometalinter/issues/new
```

I am not sure how to reconcile this with the change at #553 which adds arm64 binaries.

**Comment by vielmetti** [comment]
The impetus for this is a port of `loki`, see https://github.com/grafana/loki/issues/67 .

**Comment by alecthomas** [comment]
[Fixed!](https://github.com/alecthomas/gometalinter/releases/tag/v2.0.12)
