### ISSUE TITLE
Add goreturns

### ISSUE THREAD

**Issue by jayvdb** [alecthomas/gometalinter#568]
Some people prefer goreturns over the alternatives.

It is actively maintained: https://github.com/sqs/goreturns

**Comment by dnephin** [comment]
From my reading this seems less like a linter, and more a code completion tool.

**Comment by jayvdb** [comment]
Right, it is like `gofmt` which gometalinter supports.

It actually calls gofmt and goimports, which is probably the biggest problem for gometalinter.  goreturns can be configued to not run goimports , but I dont think gofmt can be disabled.  So a gometalinter user should run either gofmt or goreturns, not both unless they like to waste CPU.

See also https://github.com/Microsoft/vscode-go/issues/418
