### ISSUE TITLE
Add option to exclude paths when recursing

### ISSUE THREAD

**Issue by pdf** [alecthomas/gometalinter#57]
With official vendoring taking the unfortunate path of `./vendor/` rather than using a hidden (`.`-prefixed) dir, it would be beneficial to have an option that allows excluding paths from recursion.  Perhaps this should default to `vendor`.

**Comment by alecthomas** [comment]
That's a good idea.

**Comment by alecthomas** [comment]
Also see #30.

**Comment by alecthomas** [comment]
I've added `--skip=PATH` and `--vendor` flags. The latter sets `GO15VENDOREXPERIMENT=1` *and* ignores `vendor` directories.

**Comment by pdf** [comment]
Awesome, thanks for taking care of this @alecthomas.
