### ISSUE TITLE
gometalinter does not invoke golint correctly

### ISSUE THREAD

**Issue by oliver-rew** [alecthomas/gometalinter#573]
Hi, I have read through the documentation and I cannot figure this out. When I run:
```
//config file specifies "golint", "gofmt", "gosec", and "deadcode"
gometalinter --config=".gometalinter.json" ./... --debug
```
I do not get any output from `golint`. When I check the debug message I see that `golint` is being executed as such:
```
DEBUG: [Jan  4 19:20:40.101] [golint.3]: executing /usr/bin/golint -min_confidence 0.800000 . ./dir1 ./dir2 ./dir3 
```
Which when ran independently results in the following error output:
```
$ golint -min_confidence 0.800000 . ./dir1 ./dir2 ./dir3
read .: is a directory
read ./dir1: is a directory
read ./dir2: is a directory
read ./dir3: is a directory
```
Likewise, the `golint` help text shows this is an invalid way to use `golint`
```
$ golint --help
Usage of golint:
    golint [flags] # runs on package in current directory
    golint [flags] package
    golint [flags] directory
    golint [flags] files... # must be a single package
```
Am I missing something in how to invoke `gometalinter so that `golint` works with other linters? When `gometalinter` is passed `./...` shouldn't it call `golint` similarly(this is a valid us of `golint`. In fact, AFAIK it is the only way to use `golint` recursively with multiple packages. 

Thanks for the help!

**Comment by alecthomas** [comment]
You're using the wrong version of golint. You probably have an older version installed somewhere that is being used rather than the version installed by gometalinter.
