### ISSUE TITLE
gometalinter fails on empty directory

### ISSUE THREAD

**Issue by cep21** [alecthomas/gometalinter#58]
The other linters work with empty directories, but it looks like gofmt and goimports fail on directories without *.go files.  Can these linters not run on directories without *.go files?

```
< gometalinter .
stat ./*.go: no such file or directory:1::error: file is not gofmted (gofmt)
stat ./*.go: no such file or directory:1::error: file is not goimported (goimports)
```

**Comment by alecthomas** [comment]
Under what circumstances do you run it on an empty directory?

**Comment by cep21** [comment]
xargs and company

**Comment by cep21** [comment]
I usually can't use "./..." and have to xargs pipe things because I need to ignore some files or directories.  I'm hacking around it, but it seems reasonable to not fail if ran in a directory that doesn't have go files in it.

**Comment by alecthomas** [comment]
Ah, well, coincidentally I am implementing #57 which will add a directory exclusion flag.

Currently, I pass paths directly on to the underlying linters as-is. Having to check each directory to see if it's empty seems like overkill for an edge case.

In summary, I won't implement this. A good workaround is to use the `--exclude` flag to filter out those errors. Or use the `--skip` flag to skip matching paths.

**Comment by cep21** [comment]
Non empty directories will fail as well.  Any directory without *.go files inside it will fail the fmt and imports check.

**Comment by alecthomas** [comment]
Yeah, I understand the problem.
