### ISSUE TITLE
vendor not work in go 1.10+

### ISSUE THREAD

**Issue by daixiang0** [alecthomas/gometalinter#589]
I can not skip vendor lint, the log is [here](https://circleci.com/gh/grafana/loki/2351?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link).

The old val of Vendor in config is true, but it can not skip vendor dir, so i change it to false, still can not work.

I test locally, same result.

Config file is [here](https://github.com/grafana/loki/blob/master/.gometalinter.json)

Makefile is [here](https://github.com/grafana/loki/blob/master/Makefile#L128).

**Comment by dnephin** [comment]
https://github.com/alecthomas/gometalinter/issues/562#issuecomment-447606888

**Comment by daixiang0** [comment]
@dnephin I change to use `go1.10.4`, but `gometalinter --vendor ./...` still can not work.

**Comment by daixiang0** [comment]
@dnephin hi，i follow comment but get:
```
[root@dx-app2 loki]# GO111MODULE=on go mod vendor
go: github.com/cespare/xxhash@v0.0.0-20190104012619-3b82fb7d1867: go.mod has post-v0 module path "github.com/cespare/xxhash/v2" at revision 3b82fb7d1867
go: error loading module requirements
```
I do not know how to fix it, could you help me?

**Comment by daixiang0** [comment]
@dnephin any input?

**Comment by dnephin** [comment]
It sounds like the problem is that one of your dependencies is incompatible with `go mod`.
