### ISSUE TITLE
go mod vendor error

### ISSUE THREAD

**Issue by daixiang0** [alecthomas/gometalinter#592]
The repo is [loki](https://github.com/grafana/loki), after use `dep ensure` at master branch:
```
[root@dx-app2 loki]# GO111MODULE=on go mod vendor
go: creating new go.mod: module github.com/grafana/loki
go: copying requirements from Gopkg.lock
go: converting Gopkg.lock: stat github.com/weaveworks/common@6ebd07f752e2a8d51d3ac919014f972350d25b39: unknown revision 6ebd07f752e2a8d51d3ac919014f972350d25b39
go: github.com/cespare/xxhash@v0.0.0-20190104012619-3b82fb7d1867: go.mod has post-v0 module path "github.com/cespare/xxhash/v2" at revision 3b82fb7d1867
go: error loading module requirements
[root@dx-app2 loki]# go version
go version go1.11 linux/amd64
[root@dx-app2 loki]# gometalinter --version
gometalinter version 3.0.0 built from df395bfa67c5d0630d936c0044cf07ff05086655 on 2019-01-29T22:44:16Z
```

**Comment by alecthomas** [comment]
Sorry, I don't understand. What has this got to do with gometalinter?

If you're trying to include gometalinter as a dependency, that is not supported. Use the installation instructions in the README to install gometalinter.

**Comment by daixiang0** [comment]
I just want to skip check lint about codes in vendor, as comment in #589 , i found this error, i do not know how to fix it.

**Comment by alecthomas** [comment]
I'm not sure. This is a Go module error, so you'll have to search around for an answer. To be clear, this has nothing to do with gometalinter.

**Comment by daixiang0** [comment]
@alecthomas thanks, could you help take a look about #589 , i still can not ignore lint error which in vendor dir.
