### ISSUE TITLE
Unmatched checksum

### ISSUE THREAD

**Issue by EatonEmmerich** [alecthomas/gometalinter#596]
With the following:
$ go get github.com/alecthomas/gometalinter/releases/tag/v3.0.0
go: finding github.com/alecthomas/gometalinter/releases/tag latest
go: finding github.com/alecthomas/gometalinter/releases latest
go: downloading github.com/alecthomas/gometalinter v3.0.0+incompatible
go: verifying github.com/alecthomas/gometalinter@v3.0.0+incompatible: checksum mismatch
	downloaded: h1:e9Zfvfytsw/e6Kd/PYd75wggK+/kX5Xn8IYDUKyc5fU=
	go.sum:     h1:+A0g3WZuqrIRQtFITjs53Dxu7S8yj99GY3u53Szo5p0=

**Comment by alecthomas** [comment]
I don’t know what that means.

**Comment by alecthomas** [comment]
Also the only supported installation method is via release binaries.

**Comment by dnephin** [comment]
https://github.com/golang/go/issues/29278

There was a change in go1.11.4 which caused this for some packages. `go.mod` may need to be updated for newer version of go.

**Comment by EatonEmmerich** [comment]
Oh, I didn't realise only binary releases are supported. Thanks!
