### ISSUE TITLE
GetFileAttributesEx .\*.go warnings

### ISSUE THREAD

**Issue by tdewolff** [alecthomas/gometalinter#69]
When running `gometalinter ./...` over a package, I get the following warnings for each directory:

```
GetFileAttributesEx .\*.go: The filename, directory name, or volume label syntax is incorrect.:1::warning: file is not goimported (goimports)
GetFileAttributesEx .\*.go: The filename, directory name, or volume label syntax is incorrect.:1::warning: file is not gofmted (gofmt)
```

All my files are gofmted and goimported, it seems it barks this over directories or the `*.go` pattern...

Go 1.5 on Win10

**Comment by alecthomas** [comment]
Does this still occur? Did you try using `--debug` to see what was occurring? Anyway, gofmt and goimports are no longer enabled by default.

**Comment by tdewolff** [comment]
Yes, this problem does not occur anymore, thanks.
