### ISSUE TITLE
How do I pass flags?

### ISSUE THREAD

**Issue by Unknwon** [alecthomas/gometalinter#70]
For example I want to pass flag to `golint`.

Thanks.

**Comment by alecthomas** [comment]
You cannot. What are you attempting to do?

**Comment by Unknwon** [comment]
Let's I want to change `min_confidence`, how can I achieve that?

**Comment by alecthomas** [comment]
Fortunately, that flag is available as '--min-confidence=0.8'.

**Comment by Unknwon** [comment]
How about other tools, like `go vet -composites=false -methods=false -structtags=false`?

**Comment by alecthomas** [comment]
You'll need to override the tool with --linter. Check out the README or help for more information.

**Comment by Unknwon** [comment]
My bad, miss the last section.

How about override more than one tool? Use `--linter` twice?

**Comment by alecthomas** [comment]
No problem. Yep, exactly.

**Comment by Unknwon** [comment]
Got it, thanks a lot!
