### ISSUE TITLE
Add goconst

### ISSUE THREAD

**Issue by jgautheron** [alecthomas/gometalinter#78]
[goconst](https://github.com/jgautheron/goconst) finds repeated strings that could be replaced by a constant.
I could throw a PR your way if you think this would be a good addition.

**Comment by alecthomas** [comment]
Sounds good, I'd love a PR.

**Comment by alecthomas** [comment]
Ping.

**Comment by jgautheron** [comment]
How do you propose I integrate the following output in `gometalinter`?
```
9 occurrences of ", " found:
	gossip/infostore.go:112:13
	sql/parser/alter_table.go:49:12
	sql/parser/create.go:124:12
	sql/parser/select.go:87:12
	sql/parser/select.go:141:12
	sql/parser/select.go:278:12
	sql/parser/select.go:291:12
	sql/parser/update.go:50:12
	sql/parser/expr.go:559:12
6 occurrences of "tcp" found:
	gossip/resolver/node_lookup.go:78:16
	gossip/resolver/resolver.go:56:9
	gossip/resolver/resolver.go:92:7
	gossip/resolver/socket.go:49:7
	util/testing.go:119:7
	util/unresolved_addr.go:63:7
5 occurrences of "unix" found:
	gossip/resolver/resolver.go:77:12
	gossip/resolver/resolver.go:92:14
	gossip/resolver/socket.go:42:7
	util/testing.go:125:7
	util/unresolved_addr.go:67:7
```
`gometalinter` is path-centric and in this instance, there are multiple paths.

I could reformat the error message as: `5 occurrences of "unix" found in file1:x:y, file2:x:y, file3:x:y` but I still need at least a reference `path`. Should it be the first mentioned?

**Comment by alecthomas** [comment]
dupl had the [same problem](https://github.com/mibk/dupl/issues/2). Check out their solution (which gometalinter uses).
