### ISSUE TITLE
Add usedexports

### ISSUE THREAD

**Issue by jgautheron** [alecthomas/gometalinter#79]
[usedexports](https://github.com/jgautheron/usedexports) finds exported variables that could be unexported.
We talked about it a while ago, I finally took a whole different approach.

**Comment by alecthomas** [comment]
I remember, but I'm not sure there's a good solution in general. IMO you really want to know what symbols in public packages are unused by other packages. This is inherently a slow process and probably not a good fit for gometalinter.

For a "main" package, it doesn't really matter what is or isn't exported, as you can't import a main package anyway.

**Comment by jgautheron** [comment]
Agreed, I run this linter manually when needed but I wouldn't integrate it in my CI build.
