### ISSUE TITLE
process exits 0 when errors/warnings are reported

### ISSUE THREAD

**Issue by afex** [alecthomas/gometalinter#8]
i expect linters to return non-zero exit codes when they find something so that they may be used during build processes.

**Comment by alecthomas** [comment]
I've actually changed this to completely ignore the linter status code, as it's not reliable. Now, if any lint messages are printed, gometalinter exits with a non-zero status. You can also now use `--errors` to only report errors, in which case gometalinter will only exit with a non-zero status if there are errors.
