### ISSUE TITLE
doco issue with repeated arguments

### ISSUE THREAD

**Issue by client9** [alecthomas/gometalinter#81]
Thanks for a lovely project.

For what it's worth, I thought the following meant I was suppose to comma-separate the values, when instead you need to repeat the arg, e.g. `--disable=test --disable=gofmt`   Same with ` -e, --exclude=REGEXP`, etc.

```
  -D, --disable=LINTER      List of linters to disable (testify,test,gofmt,go imports).
```

thanks again!

n

**Comment by alecthomas** [comment]
This is actually related to kingpin (the flag parser), but is something I've been [meaning to fix](https://github.com/alecthomas/kingpin/issues/90).

**Comment by alecthomas** [comment]
This should have been fixed in the latest kingpin release.
