### ISSUE TITLE
1.5 linters build error

### ISSUE THREAD

**Issue by sp-gonzalo-serrano** [alecthomas/gometalinter#83]
Looks like some linters are unable to build with go 1.5, probably because the `types` package was moved (see https://golang.org/doc/go1.5).

Errors output: https://gist.github.com/sp-gonzalo-serrano/782a93cb7a7e656bcbe1

Is there any way to just install certain linters?

Thanks

**Comment by casimir** [comment]
If you have upgrade Go recently you should clean the packages cache, `rm -rf $GOPATH/pkg`.

**Comment by njohns-grovo** [comment]
This is currently happening from running 

```
go get -u github.com/opennota/check/cmd/structcheck
go get -u github.com/opennota/check/cmd/aligncheck
```

**Comment by alecthomas** [comment]
There is currently no way to install linters separately.

All linters are installed with one command to avoid repeatedly updating/installing the same packages that the linters depend on. For example, the two commands mentioned by @njohns-grovo will download all the dependencies twice. Multiply that by 17 linters and installs/updates take a very long time if done individually. By combining them into one command, common dependencies are only downloaded once. This was introduced in 8d1fc9355fa30b100f360af158acfd8a32433943.

There are several solutions:

1. Do nothing. People can manually install linters if temporary breakage occurs.
2. Attempt one-shot install but fall back on installing linters individually on failure.

**Comment by alecthomas** [comment]
I implemented the second option.

**Comment by emead** [comment]
Looks like this specific build failure was fixed by a roll-back commit in golang/tools: https://github.com/golang/tools/commit/da91609d887c6b1e28ad4548c47f3ff39a471989
