### ISSUE TITLE
Can't skip dir named "repos"

### ISSUE THREAD

**Issue by shawnps** [alecthomas/gometalinter#86]
Not sure if I'm just invoking the command incorrectly but...

This successfully skips `Godeps` dir: `gometalinter --skip=Godeps --disable=all --enable=gocyclo ./...`

This does not skip a dir called `repos`: `gometalinter --skip=repos --disable=all --enable=gocyclo ./...`

And this skips neither `Godeps` nor `repos`: `gometalinter --skip=Godeps --skip=repos --disable=all --enable=gocyclo ./...`

**Comment by shawnps** [comment]
```
➜  goreportcard [gometalinter] go version
go version go1.5.2 darwin/amd64
➜  goreportcard [gometalinter] go get -u -v github.com/fzipp/gocyclo
github.com/fzipp/gocyclo (download)
➜  goreportcard [gometalinter] vim /Users/shawn/mygo/src/github.com/alecthomas/gometalinter/main.go
➜  goreportcard [gometalinter] go get -u -v github.com/alecthomas/gometalinter
github.com/alecthomas/gometalinter (download)
github.com/google/shlex (download)
Fetching https://gopkg.in/alecthomas/kingpin.v2?go-get=1
Parsing meta tags from https://gopkg.in/alecthomas/kingpin.v2?go-get=1 (status code 200)
get "gopkg.in/alecthomas/kingpin.v2": found meta tag main.metaImport{Prefix:"gopkg.in/alecthomas/kingpin.v2", VCS:"git", RepoRoot:"https://gopkg.in/alecthomas/kingpin.v2"} at https://gopkg.in/alecthomas/kingpin.v2?go-get=1
gopkg.in/alecthomas/kingpin.v2 (download)
github.com/alecthomas/template (download)
github.com/alecthomas/units (download)
github.com/alecthomas/gometalinter
```

**Comment by shawnps** [comment]
If I add `--exclude=Godeps` and `--exclude=repos` they do not show up in the output.

**Comment by alecthomas** [comment]
This is actually a [FAQ](https://github.com/alecthomas/gometalinter#why-does-gometalinter---install-install-a-fork-of-gocyclo).

If you run gometalinter with `--debug` you'll notice it doesn't actually call gocyclo in those directories, but the default behaviour for goycyclo is to recurse.

Finally, you should not install gocyclo manually, you should use `gometalinter --install --update`.

**Comment by alecthomas** [comment]
Also, you probably want `--disable-all` not `--disable=all`.

**Comment by shawnps** [comment]
@alecthomas Ahhh thanks. Apologies for not reading the manual.

**Comment by shawnps** [comment]
> Also, you probably want --disable-all not --disable=all.

thanks!
