### ISSUE TITLE
Switch to https://github.com/mdempsky/maligned instead of aligncheck?

### ISSUE THREAD

**Issue by dgryski** [alecthomas/gometalinter#92]
The author of `aligncheck`, @opennota, suggests to use `maligned`.

https://github.com/opennota/check/issues/28#issuecomment-184007619

**Comment by alecthomas** [comment]
Unfortunately it doesn't compile: https://github.com/mdempsky/maligned/issues/1

**Comment by dgryski** [comment]
The maligned build has been fixed.

**Comment by dgryski** [comment]
ping

**Comment by dajohi** [comment]
@alecthomas status?

**Comment by andreigornostajev** [comment]
Hei @alecthomas, I have also faced a problem with aligncheck and again, its author suggests to use https://github.com/mdempsky/maligned. So, it would be really nice to add support for it.
Thanks
