### ISSUE TITLE
Trying to ignore multiple linters does not work

### ISSUE THREAD

**Issue by djui** [alecthomas/gometalinter#95]
Running `gometalinter . --deadline=10m --disable=gotype,gocyclo` does not exclude either linter.

**Comment by alecthomas** [comment]
The correct syntax is:

```
gometalinter --disable=gotype --disable=gocyclo
```

**Comment by alecthomas** [comment]
Unrelated, but you may want to consider `--disable-all --enable=X --enable=Y` for more reproducible results. This prevents extra linters from running when added to upstream gometalinter.

**Comment by djui** [comment]
That I found, but the documentation is inaccurate and hints at (1) it's a list and (2) it's a comma-separated list.

```
List of linters to disable (testify,test).
```

I just want to exclude `gotype` as it seems not to be compatible with Vendoring.
