### ISSUE TITLE
errcheck is slow

### ISSUE THREAD

**Issue by mhamrle** [alecthomas/gometalinter#96]
Using errcheck in gometalinter on bigger project is much slower that using errcheck directly. I think that problem is that gometalinter runs new process errcheck for every package. Errcheck loads not only the package but also all dependencies.
```
gometalinter --disable-all -E errcheck ./...
```

When using one process errcheck with all packages as params, it is much faster because the dependencies are loaded only once.
```
errcheck $(go list ./...)
```

In my case first run takes 90s but second only 2.5s, project has 139 packages.

**Comment by alecthomas** [comment]
Yes, this is correct. But the solution is to have distinctly separate logic for checkers that support multiple directories, and I think that will significantly complicate the code. See also #35.

**Comment by benma** [comment]
> But the solution is to have distinctly separate logic for checkers that support multiple directories

With the right abstractions, it shouldn't be too bad. I.e. there is only a limited number of ways to invoke all linters: by file, by file list, by package list, by directory, ...

The list of files/directories/packages can be retrieved from the input to gometalinter, and then it is only about setting a flag per linter in what way it should be called. In the beginning, only the slowest could be configured, like errcheck, while the rest is invoked like before.

I think the effort would definitely worth it, as gometalinter would be an excellent alternative to calling all the other linters manually, but using it is impractical when it is that much slower.

**Comment by alecthomas** [comment]
Yes, I'm fairly aware of how the linters are invoked... but it is not a trivial job to refactor the current code. PRs welcome.

**Comment by dominikh** [comment]
I'd like to point out that running errcheck on multiple packages at once will have higher memory usage than running on packages individually. For example, `errcheck ...`, where ... matches 2495 packages, takes about 4 GB of memory. The same applies to most tools that use `go/types` (including `unused`) – That may be something you want to take into consideration when fixing this issue.

**Comment by alecthomas** [comment]
That is also an excellent point.

**Comment by szubtsovskiy** [comment]
Seems like this fix broke things for us. We started getting following warnings:

> WARNING: failed to execute linter gosimple .: chdir src/...: no such file or directory
> WARNING: failed to execute linter golint -min_confidence 0.800000 .: chdir src/...: no such file or directory
> 

We run gometalinter using this command (from the project directory; we have to play with GOPATH since we are using gb to build the project):
```
GOPATH=`pwd`:`pwd`/vendor gometalinter --concurrency=4 --disable=gotype --disable=structcheck --disable=aligncheck --disable=varcheck --disable=dupl --disable=gocyclo --deadline=5m src/...
```

Any ideas? Thanks!

**Comment by alecthomas** [comment]
@szubtsovskiy This should be fixed.
