### ISSUE TITLE
Disable linter vet --composites=false

### ISSUE THREAD

**Issue by jtblin** [alecthomas/gometalinter#97]
I am trying to disable `--composites=false` for `vet` so trying to run with something like `--linter=vet:vet:--composites=false` but I'm getting
> gometalinter WARNING: exec: "vet": executable file not found in $PATH

`--linter=errcheck:errcheck:-ignore=Write` works for example. If I use `--linter=vet:go tool vet:--composites=false` it panics.

Thanks for your help.

**Comment by alecthomas** [comment]
Have a look right down the bottom of the README, there's an example:

```
gometalinter --linter='vet:go tool vet -printfuncs=Infof,Debugf,Warningf,Errorf {paths}:PATH:LINE:MESSAGE' .
```

**Comment by jtblin** [comment]
Arg sorry about that, I missed that one.

Thanks
