### ISSUE TITLE
Replace deadcode by unused?

### ISSUE THREAD

**Issue by alexcesaro** [alecthomas/gometalinter#98]
According to the author `unused` is slower but more powerful than `deadcode`: https://groups.google.com/d/msg/golang-nuts/sC51GN-X3EY/-BaPkYyfAgAJ

**Comment by alecthomas** [comment]
It definitely seems more comprehensive, but it's *much* slower. It might be a better idea to have both, with `unused` in the "slow linter" list disabled by `--fast`.

**Comment by alecthomas** [comment]
I think this would be okay to add once a solution to #96 is in place.
