### ISSUE TITLE
ineffassign incorrectly claims that an assignment is not used

### ISSUE THREAD

**Issue by kinghajj** [alecthomas/gometalinter#99]
func (f *Foo) Bar() (bzs []Baz, err error) {
    	if bs, err := ioutil.ReadFile(os.Getenv(bazesPathKey)); err == nil {
            // ineffassign claims that this is not used, but it's a return value
    		err = json.Unmarshal(bs, &bzs)
    	}
    	return
    }

**Comment by alecthomas** [comment]
File an issue against ineffassign...

**Comment by kinghajj** [comment]
Sorry, didn't realize how this worked! Just installed Atom/atom-go after a long absence from the Go community.
